/**
 * Generates a typed enum-lookup module from a Paraglide message catalog.
 *
 * Enum-valued labels live under a reserved `enum__<group>__<member>` namespace
 * (e.g. `enum__health__idle`). This turns each such group into a static, typed
 * map so app code does `health[value]()` instead of a dynamic key lookup:
 *
 *   export const health = {
 *     idle: m.enum__health__idle,
 *     backlogged: m.enum__health__backlogged,
 *   } satisfies EnumI18n<'idle' | 'backlogged'>
 *   export type HealthKey = keyof typeof health
 */

export interface GenerateEnumsOptions {
  /** Import specifier for the wrapped, branded `m` object. Default `'./messages.js'`. */
  messagesImport?: string
  /** Import specifier for the `I18nString` brand. Default `'@pikku/react'`. */
  i18nImport?: string
  /** Prefix marking an enum group. Default `'enum'`. */
  prefix?: string
  /** Namespace separator. Default `'__'`. */
  separator?: string
  /**
   * Called for each authoring issue (e.g. a member that isn't a valid JS
   * identifier and had to be quoted). Default: no-op. CLI/vite pass `console.warn`.
   */
  onWarn?: (message: string) => void
}

export interface EnumGroup {
  /** Raw group path between the prefix and the member (e.g. `booking__status`). */
  raw: string
  /** camelCase export identifier (e.g. `bookingStatus`). */
  ident: string
  /** Member names in catalog order. */
  members: string[]
}

const DEFAULTS: Required<GenerateEnumsOptions> = {
  messagesImport: './messages.js',
  i18nImport: '@pikku/react',
  prefix: 'enum',
  separator: '__',
  onWarn: () => {},
}

const isIdent = (s: string): boolean => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s)

const toCamel = (raw: string, separator: string): string =>
  raw
    .split(separator)
    .join('_')
    .split('_')
    .filter(Boolean)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('')

const toPascal = (camel: string): string => camel.charAt(0).toUpperCase() + camel.slice(1)

/** Group catalog keys under `<prefix><sep>…` into enum groups, preserving order. */
export function collectEnumGroups(keys: string[], options: GenerateEnumsOptions = {}): EnumGroup[] {
  const { prefix, separator } = { ...DEFAULTS, ...options }
  const head = prefix + separator
  const groups = new Map<string, string[]>()
  for (const key of keys) {
    if (!key.startsWith(head)) continue
    const parts = key.slice(head.length).split(separator)
    if (parts.length < 2) continue // need at least <group> + <member>
    const member = parts[parts.length - 1]
    const raw = parts.slice(0, -1).join(separator)
    const members = groups.get(raw) ?? groups.set(raw, []).get(raw)!
    if (!members.includes(member)) members.push(member)
  }
  return [...groups.entries()].map(([raw, members]) => ({
    raw,
    ident: toCamel(raw, separator),
    members,
  }))
}

/** Generate the full `i18n-enum.gen.ts` source from a catalog's keys. */
export function generateEnumsSource(keys: string[], options: GenerateEnumsOptions = {}): string {
  const opts = { ...DEFAULTS, ...options }
  const groups = collectEnumGroups(keys, opts)

  const fullKey = (raw: string, member: string): string =>
    `${opts.prefix}${opts.separator}${raw}${opts.separator}${member}`
  const access = (key: string): string => (isIdent(key) ? `m.${key}` : `m[${JSON.stringify(key)}]`)
  const memberKey = (member: string): string => (isIdent(member) ? member : JSON.stringify(member))

  const header =
    `// AUTO-GENERATED by @pikku/paraglide — do not edit.\n` +
    `// Source of truth: the \`${opts.prefix}${opts.separator}*\` keys in the message catalog.\n` +
    `import { m } from '${opts.messagesImport}'\n` +
    `import type { I18nString } from '${opts.i18nImport}'\n\n` +
    `/** A message accessor — call it at render time so the label tracks the active locale. */\n` +
    `export type I18nMessage = () => I18nString\n` +
    `/** A static, exhaustive map from an enum member to its branded i18n label. */\n` +
    `export type EnumI18n<E extends string> = Record<E, I18nMessage>\n`

  if (groups.length === 0) {
    return `${header}\n// No \`${opts.prefix}${opts.separator}*\` keys found in the catalog.\n`
  }

  const blocks = groups.map((g) => {
    for (const member of g.members) {
      if (!isIdent(member)) {
        opts.onWarn(
          `enum member '${fullKey(g.raw, member)}' is not a valid identifier — ` +
            `it was quoted as a fallback. Rename it to a valid identifier ` +
            `(e.g. spell out leading digits: '2_guests' → 'two_guests').`
        )
      }
    }
    const union = g.members.map((m) => JSON.stringify(m)).join(' | ')
    const entries = g.members.map((m) => `  ${memberKey(m)}: ${access(fullKey(g.raw, m))},`).join('\n')
    return (
      `export const ${g.ident} = {\n${entries}\n} satisfies EnumI18n<${union}>\n` +
      `export type ${toPascal(g.ident)}Key = keyof typeof ${g.ident}\n`
    )
  })

  return `${header}\n${blocks.join('\n')}`
}
