/**
 * This file was generated by the @pikku/cli
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */

// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string }
export type SayHelloOutput = { message: string; timestamp: number }
export type DisableToolInput = { name: string }
export type CalculateInput = {
  operation: 'add' | 'subtract' | 'multiply' | 'divide'
  a: number
  b: number
}
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L39C3Output =
  { type: string; text: string }[]
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L73C55Output =
  { uri: any; text: string }[]
export type GetUserInfoInput = { userId: string }
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L85C3Output =
  { uri: string; text: string }[]
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L121C66Output =
  { role: 'user'; content: { type: 'text'; text: string } }[]
export type DynamicPromptGeneratorInput = {
  topic: string
  complexity: 'beginner' | 'intermediate' | 'advanced'
  includeExamples?: boolean
}
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L140C4Output =
  { role: 'user'; content: { type: 'text'; text: string } }[]
export type OnConnectInput = 'hello!'
export type AuthenticateInput = { token: string; userId: string }
export type AuthenticateOutput = { authResult: boolean; action: 'auth' }
export type SubscribeInput = { name: string }
export type UnsubscribeInput = { name: string }
export type EmitMessageInput = { name: string }
export type EmitMessageOutput =
  | { timestamp: string; from: string }
  | { message: string }
export type OnMessageInput = 'hello'
export type OnMessageOutput = 'hey'
export type ProgressiveEnhancementExampleOutput = {
  state: 'initial' | 'pending' | 'done'
}
export type TimeSinceOpenedOutput = { count: number }
export type QueueWorkerInput = { message: string; fail: boolean }
export type QueueWorkerOutput = { result: string }
export type RpcTestInput = { in: number }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
  input: I
  output: O
}

export type QueueMap = {
  readonly 'hello-world-queue': QueueHandler<
    QueueWorkerInput,
    QueueWorkerOutput
  >
}

type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd
  getJob: QueueGetJob
}
