import { LocalVariablesService, LocalSecretService } from '@pikku/core/services'
import type { CoreSingletonServices } from '@pikku/core'
import type { ScheduledController } from '@cloudflare/workers-types'
import { WorkerEntrypoint } from 'cloudflare:workers'
import { runFetch } from './run-fetch.js'
import { runScheduled } from './run-scheduled.js'
import { runQueueJob } from '@pikku/core/queue'
import { pikkuState } from '@pikku/core/internal'
import type { QueueJob, QueueJobStatus } from '@pikku/core/queue'
import { CloudflareWebSocketHibernationServer } from './cloudflare-hibernation-websocket-server.js'
import { CloudflareEventHubService } from './cloudflare-eventhub-service.js'

export type CloudflareEnv = Record<string, unknown>

export interface ServiceFactories {
  createConfig: (
    variables: LocalVariablesService,
    ...args: unknown[]
  ) => Promise<unknown>
  createSingletonServices: (
    config: unknown,
    existingServices?: Partial<Record<string, unknown>>
  ) => Promise<CoreSingletonServices>
  /**
   * Optional callback to create platform services from CF env bindings.
   * Returns services to merge into existingServices.
   * Generated by the deploy codegen based on unit capabilities.
   */
  createPlatformServices?: (
    env: CloudflareEnv
  ) => Record<string, unknown> | Promise<Record<string, unknown>>
}

let cachedServices: CoreSingletonServices | null = null

let cachedEnv: CloudflareEnv | null = null

/**
 * Returns the Cloudflare `env` that was last passed into the worker handler,
 * or `null` if called before any request. Lets user `createSingletonServices`
 * read CF-specific bindings (D1, R2, KV, queue producers, etc.) without
 * threading `env` through every signature.
 */
export function getCloudflareEnv(): CloudflareEnv | null {
  return cachedEnv
}

async function setupServices(
  env: CloudflareEnv,
  factories: ServiceFactories
): Promise<CoreSingletonServices> {
  cachedEnv = env
  if (cachedServices) return cachedServices
  const variables = new LocalVariablesService(
    env as Record<string, string | undefined>
  )
  const config = await factories.createConfig(variables)
  const secrets = new LocalSecretService(variables)

  const platformServices = factories.createPlatformServices
    ? await factories.createPlatformServices(env)
    : {}

  cachedServices = await factories.createSingletonServices(config, {
    variables,
    secrets,
    ...platformServices,
  })
  return cachedServices
}

/**
 * Handles processing a queue batch message.
 */
async function processQueueBatch(batch: {
  queue?: string
  messages: Array<{ id: string; body: unknown }>
}): Promise<void> {
  for (const message of batch.messages) {
    let body: Record<string, unknown>
    try {
      body =
        typeof message.body === 'string'
          ? JSON.parse(message.body)
          : (message.body as Record<string, unknown>)
    } catch {
      console.error('CF Queue: failed to parse message body', message.id)
      continue
    }
    // Use batch.queue (CF provides the queue name) or fall back to body.queueName.
    // CF queue names may have a project prefix (e.g. "functions-wf-step-create-todo")
    // but the queue meta uses unprefixed names. Try both.
    const rawQueueName = batch.queue ?? (body.queueName as string) ?? 'unknown'
    const queueMeta = pikkuState(null, 'queue', 'meta')
    const queueName = queueMeta[rawQueueName]
      ? rawQueueName
      : (Object.keys(queueMeta)
          .filter((k) => rawQueueName.endsWith(k))
          .sort((a, b) => b.length - a.length)[0] ?? rawQueueName)
    const job: QueueJob = {
      queueName,
      data: body.data ?? body,
      id: message.id,
      status: async () => 'active' as QueueJobStatus,
      metadata: () => ({
        processedAt: new Date(),
        attemptsMade: 0,
        maxAttempts: undefined,
        result: undefined,
        progress: 0,
        createdAt: new Date(),
        completedAt: undefined,
        failedAt: undefined,
        error: undefined,
      }),
      waitForCompletion: async () => {
        throw new Error('CF Queues do not support waitForCompletion')
      },
    }
    console.log(
      `[QUEUE] Running job: queue=${queueName}, id=${message.id}, data=${JSON.stringify(job.data).slice(0, 200)}`
    )
    try {
      await runQueueJob({ job })
      console.log(`[QUEUE] Job completed: queue=${queueName}, id=${message.id}`)
    } catch (e: unknown) {
      console.error(
        `[QUEUE] Job failed: queue=${queueName}, id=${message.id}`,
        (e as Error).message
      )
      throw e
    }
  }
}

/**
 * Creates a WorkerEntrypoint class with the requested handler methods.
 *
 * Methods on a WorkerEntrypoint subclass are exposed via Worker RPC: any
 * service binding (or dispatch-namespace `env.NS.get(name)`) can call
 * `.fetch()`, `.queue()`, `.scheduled()` directly. This unblocks queue
 * fan-out from a per-stage dispatcher to namespace scripts on Workers
 * for Platforms (CF queue consumers can't bind to namespace scripts
 * directly, so a dispatcher consumes and forwards via RPC).
 *
 * The class is constructed once per Worker instance; CF passes ctx, env
 * to the constructor. We stash env in module-scope cachedEnv so user
 * service factories can read it via getCloudflareEnv().
 */
export function createCloudflareHandler(
  factories: ServiceFactories,
  handlerTypes: string[]
) {
  const includesFetch = handlerTypes.includes('fetch')
  const includesQueue = handlerTypes.includes('queue')
  const includesScheduled = handlerTypes.includes('scheduled')
  const fallbackFetchMessage = `Worker active (handlers: ${handlerTypes.join(', ')})`

  return class PikkuHandler extends WorkerEntrypoint<CloudflareEnv> {
    async fetch(request: Request): Promise<Response> {
      if (includesFetch) {
        const services = await setupServices(this.env, factories)

        const url = new URL(request.url)
        if (url.pathname === '/__pikku/debug') {
          const queueMeta = pikkuState(null, 'queue', 'meta')
          const workflowMeta = pikkuState(null, 'workflows', 'meta')
          const queueRegistrations = pikkuState(null, 'queue', 'registrations')
          return new Response(
            JSON.stringify(
              {
                hasQueueService: !!services.queueService,
                hasWorkflowService: !!services.workflowService,
                queueMetaKeys: Object.keys(queueMeta ?? {}),
                workflowMetaKeys: Object.keys(workflowMeta ?? {}),
                queueRegistrationKeys: queueRegistrations
                  ? [...queueRegistrations.keys()]
                  : [],
                envBindings: Object.keys(this.env).filter(
                  (k) =>
                    k.includes('WF_') ||
                    k.includes('QUEUE') ||
                    k.includes('WORKFLOW')
                ),
              },
              null,
              2
            ),
            { headers: { 'Content-Type': 'application/json' } }
          )
        }

        return runFetch(request, undefined, { exposeErrors: true })
      }
      // Health-check fallback for units with no fetch role
      return new Response(fallbackFetchMessage, { status: 200 })
    }

    async queue(batch: {
      queue?: string
      messages: Array<{ id: string; body: unknown }>
    }): Promise<void> {
      if (!includesQueue) return
      try {
        await setupServices(this.env, factories)
        console.log(
          `[QUEUE] Processing batch from "${batch.queue}", ${batch.messages.length} messages`
        )
        await processQueueBatch(batch)
        console.log(`[QUEUE] Batch processed successfully`)
      } catch (e: unknown) {
        console.error(
          `[QUEUE] Error processing batch:`,
          (e as Error).message,
          (e as Error).stack
        )
        throw e
      }
    }

    async scheduled(controller: ScheduledController): Promise<void> {
      if (!includesScheduled) return
      await setupServices(this.env, factories)
      await runScheduled(controller)
    }
  }
}

/**
 * Creates a WorkerEntrypoint class with a fetch() handler for HTTP, agent,
 * RPC, and workflow-orchestrator units. WorkerEntrypoint exposes methods
 * via Worker RPC so service-binding callers (and dispatch-namespace stubs)
 * can invoke them across Worker boundaries.
 */
export function createCloudflareWorkerHandler(factories: ServiceFactories) {
  return class PikkuWorker extends WorkerEntrypoint<CloudflareEnv> {
    async fetch(request: Request): Promise<Response> {
      await setupServices(this.env, factories)
      return runFetch(request)
    }
  }
}

/**
 * Creates a WorkerEntrypoint class with a scheduled() handler for cron units.
 */
export function createCloudflareCronHandler(factories: ServiceFactories) {
  return class PikkuCron extends WorkerEntrypoint<CloudflareEnv> {
    async fetch(): Promise<Response> {
      return new Response('Cron worker active', { status: 200 })
    }
    async scheduled(controller: ScheduledController): Promise<void> {
      await setupServices(this.env, factories)
      await runScheduled(controller)
    }
  }
}

/**
 * Creates a WorkerEntrypoint class with a queue() handler for queue-consumer
 * and workflow-step units. queue() is RPC-callable, so a dispatcher can do
 * `env.NS.get(name).queue(batch)` to fan a batch out to a namespace script.
 */
export function createCloudflareQueueHandler(factories: ServiceFactories) {
  return class PikkuQueue extends WorkerEntrypoint<CloudflareEnv> {
    async fetch(): Promise<Response> {
      return new Response('Queue consumer active', { status: 200 })
    }
    async queue(batch: {
      queue?: string
      messages: Array<{ id: string; body: unknown }>
    }): Promise<void> {
      await setupServices(this.env, factories)
      await processQueueBatch(batch)
    }
  }
}

/**
 * Creates an ExportedHandler with a fetch() entrypoint for MCP units.
 * MCP uses the same HTTP transport — the MCP protocol is handled by pikku core.
 */
export function createCloudflareMCPHandler(factories: ServiceFactories) {
  return createCloudflareWorkerHandler(factories)
}

/**
 * Module-level factories ref for the WebSocket DO class.
 * Set by createCloudflareWebSocketHandler before the DO is used.
 */
let wsFactories: ServiceFactories | null = null

/**
 * WebSocket Durable Object class for channel units.
 * Extends CloudflareWebSocketHibernationServer with auto service setup.
 */
export class PikkuWebSocketHibernationServer extends CloudflareWebSocketHibernationServer {
  protected async getParams() {
    if (!wsFactories) {
      throw new Error(
        'WebSocket handler not initialized — call createCloudflareWebSocketHandler first'
      )
    }
    const singletonServices = await setupServices(this.env, wsFactories)
    const servicesWithEventHub = singletonServices as CoreSingletonServices & {
      eventHub: CloudflareEventHubService
    }
    servicesWithEventHub.eventHub = new CloudflareEventHubService(
      singletonServices.logger,
      this.ctx
    )
    return { singletonServices: servicesWithEventHub }
  }
}

/**
 * Creates an ExportedHandler with fetch() that delegates to a WebSocket
 * Durable Object.
 *
 * The entry file must also export PikkuWebSocketHibernationServer as the DO class:
 *
 * ```ts
 * export { PikkuWebSocketHibernationServer as WebSocketHibernationServer } from '@pikku/cloudflare'
 * export default createCloudflareWebSocketHandler(factories)
 * ```
 */
export function createCloudflareWebSocketHandler(factories: ServiceFactories) {
  wsFactories = factories
  return class PikkuWebSocketRouter extends WorkerEntrypoint<CloudflareEnv> {
    async fetch(request: Request): Promise<Response> {
      await setupServices(this.env, factories)
      const durableObject = this.env.WEBSOCKET_HIBERNATION_SERVER as
        | {
            idFromName: (name: string) => { toString: () => string }
            get: (id: unknown) => {
              fetch: (req: Request) => Promise<Response>
            }
          }
        | undefined
      if (!durableObject) {
        return new Response(
          'WEBSOCKET_HIBERNATION_SERVER Durable Object binding not found in env',
          { status: 503 }
        )
      }
      const id = durableObject.idFromName('default')
      const stub = durableObject.get(id)
      return stub.fetch(request)
    }
  }
}
