import { LocalVariablesService, LocalSecretService } from '@pikku/core/services'
import type { CoreSingletonServices } from '@pikku/core'
import type { ScheduledController } from '@cloudflare/workers-types'
import { runFetch } from './run-fetch.js'
import { runScheduled } from './run-scheduled.js'
import { runQueueJob } from '@pikku/core/queue'
import { pikkuState } from '@pikku/core/internal'
import type { QueueJob, QueueJobStatus } from '@pikku/core/queue'
import { CloudflareWebSocketHibernationServer } from './cloudflare-hibernation-websocket-server.js'
import { CloudflareEventHubService } from './cloudflare-eventhub-service.js'

export type CloudflareEnv = Record<string, unknown>

export interface ServiceFactories {
  createConfig: (
    variables: LocalVariablesService,
    ...args: unknown[]
  ) => Promise<unknown>
  createSingletonServices: (
    config: unknown,
    existingServices?: Partial<Record<string, unknown>>
  ) => Promise<CoreSingletonServices>
  /**
   * Optional callback to create platform services from CF env bindings.
   * Returns services to merge into existingServices.
   * Generated by the deploy codegen based on unit capabilities.
   */
  createPlatformServices?: (
    env: CloudflareEnv
  ) => Record<string, unknown> | Promise<Record<string, unknown>>
}

let cachedServices: CoreSingletonServices | null = null

let cachedEnv: CloudflareEnv | null = null

/**
 * Returns the Cloudflare `env` that was last passed into the worker handler,
 * or `null` if called before any request. Lets user `createSingletonServices`
 * read CF-specific bindings (D1, R2, KV, queue producers, etc.) without
 * threading `env` through every signature.
 */
export function getCloudflareEnv(): CloudflareEnv | null {
  return cachedEnv
}

async function setupServices(
  env: CloudflareEnv,
  factories: ServiceFactories
): Promise<CoreSingletonServices> {
  cachedEnv = env
  if (cachedServices) return cachedServices
  const variables = new LocalVariablesService(
    env as Record<string, string | undefined>
  )
  const config = await factories.createConfig(variables)
  const secrets = new LocalSecretService(variables)

  const platformServices = factories.createPlatformServices
    ? await factories.createPlatformServices(env)
    : {}

  cachedServices = await factories.createSingletonServices(config, {
    variables,
    secrets,
    ...platformServices,
  })
  return cachedServices
}

/**
 * Handles processing a queue batch message.
 */
async function processQueueBatch(batch: {
  queue?: string
  messages: Array<{ id: string; body: unknown }>
}): Promise<void> {
  for (const message of batch.messages) {
    let body: Record<string, unknown>
    try {
      body =
        typeof message.body === 'string'
          ? JSON.parse(message.body)
          : (message.body as Record<string, unknown>)
    } catch {
      console.error('CF Queue: failed to parse message body', message.id)
      continue
    }
    // Use batch.queue (CF provides the queue name) or fall back to body.queueName.
    // CF queue names may have a project prefix (e.g. "functions-wf-step-create-todo")
    // but the queue meta uses unprefixed names. Try both.
    const rawQueueName = batch.queue ?? (body.queueName as string) ?? 'unknown'
    const queueMeta = pikkuState(null, 'queue', 'meta')
    const queueName = queueMeta[rawQueueName]
      ? rawQueueName
      : (Object.keys(queueMeta)
          .filter((k) => rawQueueName.endsWith(k))
          .sort((a, b) => b.length - a.length)[0] ?? rawQueueName)
    const job: QueueJob = {
      queueName,
      data: body.data ?? body,
      id: message.id,
      status: async () => 'active' as QueueJobStatus,
      metadata: () => ({
        processedAt: new Date(),
        attemptsMade: 0,
        maxAttempts: undefined,
        result: undefined,
        progress: 0,
        createdAt: new Date(),
        completedAt: undefined,
        failedAt: undefined,
        error: undefined,
      }),
      waitForCompletion: async () => {
        throw new Error('CF Queues do not support waitForCompletion')
      },
    }
    console.log(
      `[QUEUE] Running job: queue=${queueName}, id=${message.id}, data=${JSON.stringify(job.data).slice(0, 200)}`
    )
    try {
      await runQueueJob({ job })
      console.log(`[QUEUE] Job completed: queue=${queueName}, id=${message.id}`)
    } catch (e: unknown) {
      console.error(
        `[QUEUE] Job failed: queue=${queueName}, id=${message.id}`,
        (e as Error).message
      )
      throw e
    }
  }
}

/**
 * Creates a combined ExportedHandler based on which handler types the unit needs.
 *
 * Instead of one handler factory per role, a unit declares which handlers it needs
 * (fetch, queue, scheduled) and this function builds a single default export
 * that includes all of them.
 */
export function createCloudflareHandler(
  factories: ServiceFactories,
  handlerTypes: string[]
) {
  const result: Record<string, unknown> = {}

  if (handlerTypes.includes('fetch')) {
    result.fetch = async (request: Request, env: CloudflareEnv) => {
      const services = await setupServices(env, factories)

      // Debug endpoint: /__pikku/debug
      const url = new URL(request.url)
      if (url.pathname === '/__pikku/debug') {
        const queueMeta = pikkuState(null, 'queue', 'meta')
        const workflowMeta = pikkuState(null, 'workflows', 'meta')
        const queueRegistrations = pikkuState(null, 'queue', 'registrations')
        return new Response(
          JSON.stringify(
            {
              hasQueueService: !!services.queueService,
              hasWorkflowService: !!services.workflowService,
              queueMetaKeys: Object.keys(queueMeta ?? {}),
              workflowMetaKeys: Object.keys(workflowMeta ?? {}),
              queueRegistrationKeys: queueRegistrations
                ? [...queueRegistrations.keys()]
                : [],
              envBindings: Object.keys(env).filter(
                (k) =>
                  k.includes('WF_') ||
                  k.includes('QUEUE') ||
                  k.includes('WORKFLOW')
              ),
            },
            null,
            2
          ),
          { headers: { 'Content-Type': 'application/json' } }
        )
      }

      // Debug endpoint: /__pikku/test-step — test insertStepState + queueStepWorker
      if (url.pathname === '/__pikku/test-step') {
        try {
          const wfService = services.workflowService
          if (!wfService)
            return new Response('No workflowService', { status: 500 })
          const queueService = services.queueService
          if (!queueService)
            return new Response('No queueService', { status: 500 })

          // Try insertStepState
          const testRunId = 'test-' + crypto.randomUUID().slice(0, 8)
          try {
            await wfService.createRun(
              'createAndNotifyWorkflow',
              { test: true },
              false,
              'test',
              { type: 'debug' }
            )
          } catch (e: unknown) {
            return new Response(
              JSON.stringify({
                step: 'createRun',
                error: (e as Error).message,
              }),
              { status: 500 }
            )
          }

          // Try queue send
          try {
            await queueService.add('wf-step-create-todo', {
              test: true,
              runId: testRunId,
            })
          } catch (e: unknown) {
            return new Response(
              JSON.stringify({
                step: 'queueSend',
                error: (e as Error).message,
              }),
              { status: 500 }
            )
          }

          return new Response(JSON.stringify({ success: true, testRunId }), {
            headers: { 'Content-Type': 'application/json' },
          })
        } catch (e: unknown) {
          return new Response(
            JSON.stringify({
              error: (e as Error).message,
              stack: (e as Error).stack,
            }),
            { status: 500 }
          )
        }
      }

      return runFetch(request, undefined, { exposeErrors: true })
    }
  }

  if (handlerTypes.includes('queue')) {
    result.queue = async (
      batch: { queue?: string; messages: Array<{ id: string; body: unknown }> },
      env: CloudflareEnv
    ) => {
      try {
        await setupServices(env, factories)
        console.log(
          `[QUEUE] Processing batch from "${batch.queue}", ${batch.messages.length} messages`
        )
        await processQueueBatch(batch)
        console.log(`[QUEUE] Batch processed successfully`)
      } catch (e: unknown) {
        console.error(
          `[QUEUE] Error processing batch:`,
          (e as Error).message,
          (e as Error).stack
        )
        throw e
      }
    }
  }

  if (handlerTypes.includes('scheduled')) {
    result.scheduled = async (
      controller: ScheduledController,
      env: CloudflareEnv
    ) => {
      await setupServices(env, factories)
      await runScheduled(controller)
    }
  }

  // If no fetch handler was requested, add a health check endpoint
  if (!handlerTypes.includes('fetch')) {
    const activeHandlers = handlerTypes.join(', ')
    result.fetch = async () => {
      return new Response(`Worker active (handlers: ${activeHandlers})`, {
        status: 200,
      })
    }
  }

  return result
}

/**
 * Creates an ExportedHandler with a fetch() entrypoint for HTTP, agent, RPC,
 * and workflow-orchestrator units.
 */
export function createCloudflareWorkerHandler(factories: ServiceFactories) {
  return {
    async fetch(request: Request, env: CloudflareEnv) {
      await setupServices(env, factories)
      return runFetch(request)
    },
  }
}

/**
 * Creates an ExportedHandler with a scheduled() entrypoint for cron units.
 */
export function createCloudflareCronHandler(factories: ServiceFactories) {
  return {
    async fetch() {
      return new Response('Cron worker active', { status: 200 })
    },
    async scheduled(controller: ScheduledController, env: CloudflareEnv) {
      await setupServices(env, factories)
      await runScheduled(controller)
    },
  }
}

/**
 * Creates an ExportedHandler with a queue() entrypoint for queue-consumer
 * and workflow-step units.
 */
export function createCloudflareQueueHandler(factories: ServiceFactories) {
  return {
    async fetch() {
      return new Response('Queue consumer active', { status: 200 })
    },
    async queue(
      batch: { messages: Array<{ id: string; body: unknown }> },
      env: CloudflareEnv
    ) {
      await setupServices(env, factories)
      await processQueueBatch(batch)
    },
  }
}

/**
 * Creates an ExportedHandler with a fetch() entrypoint for MCP units.
 * MCP uses the same HTTP transport — the MCP protocol is handled by pikku core.
 */
export function createCloudflareMCPHandler(factories: ServiceFactories) {
  return createCloudflareWorkerHandler(factories)
}

/**
 * Module-level factories ref for the WebSocket DO class.
 * Set by createCloudflareWebSocketHandler before the DO is used.
 */
let wsFactories: ServiceFactories | null = null

/**
 * WebSocket Durable Object class for channel units.
 * Extends CloudflareWebSocketHibernationServer with auto service setup.
 */
export class PikkuWebSocketHibernationServer extends CloudflareWebSocketHibernationServer {
  protected async getParams() {
    if (!wsFactories) {
      throw new Error(
        'WebSocket handler not initialized — call createCloudflareWebSocketHandler first'
      )
    }
    const singletonServices = await setupServices(this.env, wsFactories)
    const servicesWithEventHub = singletonServices as CoreSingletonServices & {
      eventHub: CloudflareEventHubService
    }
    servicesWithEventHub.eventHub = new CloudflareEventHubService(
      singletonServices.logger,
      this.ctx
    )
    return { singletonServices: servicesWithEventHub }
  }
}

/**
 * Creates an ExportedHandler with fetch() that delegates to a WebSocket
 * Durable Object.
 *
 * The entry file must also export PikkuWebSocketHibernationServer as the DO class:
 *
 * ```ts
 * export { PikkuWebSocketHibernationServer as WebSocketHibernationServer } from '@pikku/cloudflare'
 * export default createCloudflareWebSocketHandler(factories)
 * ```
 */
export function createCloudflareWebSocketHandler(factories: ServiceFactories) {
  wsFactories = factories
  return {
    async fetch(request: Request, env: CloudflareEnv) {
      await setupServices(env, factories)
      const durableObject = env.WEBSOCKET_HIBERNATION_SERVER as
        | {
            idFromName: (name: string) => { toString: () => string }
            get: (id: unknown) => {
              fetch: (req: Request) => Promise<Response>
            }
          }
        | undefined
      if (!durableObject) {
        return new Response(
          'WEBSOCKET_HIBERNATION_SERVER Durable Object binding not found in env',
          { status: 503 }
        )
      }
      const id = durableObject.idFromName('default')
      const stub = durableObject.get(id)
      return stub.fetch(request)
    },
  }
}
