/**
 * This file was generated by the @pikku/cli
 */
import { addSchema } from '@pikku/core/schema'

import * as SayHelloInput from './schemas/SayHelloInput.schema.json' with { type: 'json' }
addSchema('SayHelloInput', SayHelloInput)

import * as SayHelloOutput from './schemas/SayHelloOutput.schema.json' with { type: 'json' }
addSchema('SayHelloOutput', SayHelloOutput)

import * as DisableToolInput from './schemas/DisableToolInput.schema.json' with { type: 'json' }
addSchema('DisableToolInput', DisableToolInput)

import * as CalculateInput from './schemas/CalculateInput.schema.json' with { type: 'json' }
addSchema('CalculateInput', CalculateInput)

import * as PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L39C3Output from './schemas/PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L39C3Output.schema.json' with { type: 'json' }
addSchema(
  'PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L39C3Output',
  PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L39C3Output
)

import * as PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L73C55Output from './schemas/PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L73C55Output.schema.json' with { type: 'json' }
addSchema(
  'PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L73C55Output',
  PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L73C55Output
)

import * as GetUserInfoInput from './schemas/GetUserInfoInput.schema.json' with { type: 'json' }
addSchema('GetUserInfoInput', GetUserInfoInput)

import * as PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L85C3Output from './schemas/PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L85C3Output.schema.json' with { type: 'json' }
addSchema(
  'PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L85C3Output',
  PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L85C3Output
)

import * as PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L121C66Output from './schemas/PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L121C66Output.schema.json' with { type: 'json' }
addSchema(
  'PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L121C66Output',
  PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L121C66Output
)

import * as DynamicPromptGeneratorInput from './schemas/DynamicPromptGeneratorInput.schema.json' with { type: 'json' }
addSchema('DynamicPromptGeneratorInput', DynamicPromptGeneratorInput)

import * as PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L140C4Output from './schemas/PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L140C4Output.schema.json' with { type: 'json' }
addSchema(
  'PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L140C4Output',
  PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L140C4Output
)

import * as OnConnectInput from './schemas/OnConnectInput.schema.json' with { type: 'json' }
addSchema('OnConnectInput', OnConnectInput)

import * as AuthenticateInput from './schemas/AuthenticateInput.schema.json' with { type: 'json' }
addSchema('AuthenticateInput', AuthenticateInput)

import * as AuthenticateOutput from './schemas/AuthenticateOutput.schema.json' with { type: 'json' }
addSchema('AuthenticateOutput', AuthenticateOutput)

import * as SubscribeInput from './schemas/SubscribeInput.schema.json' with { type: 'json' }
addSchema('SubscribeInput', SubscribeInput)

import * as UnsubscribeInput from './schemas/UnsubscribeInput.schema.json' with { type: 'json' }
addSchema('UnsubscribeInput', UnsubscribeInput)

import * as EmitMessageInput from './schemas/EmitMessageInput.schema.json' with { type: 'json' }
addSchema('EmitMessageInput', EmitMessageInput)

import * as EmitMessageOutput from './schemas/EmitMessageOutput.schema.json' with { type: 'json' }
addSchema('EmitMessageOutput', EmitMessageOutput)

import * as OnMessageInput from './schemas/OnMessageInput.schema.json' with { type: 'json' }
addSchema('OnMessageInput', OnMessageInput)

import * as OnMessageOutput from './schemas/OnMessageOutput.schema.json' with { type: 'json' }
addSchema('OnMessageOutput', OnMessageOutput)

import * as ProgressiveEnhancementExampleOutput from './schemas/ProgressiveEnhancementExampleOutput.schema.json' with { type: 'json' }
addSchema(
  'ProgressiveEnhancementExampleOutput',
  ProgressiveEnhancementExampleOutput
)

import * as TimeSinceOpenedOutput from './schemas/TimeSinceOpenedOutput.schema.json' with { type: 'json' }
addSchema('TimeSinceOpenedOutput', TimeSinceOpenedOutput)

import * as QueueWorkerInput from './schemas/QueueWorkerInput.schema.json' with { type: 'json' }
addSchema('QueueWorkerInput', QueueWorkerInput)

import * as QueueWorkerOutput from './schemas/QueueWorkerOutput.schema.json' with { type: 'json' }
addSchema('QueueWorkerOutput', QueueWorkerOutput)

import * as RpcTestInput from './schemas/RpcTestInput.schema.json' with { type: 'json' }
addSchema('RpcTestInput', RpcTestInput)
