/**
 * This file was generated by the @pikku/cli
 */
import './functions/pikku-functions-meta.gen.js'
import './scheduler/pikku-schedules-meta.gen.js'
import './functions/pikku-functions.gen.js'
import './schemas/register.gen.js'
import './scheduler/pikku-schedules.gen.js'
