//! Generated by pikku, and rewritten by `pikku app native add` and `upgrade`.
//! Edits here are lost: initialise your own plugins in lib.rs.

/// Every plugin in this app's `native.plugins`, initialised.
pub fn plugins<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
    builder
}
