/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('mcp', 'resourcesMeta', {
  getStaticResource: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L68C3',
    uri: 'getStaticResource',
    title: 'Static Resource',
    description: 'Gets a static resource with predefined data',
    inputSchema: null,
    outputSchema: 'GetStaticResourceOutput',
  },
  'getUserInfo/{userId}': {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L80C3',
    uri: 'getUserInfo/{userId}',
    title: 'User Information',
    description: 'Retrieve user information by user ID',
    tags: ['user', 'profile', 'data'],
    inputSchema: 'GetUserInfoInput',
    outputSchema: 'GetUserInfoOutput',
  },
})
pikkuState('mcp', 'toolsMeta', {
  sayHello: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L12C3',
    name: 'sayHello',
    description: 'Greet someone with a friendly hello message',
    tags: ['greeting', 'hello', 'demo'],
    inputSchema: 'SayHelloInput',
    outputSchema: 'SayHelloOutput',
  },
  calculate: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L31C3',
    name: 'calculate',
    description:
      'Perform basic mathematical operations (add, subtract, multiply, divide)',
    tags: ['math', 'calculator', 'arithmetic'],
    inputSchema: 'CalculateInput',
    outputSchema: 'CalculateOutput',
  },
})
pikkuState('mcp', 'promptsMeta', {
  getStaticResource: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L113C66',
    name: 'getStaticResource',
    description: 'A static prompt that returns a predefined message',
    inputSchema: null,
    outputSchema: 'PikkuFn_src_mcp_functions_ts_L113C66Output',
    arguments: [],
  },
  dynamicPromptGenerator: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L133C4',
    name: 'dynamicPromptGenerator',
    description:
      'Generate educational content with progressive complexity and optional examples',
    tags: ['education', 'content', 'progressive', 'examples'],
    inputSchema: 'DynamicPromptGeneratorInput',
    outputSchema: 'PikkuFn_src_mcp_functions_ts_L133C4Output',
    arguments: [
      {
        name: 'topic',
        description: 'topic parameter',
        required: true,
      },
      {
        name: 'complexity',
        description: 'complexity parameter',
        required: true,
      },
      {
        name: 'includeExamples',
        description: 'includeExamples parameter',
        required: false,
      },
    ],
  },
})
