/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('mcp', 'meta', {
  sayHello: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L10C3',
    name: 'sayHello',
    description: 'Greet someone with a friendly hello message',
    type: 'tool',
    docs: {
      summary: 'Say hello to someone',
      description:
        'A simple greeting tool that returns a personalized hello message with timestamp',
      tags: ['greeting', 'hello', 'demo'],
    },
  },
  calculate: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L27C3',
    name: 'calculate',
    description:
      'Perform basic mathematical operations (add, subtract, multiply, divide)',
    type: 'tool',
    docs: {
      summary: 'Basic calculator',
      description: 'Performs basic arithmetic operations between two numbers',
      tags: ['math', 'calculator', 'arithmetic'],
    },
  },
  getUserInfo: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L66C3',
    name: 'getUserInfo',
    description: 'Retrieve user information by user ID',
    type: 'resource',
    docs: {
      summary: 'Get user data',
      description:
        'Fetches user profile information including name, email, and last login',
      tags: ['user', 'profile', 'data'],
    },
  },
})
