/**
 * This file was generated by the @pikku/cli
 */
import '../pikku-functions-meta.gen.js'
import './mcp-endpoints-meta.gen.js'
import '../pikku-functions.gen.js'
import '../schemas/register.gen.js'
import './mcp-endpoints.gen.js'
