import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { MantineBlock } from '../src/blocks/types.js'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const BLOCKS = join(SCRIPT_DIR, '../blocks')
const OUT = join(SCRIPT_DIR, '../src/blocks/blocks.gen.ts')

type Meta = Partial<MantineBlock> & {
  name: string
  title: string
  description: string
}

const blocks: MantineBlock[] = []
for (const dir of readdirSync(BLOCKS).sort()) {
  const metaPath = join(BLOCKS, dir, 'meta.json')
  if (!existsSync(metaPath)) continue
  const meta = JSON.parse(readFileSync(metaPath, 'utf8')) as Meta
  const source: Record<string, string> = {}
  for (const file of readdirSync(join(BLOCKS, dir)).sort()) {
    if (file !== 'meta.json')
      source[file] = readFileSync(join(BLOCKS, dir, file), 'utf8')
  }
  blocks.push({
    name: meta.name,
    title: meta.title,
    description: meta.description,
    tags: meta.tags ?? [],
    dependsOn: meta.dependsOn ?? [],
    npmDeps: meta.npmDeps ?? [],
    internal: meta.internal ?? false,
    i18nKeys: meta.i18nKeys ?? {},
    ...(meta.usage ? { usage: meta.usage } : {}),
    source,
  })
}
blocks.sort((a, b) => a.name.localeCompare(b.name))

const banner = [
  '// Generated by scripts/generate-blocks.ts from blocks/ — do not edit by hand.',
  "import type { MantineBlock } from './types.js'",
  '',
].join('\n')

writeFileSync(
  OUT,
  `${banner}\nexport const MANTINE_BLOCKS: MantineBlock[] = ${JSON.stringify(blocks, null, 2)}\n`
)
const tags = [...new Set(blocks.flatMap((b) => b.tags))].sort()
console.log(`wrote ${OUT}: ${blocks.length} blocks, ${tags.length} tags`)
