#:schema node_modules/wrangler/config-schema.json
name = "functions-agent-main-router"
main = "bundle.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "functions-db"
database_id = "pikku"

[ai]
binding = "AI"

[[services]]
binding = "AGENT_TODO_ASSISTANT"
service = "functions-agent-todo-assistant"

[[services]]
binding = "AGENT_DAILY_PLANNER"
service = "functions-agent-daily-planner"
