#:schema node_modules/wrangler/config-schema.json
name = "functions-process-reminder"
main = "bundle.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[[queues.consumers]]
queue = "functions-todo-reminders"
max_batch_size = 10
max_batch_timeout = 5
