import type { ScopeDefinitions } from '@pikku/core/scope'
import { flattenScopeDefinitions } from '@pikku/core/scope'

export interface SerializeScopesOptions {
  definitions: ScopeDefinitions
}

const quote = (value: string) => `'${value.replace(/'/g, "\\'")}'`

/**
 * Generates the `ScopeId` union and scope metadata from `wireScope`
 * declarations.
 *
 * The union carries every declared node plus a wildcard form for each node that
 * has descendants — `admin:*` is requirable when `admin` has children, but a
 * leaf's wildcard would grant nothing beyond the leaf itself, so it is omitted.
 * The bare `*` is never emitted: it is a valid grant but never a sensible
 * requirement.
 */
export const serializeScopesTypes = ({
  definitions,
}: SerializeScopesOptions) => {
  const flat = flattenScopeDefinitions(definitions)
  const ids = flat.map((s) => s.id)

  const hasChildren = (id: string) =>
    ids.some((other) => other.startsWith(`${id}:`))

  const requirable = [
    ...ids,
    ...ids.filter(hasChildren).map((id) => `${id}:*`),
  ].sort()

  const union =
    requirable.length > 0
      ? `\n${requirable.map((id) => `  | ${quote(id)}`).join('\n')}`
      : ' never'

  const metaEntries = [...flat]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((scope) => {
      const displayName = definitions.find(
        (d) => d.name === scope.id
      )?.displayName
      const parts = [`id: ${quote(scope.id)}`]
      if (displayName) {
        parts.push(`displayName: ${quote(displayName)}`)
      }
      if (scope.description) {
        parts.push(`description: ${quote(scope.description)}`)
      }
      return `  ${quote(scope.id)}: { ${parts.join(', ')} },`
    })

  const listEntries = [...flat]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((scope) => {
      const parts = [`id: ${quote(scope.id)}`]
      if (scope.description) {
        parts.push(`description: ${quote(scope.description)}`)
      }
      return `  { ${parts.join(', ')} },`
    })

  return `/**
 * This file was generated by the @pikku/cli
 */
import type { FlatScope } from '@pikku/core/scope'

/**
 * Every scope a function can require.
 *
 * A \`:*\` entry requires the scope and all of its descendants. Held grants are
 * matched against this by \`verifyScopes\` — \`admin:*\` on a session satisfies
 * any \`admin:...\` requirement.
 */
export type ScopeId =${union}

export interface ScopeMeta {
  id: ScopeId
  displayName?: string
  description?: string
}

/** Declared scopes, keyed by id. Rendered by the console when granting. */
export const SCOPES_META: Record<string, ScopeMeta> = {
${metaEntries.join('\n')}
}

/**
 * The declared scope set, for a ScopeService to sync into its store.
 * Additive: removing a declaration leaves an inert row rather than revoking a
 * grant mid-deploy. Use \`pikku scopes prune\` to remove them deliberately.
 */
export const SCOPES: FlatScope[] = [
${listEntries.join('\n')}
]
`
}
