import type { ScopeDefinitions } from '@pikku/core/scope'
import { flattenScopeDefinitions } from '@pikku/core/scope'

export interface SerializeScopesOptions {
  definitions: ScopeDefinitions
}

const quote = (value: string) => `'${value.replace(/'/g, "\\'")}'`

/**
 * Generates the `ScopeId` union and scope metadata from `wireScope`
 * declarations.
 *
 * The union carries every declared node plus a wildcard form for each node that
 * has descendants — `admin:*` is requirable when `admin` has children, but a
 * leaf's wildcard would grant nothing beyond the leaf itself, so it is omitted.
 * The bare `*` is never emitted: it is a valid grant but never a sensible
 * requirement.
 */
export const serializeScopesTypes = ({
  definitions,
}: SerializeScopesOptions) => {
  const flat = flattenScopeDefinitions(definitions)
  const ids = flat.map((s) => s.id)

  const hasChildren = (id: string) =>
    ids.some((other) => other.startsWith(`${id}:`))

  const requirable = [
    ...ids,
    ...ids.filter(hasChildren).map((id) => `${id}:*`),
  ].sort()

  const union =
    requirable.length > 0
      ? `\n${requirable.map((id) => `  | ${quote(id)}`).join('\n')}`
      : ' never'

  const displayNames = [...flat]
    .sort((a, b) => a.id.localeCompare(b.id))
    .flatMap((scope) => {
      const displayName = definitions.find(
        (d) => d.name === scope.id
      )?.displayName
      return displayName ? [`  ${quote(scope.id)}: ${quote(displayName)},`] : []
    })

  return `/**
 * This file was generated by the @pikku/cli
 */
import type { FlatScope, ScopeDefinitionsMeta } from '@pikku/core/scope'
import { flattenScopeDefinitions } from '@pikku/core/scope'
import definitions from './pikku-scopes-meta.gen.json' with { type: 'json' }

/**
 * Every scope a function can require.
 *
 * A \`:*\` entry requires the scope and all of its descendants. Held grants are
 * matched against this by \`verifyScopes\` — \`admin:*\` on a session satisfies
 * any \`admin:...\` requirement.
 */
export type ScopeId =${union}

export interface ScopeMeta {
  id: ScopeId
  displayName?: string
  description?: string
}

/**
 * The declared scope set, for a ScopeService to sync into its store.
 *
 * Derived from the metadata sidecar rather than inlined, so that the import
 * above forces tsc to emit the .json alongside this file. An addon publishes
 * only its compiled output, and a host reads that .json to merge the addon's
 * scopes into its own \`ScopeId\` union and declared set — an uncopied sidecar
 * would leave the addon's scopes ungrantable.
 *
 * Additive: removing a declaration leaves an inert row rather than revoking a
 * grant mid-deploy. Use \`pikku scopes prune\` to remove them deliberately.
 */
export const SCOPES: FlatScope[] = flattenScopeDefinitions(
  Object.values(definitions as ScopeDefinitionsMeta)
)

const DISPLAY_NAMES: Record<string, string> = {
${displayNames.join('\n')}
}

/** Declared scopes, keyed by id. Rendered by the console when granting. */
export const SCOPES_META: Record<string, ScopeMeta> = Object.fromEntries(
  SCOPES.map((scope) => [
    scope.id,
    {
      id: scope.id as ScopeId,
      ...(DISPLAY_NAMES[scope.id]
        ? { displayName: DISPLAY_NAMES[scope.id] }
        : {}),
      ...(scope.description ? { description: scope.description } : {}),
    },
  ])
)
`
}
