import { SERVER_READY_MARKER } from '@pikku/deploy'

import { DATA_DIR_ENV, PARENT_PID_ENV } from '../runtime/parent-watch.js'
import type { NativeApi } from './native.js'

type WindowOptions = {
  windowTitle: string
  width: number
  height: number
}

export type MainRsOptions = WindowOptions &
  (
    | {
        /** The `externalBin` base name — how `shell().sidecar(..)` finds the binary. */
        sidecarName: string
        remoteUrl?: undefined
      }
    | {
        /** An already-running server the window opens against. */
        remoteUrl: string
        sidecarName?: undefined
      }
  ) & {
    /** Native APIs to initialise. Only the remote shell can carry them. */
    native?: readonly NativeApi[]
  }

/**
 * `main.rs`, which on mobile is never called at all.
 *
 * Android loads the crate as a `cdylib` through JNI and iOS links it as a
 * `staticlib`; neither runs a `main`. So the program lives in `lib.rs` behind
 * `run()`, and this file is the desktop binary's one-line entry point. The
 * split is invisible on desktop and is the whole reason a mobile build is
 * possible at all.
 */
export const renderMainRs = (crateName: string): string => {
  const libName = `${crateName.replace(/-/g, '_')}_lib`
  return `// Generated by \`pikku deploy apply --desktop\`. Safe to edit — the generator
// will not overwrite this file once you have changed it.
//
// The program is in lib.rs: a mobile build never calls \`main\`, so everything
// has to be reachable from \`run()\` instead.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    ${libName}::run()
}
`
}

/**
 * The shell's whole program.
 *
 * Everything it does follows from one decision: the server serves the UI and
 * the API from a single real HTTP origin, and the webview simply points at it.
 * A `tauri://localhost` webview would break every cookie, CORS check and OAuth
 * redirect keyed on `window.location.origin`, which is the trap this design
 * exists to avoid. On mobile that trap is deeper — the webview origin there is
 * `http://tauri.localhost` or `tauri://localhost` and an OAuth redirect has
 * nowhere to land — so a remote origin is what makes a mobile build viable.
 *
 * Which origin it is decides the program. A sidecar binds its port at startup,
 * so the shell has to start it, read the port off its ready line and open the
 * window itself. A remote url is known before a line of Rust is generated, so
 * the window is declared in `tauri.conf.json` and nothing here runs beyond
 * initialising plugins.
 */
export const renderLibRs = (options: MainRsOptions): string =>
  options.remoteUrl === undefined
    ? renderSidecarLibRs(options)
    : renderRemoteLibRs(options.native ?? [])

/**
 * `.plugin()` lines for the chosen native APIs.
 *
 * A mobile-only plugin's crate does not exist for a desktop target, so its
 * initialiser has to be gated to match the dependency gating in Cargo.toml —
 * ungated, it is a build failure on the platform the shell started life on.
 */
const renderNativePlugins = (native: readonly NativeApi[]): string =>
  native
    .map((api) => {
      const init = `    let builder = builder.plugin(${api.module}::init());`
      return api.support === 'mobile'
        ? `\n    #[cfg(mobile)]\n${init}`
        : `\n${init}`
    })
    .join('')

const renderRemoteLibRs = (native: readonly NativeApi[]): string =>
  `// Generated by \`pikku deploy apply --desktop\`. Safe to edit — the generator
// will not overwrite this file once you have changed it.
//
// The window is declared in tauri.conf.json, pointed straight at the remote
// server: its origin is known up front, so there is no port to discover and no
// process to supervise. The webview loads that origin rather than
// \`tauri://localhost\`, which is what keeps cookies first-party and OAuth
// redirects working — on mobile as much as on desktop.

/// Mobile has no \`main\`: Android loads this crate through JNI and iOS links it
/// as a static library, and the attribute generates the entry point each one
/// looks for. On desktop it expands to nothing and \`main.rs\` calls this.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default();

    // Two windows would mean two sessions against the same server, so a second
    // launch should reach the one already open. There is no second launch to
    // catch on mobile, where the OS owns the app lifecycle and the plugin does
    // not build.
    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
        use tauri::Manager;
        if let Some(window) = app.get_webview_window("main") {
            let _ = window.unminimize();
            let _ = window.show();
            let _ = window.set_focus();
        }
    }));
${renderNativePlugins(native)}
    builder
        .run(tauri::generate_context!())
        .expect("error while running the pikku desktop shell");
}
`

const renderSidecarLibRs = (
  options: WindowOptions & { sidecarName: string }
): string => {
  const { sidecarName, windowTitle, width, height } = options
  return `// Generated by \`pikku deploy apply --desktop\`. Safe to edit — the generator
// will not overwrite this file once you have changed it.
//
// The webview points at the sidecar's own HTTP origin rather than at
// \`tauri://localhost\`, so cookies are first-party, there is no CORS, and OAuth
// redirects land where the server expects. The sidecar is the application; this
// shell only supervises it.

// A sidecar shell is a desktop program by construction, and saying so here is
// the difference between an answer and a linker error: \`bun build --compile\`
// emits no iOS or Android binary to ship, and iOS does not permit spawning a
// bundled executable even if it did.
#[cfg(mobile)]
compile_error!(
    "This shell runs a bundled pikku server as a sidecar, which iOS and Android do not permit. Regenerate with --desktop-url <url> to point a mobile build at a deployed server instead."
);

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};
use tauri_plugin_shell::process::{CommandChild, CommandEvent};
use tauri_plugin_shell::ShellExt;

/// Printed by the sidecar once it is listening *and* its startup lifecycle has
/// finished. The runtime's own "listening on ..." line comes earlier and is not
/// readiness.
const READY_PREFIX: &str = "${SERVER_READY_MARKER} on http://";

/// How long to wait for the ready line before giving up. A sidecar that starts
/// and then hangs prints nothing, so no window is ever built — and a Tauri
/// process with no window cannot be quit from the dock or the taskbar.
const READY_TIMEOUT: Duration = Duration::from_secs(30);

/// Held so the child is not dropped while the app runs, and so a clean exit can
/// stop it explicitly.
struct Sidecar(Mutex<Option<CommandChild>>);

fn parse_ready_port(line: &str) -> Option<u16> {
    let rest = line.split(READY_PREFIX).nth(1)?;
    let authority = rest.split_whitespace().next()?;
    authority
        .trim_end_matches('/')
        .rsplit(':')
        .next()?
        .parse()
        .ok()
}

pub fn run() {
    tauri::Builder::default()
        // A second launch must never spawn a second sidecar: that would be two
        // SQLite writers on one file. Focus what is already running instead.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.unminimize();
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir)?;

            let (mut rx, child) = app
                .shell()
                .sidecar("${sidecarName}")?
                // Port 0 asks the OS for a free port. Choosing one here and
                // passing it down would race whatever binds it in between, so
                // the sidecar binds first and reports back on its ready line.
                .env("PORT", "0")
                .env("HOST", "127.0.0.1")
                // The database, uploaded content and runtime state live here
                // and nowhere else. A double-clicked app has no meaningful
                // working directory, so the platform's app-data path is the
                // only sane answer — the server reads this in bootstrap.
                .env("${DATA_DIR_ENV}", data_dir.to_string_lossy().to_string())
                // Tauri stops the sidecar on a clean exit, but a hard crash of
                // this process never runs that path, and an orphan would hold
                // the database open with its data key still resident.
                .env("${PARENT_PID_ENV}", std::process::id().to_string())
                .spawn()?;

            app.manage(Sidecar(Mutex::new(Some(child))));

            let opened = Arc::new(AtomicBool::new(false));

            let timeout_handle = app.handle().clone();
            let timeout_opened = opened.clone();
            std::thread::spawn(move || {
                std::thread::sleep(READY_TIMEOUT);
                if !timeout_opened.load(Ordering::SeqCst) {
                    eprintln!(
                        "the pikku sidecar did not become ready within {:?} — giving up",
                        READY_TIMEOUT
                    );
                    timeout_handle.exit(1);
                }
            });

            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                while let Some(event) = rx.recv().await {
                    let line = match event {
                        CommandEvent::Stdout(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
                        CommandEvent::Stderr(bytes) => {
                            eprint!("{}", String::from_utf8_lossy(&bytes));
                            continue;
                        }
                        CommandEvent::Terminated(payload) => {
                            eprintln!("pikku sidecar exited: {:?}", payload.code);
                            if !opened.load(Ordering::SeqCst) {
                                handle.exit(1);
                            }
                            break;
                        }
                        _ => continue,
                    };
                    print!("{}", line);

                    if opened.load(Ordering::SeqCst) {
                        continue;
                    }
                    if let Some(port) = parse_ready_port(&line) {
                        let url = format!("http://127.0.0.1:{}", port);
                        match url.parse() {
                            Ok(parsed) => {
                                let built = WebviewWindowBuilder::new(
                                    &handle,
                                    "main",
                                    WebviewUrl::External(parsed),
                                )
                                .title("${windowTitle}")
                                .inner_size(${width}.0, ${height}.0)
                                .build();
                                match built {
                                    Ok(_) => opened.store(true, Ordering::SeqCst),
                                    Err(err) => {
                                        eprintln!("could not open the window: {}", err);
                                        handle.exit(1);
                                    }
                                }
                            }
                            Err(err) => {
                                eprintln!("the sidecar reported an unusable url: {}", err);
                                handle.exit(1);
                            }
                        }
                    }
                }
            });

            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::Destroyed = event {
                if let Some(sidecar) = window.app_handle().try_state::<Sidecar>() {
                    if let Ok(mut guard) = sidecar.0.lock() {
                        if let Some(child) = guard.take() {
                            let _ = child.kill();
                        }
                    }
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running the pikku desktop shell");
}
`
}
