import { SERVER_READY_MARKER } from '@pikku/deploy'

import { DATA_DIR_ENV, PARENT_PID_ENV } from '../runtime/parent-watch.js'
import type { NativeApi } from './native.js'

/** The `externalBin` base name the compiled server is installed under. */
export const SIDECAR_NAME = 'pikku-server'

export type LibRsOptions = {
  /** Whether the window's UI comes from a bundled pikku server. */
  bundleServer: boolean
}

/** The library target's name — what `main.rs` calls `run()` on. */
export const libName = (crateName: string): string =>
  `${crateName.replace(/-/g, '_')}_lib`

const USER_OWNED = `// Written once by \`pikku app native init\` — this file is yours to edit, and
// pikku will not touch it again. The plugins in \`frontends.<name>.native\` are
// initialised in pikku.rs, which pikku rewrites; keep the \`pikku::plugins\` call.`

/**
 * `main.rs`, which on mobile is never called at all.
 *
 * Android loads the crate as a `cdylib` through JNI and iOS links it as a
 * `staticlib`; neither runs a `main`. So the program lives in `lib.rs` behind
 * `run()`, and this file is the desktop binary's one-line entry point. The
 * split is invisible on desktop and is the whole reason a mobile build is
 * possible at all.
 */
export const renderMainRs = (crateName: string): string =>
  `${USER_OWNED}
//
// The program is in lib.rs: a mobile build never calls \`main\`, so everything
// has to be reachable from \`run()\` instead.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    ${libName(crateName)}::run()
}
`

/**
 * `pikku.rs` — the one Rust file pikku keeps rewriting.
 *
 * Adding a plugin a month after `init` has to initialise it, and `lib.rs` is the
 * user's by then. So every initialiser pikku manages lives here, behind one
 * function `lib.rs` calls once, and nothing the user wrote is ever regenerated.
 *
 * A mobile-only plugin's crate does not exist for a desktop target, so its
 * initialiser is gated to match the dependency gating in Cargo.toml — ungated,
 * it is a build failure on every desktop build of the same crate.
 */
export const renderPikkuRs = (options: {
  plugins: readonly NativeApi[]
  bundleServer: boolean
}): string => {
  const lines = [
    ...(options.bundleServer
      ? ['    let builder = builder.plugin(tauri_plugin_shell::init());']
      : []),
    ...options.plugins.flatMap((api) => {
      const init = `    let builder = builder.plugin(${api.init});`
      return api.support === 'mobile' ? ['    #[cfg(mobile)]', init] : [init]
    }),
  ]
  return `//! Generated by pikku, and rewritten by \`pikku app native add\` and \`upgrade\`.
//! Edits here are lost: initialise your own plugins in lib.rs.

/// Every plugin in this app's \`native.plugins\`, initialised.
pub fn plugins<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::Builder<R> {
${lines.map((line) => `${line}\n`).join('')}    builder
}
`
}

/**
 * The app's program, written once.
 *
 * A bundled or remote UI is known before a line of Rust runs, so the window is
 * declared in \`tauri.conf.json\` and this only initialises plugins. A bundled
 * server binds its port at startup, so the shell has to start it, read the port
 * off its ready line and open the window itself.
 */
export const renderLibRs = (options: LibRsOptions): string =>
  options.bundleServer ? renderSidecarLibRs() : renderStaticLibRs()

const SINGLE_INSTANCE = `plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
        use tauri::Manager;
        if let Some(window) = app.get_webview_window("main") {
            let _ = window.unminimize();
            let _ = window.show();
            let _ = window.set_focus();
        }
    }))`

const renderStaticLibRs = (): string =>
  `${USER_OWNED}

mod pikku;

/// Mobile has no \`main\`: Android loads this crate through JNI and iOS links it
/// as a static library, and the attribute generates the entry point each one
/// looks for. On desktop it expands to nothing and \`main.rs\` calls this.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default();

    // A second launch should reach the window already open. There is no second
    // launch to catch on mobile, where the OS owns the app lifecycle and the
    // plugin does not build.
    #[cfg(desktop)]
    let builder = builder.${SINGLE_INSTANCE};

    pikku::plugins(builder)
        .run(tauri::generate_context!())
        .expect("error while running the app");
}
`

const renderSidecarLibRs = (): string =>
  `${USER_OWNED}
//
// The webview points at the sidecar's own HTTP origin rather than at
// \`tauri://localhost\`, so cookies are first-party, there is no CORS, and OAuth
// redirects land where the server expects. The sidecar is the application; this
// shell only supervises it.

// A sidecar shell is a desktop program by construction, and saying so here is
// the difference between an answer and a linker error: \`bun build --compile\`
// emits no iOS or Android binary to ship, and iOS does not permit spawning a
// bundled executable even if it did.
#[cfg(mobile)]
compile_error!(
    "This app runs a bundled pikku server as a sidecar, which iOS and Android do not permit. Drop native.bundleServer from the frontend's config to bundle only the UI, or set native.url to open a deployed server."
);

mod pikku;

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};
use tauri_plugin_shell::process::{CommandChild, CommandEvent};
use tauri_plugin_shell::ShellExt;

/// Printed by the sidecar once it is listening *and* its startup lifecycle has
/// finished. The runtime's own "listening on ..." line comes earlier and is not
/// readiness.
const READY_PREFIX: &str = "${SERVER_READY_MARKER} on http://";

/// Title of the window the ready line opens — the app's own name, once you set it.
const WINDOW_TITLE: &str = "pikku";

/// How long to wait for the ready line before giving up. A sidecar that starts
/// and then hangs prints nothing, so no window is ever built — and a Tauri
/// process with no window cannot be quit from the dock or the taskbar.
const READY_TIMEOUT: Duration = Duration::from_secs(30);

/// Held so the child is not dropped while the app runs, and so a clean exit can
/// stop it explicitly.
struct Sidecar(Mutex<Option<CommandChild>>);

fn parse_ready_port(line: &str) -> Option<u16> {
    let rest = line.split(READY_PREFIX).nth(1)?;
    let authority = rest.split_whitespace().next()?;
    authority
        .trim_end_matches('/')
        .rsplit(':')
        .next()?
        .parse()
        .ok()
}

pub fn run() {
    // A second launch must never spawn a second sidecar: that would be two
    // SQLite writers on one file. Focus what is already running instead.
    let builder = tauri::Builder::default();
    let builder = builder.${SINGLE_INSTANCE};

    pikku::plugins(builder)
        .setup(|app| {
            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir)?;

            let (mut rx, child) = app
                .shell()
                .sidecar("${SIDECAR_NAME}")?
                // Port 0 asks the OS for a free port. Choosing one here and
                // passing it down would race whatever binds it in between, so
                // the sidecar binds first and reports back on its ready line.
                .env("PORT", "0")
                .env("HOST", "127.0.0.1")
                // The database, uploaded content and runtime state live here
                // and nowhere else. A double-clicked app has no meaningful
                // working directory, so the platform's app-data path is the
                // only sane answer — the server reads this in bootstrap.
                .env("${DATA_DIR_ENV}", data_dir.to_string_lossy().to_string())
                // Tauri stops the sidecar on a clean exit, but a hard crash of
                // this process never runs that path, and an orphan would hold
                // the database open with its data key still resident.
                .env("${PARENT_PID_ENV}", std::process::id().to_string())
                .spawn()?;

            app.manage(Sidecar(Mutex::new(Some(child))));

            let opened = Arc::new(AtomicBool::new(false));

            let timeout_handle = app.handle().clone();
            let timeout_opened = opened.clone();
            std::thread::spawn(move || {
                std::thread::sleep(READY_TIMEOUT);
                if !timeout_opened.load(Ordering::SeqCst) {
                    eprintln!(
                        "the pikku sidecar did not become ready within {:?} — giving up",
                        READY_TIMEOUT
                    );
                    timeout_handle.exit(1);
                }
            });

            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                while let Some(event) = rx.recv().await {
                    let line = match event {
                        CommandEvent::Stdout(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
                        CommandEvent::Stderr(bytes) => {
                            eprint!("{}", String::from_utf8_lossy(&bytes));
                            continue;
                        }
                        CommandEvent::Terminated(payload) => {
                            eprintln!("pikku sidecar exited: {:?}", payload.code);
                            if !opened.load(Ordering::SeqCst) {
                                handle.exit(1);
                            }
                            break;
                        }
                        _ => continue,
                    };
                    print!("{}", line);

                    if opened.load(Ordering::SeqCst) {
                        continue;
                    }
                    if let Some(port) = parse_ready_port(&line) {
                        let url = format!("http://127.0.0.1:{}", port);
                        match url.parse() {
                            Ok(parsed) => {
                                let built = WebviewWindowBuilder::new(
                                    &handle,
                                    "main",
                                    WebviewUrl::External(parsed),
                                )
                                .title(WINDOW_TITLE)
                                .inner_size(1200.0, 800.0)
                                .build();
                                match built {
                                    Ok(_) => opened.store(true, Ordering::SeqCst),
                                    Err(err) => {
                                        eprintln!("could not open the window: {}", err);
                                        handle.exit(1);
                                    }
                                }
                            }
                            Err(err) => {
                                eprintln!("the sidecar reported an unusable url: {}", err);
                                handle.exit(1);
                            }
                        }
                    }
                }
            });

            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::Destroyed = event {
                if let Some(sidecar) = window.app_handle().try_state::<Sidecar>() {
                    if let Ok(mut guard) = sidecar.0.lock() {
                        if let Some(child) = guard.take() {
                            let _ = child.kill();
                        }
                    }
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running the app");
}
`
