/**
 * This file was generated by the @pikku/cli
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */

// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string }
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L12C3Output =
  { type: string; text: string }[]
export type DisableToolInput = { name: string }
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L25C3Output =
  { type: string; text: string }[]
export type CalculateInput = {
  operation: 'add' | 'subtract' | 'multiply' | 'divide'
  a: number
  b: number
}
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L52C4Output =
  { type: string; text: string }[]
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L88C55Output =
  { uri: any; text: string }[]
export type GetUserInfoInput = { userId: string }
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L101C3Output =
  { uri: string; text: string }[]
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L140C66Output =
  { role: string; content: { type: string; text: string } }[]
export type DynamicPromptGeneratorInput = {
  topic: string
  complexity: 'beginner' | 'intermediate' | 'advanced'
  includeExamples?: string
}
export type PikkuFn__Users_yasser_git_pikku_pikku_templates_functions_src_mcp_functions_ts_L159C4Output =
  { role: 'user'; content: { type: 'text'; text: string } }[]
export type OnConnectInput = 'hello!'
export type AuthenticateInput = { token: string; userId: string }
export type AuthenticateOutput = { authResult: boolean; action: 'auth' }
export type SubscribeInput = { name: string }
export type UnsubscribeInput = { name: string }
export type EmitMessageInput = { name: string }
export type EmitMessageOutput =
  | { timestamp: string; from: string }
  | { message: string }
export type OnMessageInput = 'hello'
export type OnMessageOutput = 'hey'
export type ProgressiveEnhancementExampleOutput = {
  state: 'initial' | 'pending' | 'done'
}
export type TimeSinceOpenedOutput = { count: number }
export type QueueWorkerInput = { message: string; fail: boolean }
export type QueueWorkerOutput = { result: string }
export type RpcTestInput = { in: number }

interface ChannelHandler<I, O> {
  input: I
  output: O
}

export type ChannelsMap = {
  readonly events: {
    readonly routes: {
      readonly action: {
        readonly auth: ChannelHandler<AuthenticateInput, AuthenticateOutput>
        readonly subscribe: ChannelHandler<SubscribeInput, never>
        readonly unsubscribe: ChannelHandler<UnsubscribeInput, never>
        readonly emit: ChannelHandler<EmitMessageInput, EmitMessageOutput>
      }
    }
    readonly defaultMessage: never
  }
  readonly 'progressive-enhancement': {
    readonly routes: {
      readonly action: {
        readonly status: ChannelHandler<
          void,
          ProgressiveEnhancementExampleOutput
        >
      }
    }
    readonly defaultMessage: never
  }
}

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
  ChannelsMap[Channel]['defaultMessage'] extends {
    input: infer I
    output: infer O
  }
    ? ChannelHandler<I, O>
    : never

export type ChannelRouteHandlerOf<
  Channel extends keyof ChannelsMap,
  Route extends keyof ChannelsMap[Channel]['routes'],
  Method extends keyof ChannelsMap[Channel]['routes'][Route],
> = ChannelsMap[Channel]['routes'][Route][Method] extends {
  input: infer I
  output: infer O
}
  ? ChannelHandler<I, O>
  : never
