/**
 * This file was generated by the @pikku/cli
 */
import { addSchema } from '@pikku/core/schema'

import * as OnConnectInput from './schemas/OnConnectInput.schema.json'
addSchema('OnConnectInput', OnConnectInput)

import * as AuthenticateInput from './schemas/AuthenticateInput.schema.json'
addSchema('AuthenticateInput', AuthenticateInput)

import * as AuthenticateOutput from './schemas/AuthenticateOutput.schema.json'
addSchema('AuthenticateOutput', AuthenticateOutput)

import * as SubscribeInput from './schemas/SubscribeInput.schema.json'
addSchema('SubscribeInput', SubscribeInput)

import * as UnsubscribeInput from './schemas/UnsubscribeInput.schema.json'
addSchema('UnsubscribeInput', UnsubscribeInput)

import * as EmitMessageInput from './schemas/EmitMessageInput.schema.json'
addSchema('EmitMessageInput', EmitMessageInput)

import * as EmitMessageOutput from './schemas/EmitMessageOutput.schema.json'
addSchema('EmitMessageOutput', EmitMessageOutput)

import * as OnMessageInput from './schemas/OnMessageInput.schema.json'
addSchema('OnMessageInput', OnMessageInput)

import * as OnMessageOutput from './schemas/OnMessageOutput.schema.json'
addSchema('OnMessageOutput', OnMessageOutput)

import * as ProgressiveEnhancementExampleOutput from './schemas/ProgressiveEnhancementExampleOutput.schema.json'
addSchema(
  'ProgressiveEnhancementExampleOutput',
  ProgressiveEnhancementExampleOutput
)

import * as TimeSinceOpenedOutput from './schemas/TimeSinceOpenedOutput.schema.json'
addSchema('TimeSinceOpenedOutput', TimeSinceOpenedOutput)

import * as QueueProcessorInput from './schemas/QueueProcessorInput.schema.json'
addSchema('QueueProcessorInput', QueueProcessorInput)

import * as QueueProcessorOutput from './schemas/QueueProcessorOutput.schema.json'
addSchema('QueueProcessorOutput', QueueProcessorOutput)

import * as RpcTestInput from './schemas/RpcTestInput.schema.json'
addSchema('RpcTestInput', RpcTestInput)
