/**
 * This file was generated by the @pikku/cli
 */
import { addSchema } from '@pikku/core/schema'

import * as ProgressiveEnhancementExampleOutput from './schemas/ProgressiveEnhancementExampleOutput.schema.json' 
addSchema('ProgressiveEnhancementExampleOutput', ProgressiveEnhancementExampleOutput)


import * as TimeSinceOpenedOutput from './schemas/TimeSinceOpenedOutput.schema.json' 
addSchema('TimeSinceOpenedOutput', TimeSinceOpenedOutput)
