/**
 * This file was generated by @pikku/cli@0.12.8
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */

import type { StreamWorkflowRunInput } from '../../../addon/pikku-console/dist/.pikku/rpc/pikku-rpc-wirings-map.internal.gen.d.js'

export type PikkuConsoleGetSecretInput = { secretId: string }
export type PikkuConsoleGetSecretOutput = { exists: boolean; value: unknown }
export type PikkuConsoleGetVariableInput = { variableId: string }
export type PikkuConsoleGetVariableOutput = { exists: boolean; value: unknown }
export type PikkuConsoleHasSecretInput = { secretId: string }
export type PikkuConsoleHasSecretOutput = { exists: boolean }
export type PikkuConsoleSetSecretInput = { secretId: string; value: unknown }
export type PikkuConsoleSetSecretOutput = { success: boolean }
export type PikkuConsoleSetVariableInput = {
  variableId: string
  value: unknown
}
export type PikkuConsoleSetVariableOutput = { success: boolean }
export type PikkuRemoteInternalRPCInput = { rpcName: string; data?: any }
export type PikkuWorkflowOrchestratorInput = { runId: string }
export type PikkuWorkflowSleeperInput = { runId: string; stepId: string }
export type RpcCallerInput = { rpcName: string; data?: unknown }
export type WorkflowCallerInput = { workflowName: string; input?: unknown }
export type WorkflowCallerOutput = { runId: string }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type StreamWorkflowRunInputParams = Pick<
  StreamWorkflowRunInput,
  'runId'
> & {}
export type StreamWorkflowRunInputBody = Omit<
  StreamWorkflowRunInput,
  'runId'
> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type WorkflowCallerInputParams = Pick<
  WorkflowCallerInput,
  'workflowName'
> & {}
export type WorkflowCallerInputBody = Omit<
  WorkflowCallerInput,
  'workflowName'
> & {}

interface HTTPWiringHandler<I, O> {
  input: I
  output: O
}

export type HTTPWiringsMap = {
  readonly '/workflow-run/:runId/stream': {
    readonly GET: HTTPWiringHandler<StreamWorkflowRunInput, null>
  }
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>
  }
  readonly '/rpc/workflow/:workflowName': {
    readonly POST: HTTPWiringHandler<WorkflowCallerInput, WorkflowCallerOutput>
  }
}

export type HTTPWiringHandlerOf<
  HTTPWiring extends keyof HTTPWiringsMap,
  Method extends keyof HTTPWiringsMap[HTTPWiring],
> = HTTPWiringsMap[HTTPWiring][Method] extends {
  input: infer I
  output: infer O
}
  ? HTTPWiringHandler<I, O>
  : never

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring]
    ? HTTPWiring
    : never
}[keyof HTTPWiringsMap]
