/**
 * This file was generated by @pikku/cli@0.12.2
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */

import type { StreamWorkflowRunInput } from '../../../addon/pikku-console/.pikku/rpc/pikku-rpc-wirings-map.internal.gen.d.js'

export type HttpOptionsApiWorkflowRunRunIdStreamInput = { runId: string }
export type RpcCallerInput = { rpcName: string; data?: unknown }
export type WorkflowCallerInput = { workflowName: string; input?: unknown }
export type WorkflowCallerOutput = { runId: string }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type HttpOptionsApiWorkflowRunRunIdStreamInputParams = Pick<
  HttpOptionsApiWorkflowRunRunIdStreamInput,
  'runId'
> & {}
export type HttpOptionsApiWorkflowRunRunIdStreamInputBody = Omit<
  HttpOptionsApiWorkflowRunRunIdStreamInput,
  'runId'
> & {}
export type StreamWorkflowRunInputParams = Pick<
  StreamWorkflowRunInput,
  'runId'
> & {}
export type StreamWorkflowRunInputBody = Omit<
  StreamWorkflowRunInput,
  'runId'
> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type WorkflowCallerInputParams = Pick<
  WorkflowCallerInput,
  'workflowName'
> & {}
export type WorkflowCallerInputBody = Omit<
  WorkflowCallerInput,
  'workflowName'
> & {}

interface HTTPWiringHandler<I, O> {
  input: I
  output: O
}

export type HTTPWiringsMap = {
  readonly '/api/workflow-run/:runId/stream': {
    readonly GET: HTTPWiringHandler<StreamWorkflowRunInput, null>
    readonly OPTIONS: HTTPWiringHandler<
      HttpOptionsApiWorkflowRunRunIdStreamInput,
      unknown
    >
  }
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>
  }
  readonly '/rpc/workflow/:workflowName': {
    readonly POST: HTTPWiringHandler<WorkflowCallerInput, WorkflowCallerOutput>
  }
}

export type HTTPWiringHandlerOf<
  HTTPWiring extends keyof HTTPWiringsMap,
  Method extends keyof HTTPWiringsMap[HTTPWiring],
> = HTTPWiringsMap[HTTPWiring][Method] extends {
  input: infer I
  output: infer O
}
  ? HTTPWiringHandler<I, O>
  : never

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring]
    ? HTTPWiring
    : never
}[keyof HTTPWiringsMap]
