/**
 * This file was generated by @pikku/cli@0.12.0
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */

import type {
  SetSecretInput,
  SetSecretOutput,
  GetVariableInput,
  GetVariableOutput,
  SetVariableInput,
  SetVariableOutput,
  GetSecretInput,
  GetSecretOutput,
  StartWorkflowRunInput,
  StartWorkflowRunOutput,
} from '../../backend/src/functions/pikku.console.gen.js'

export type HttpOptionsApiWorkflowRunRunIdStreamInput = { runId: string }

interface RPCHandler<I, O> {
  input: I
  output: O
}

export type RPCMap = {
  readonly setSecret: RPCHandler<SetSecretInput, SetSecretOutput>
  readonly getVariable: RPCHandler<GetVariableInput, GetVariableOutput>
  readonly setVariable: RPCHandler<SetVariableInput, SetVariableOutput>
  readonly getSecret: RPCHandler<GetSecretInput, GetSecretOutput>
  readonly startWorkflowRun: RPCHandler<
    StartWorkflowRunInput,
    StartWorkflowRunOutput
  >
}

// External package RPC maps
import type { RPCMap as ConsoleRPCMap } from '@pikku/addon-console/.pikku/rpc/pikku-rpc-wirings-map.internal.gen.js'

// Utility type to prefix keys with namespace
type PrefixKeys<T, Prefix extends string> = {
  [K in keyof T as `${Prefix}:${string & K}`]: T[K]
}

// Merge all RPC maps with namespace prefixes
export type FlattenedRPCMap = RPCMap & PrefixKeys<ConsoleRPCMap, 'console'>

export type RPCInvoke = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input']
) => Promise<FlattenedRPCMap[Name]['output']>

export type RPCRemote = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input']
) => Promise<FlattenedRPCMap[Name]['output']>

import type { WorkflowMap } from '../../backend/.pikku/workflow/pikku-workflow-map.gen.d.js'

import type { AgentMap } from '../../backend/.pikku/agent/pikku-agent-map.gen.d.js'

// External package Agent maps
import type { AgentMap as ConsoleAgentMap } from '@pikku/addon-console/.pikku/agent/pikku-agent-map.gen.d.js'

type FlattenedAgentMap = AgentMap & PrefixKeys<ConsoleAgentMap, 'console'>

import type { PikkuRPC } from '@pikku/core/rpc'

interface AIAgentInput {
  message: string
  threadId: string
  resourceId: string
}

export type TypedStartWorkflow = <Name extends keyof WorkflowMap>(
  name: Name,
  input: WorkflowMap[Name]['input'],
  options?: { startNode?: string }
) => Promise<{ runId: string }>

export type TypedAgentRun = <Name extends keyof FlattenedAgentMap>(
  name: Name,
  input: AIAgentInput
) => Promise<{
  runId: string
  result: FlattenedAgentMap[Name]['output']
  usage: { inputTokens: number; outputTokens: number }
}>

export type TypedPikkuRPC = PikkuRPC<
  RPCInvoke,
  RPCRemote,
  TypedStartWorkflow,
  TypedAgentRun
>
