/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', [
  {
    pikkuFuncName: 'pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3',
    route: '/status/sse',
    method: 'get',
  },
  {
    pikkuFuncName: 'pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3',
    route: '/status/http',
    method: 'get',
  },
  {
    pikkuFuncName: 'pikkuFn_src_http_sse_functions_ts_L6C3',
    route: '/sse',
    method: 'get',
  },
  {
    pikkuFuncName: 'pikkuFn_src_http_functions_ts_L3C54',
    route: '/hello-world',
    method: 'get',
    tags: ['hello'],
  },
  {
    pikkuFuncName: 'pikkuFn_src_rpc_functions_ts_L15C47',
    route: '/rpc',
    method: 'get',
  },
  {
    pikkuFuncName: 'pikkuFn_src_rpc_functions_ts_L4C3',
    route: '/dummy',
    method: 'get',
  },
])
