/**
 * This file was generated by @pikku/cli@0.10.0
 */
/**
 * Auto-generated workflow queue workers
 *
 * This file contains:
 * - RPC step workers (one per RPC form step)
 * - Orchestrator workers (one per workflow)
 *
 * Do not edit manually - regenerate with 'npx pikku prebuild'
 */

import { pikkuSessionlessFunc } from '../../.pikku/pikku-types.gen.js'
import { wireQueueWorker } from '@pikku/core/queue'
import { runWorkflowJob } from '@pikku/core/workflow'

// Orchestrator for: User onboarding workflow with email and profile setup
export const OnboardingOrchestratorWorker = pikkuSessionlessFunc({
  name: 'OnboardingOrchestratorWorker',
  func: async (services, payload: any) => {
    const { runId } = payload

    try {
      // Run workflow job (replays with caching)
      await runWorkflowJob(runId, services)
    } catch (error: any) {
      // WorkflowAsyncException is not an error - it means we scheduled a step
      if (error.name === 'WorkflowAsyncException') {
        // Workflow paused waiting for step completion
        return
      }

      // Real error - mark workflow as failed
      await services.workflowState!.updateRunStatus(
        runId,
        'failed',
        undefined,
        {
          message: error.message,
          stack: error.stack,
          code: error.code,
        }
      )

      throw error
    }
  },
})

wireQueueWorker({
  queueName: 'workflow-onboarding-orchestrator',
  func: OnboardingOrchestratorWorker as any,
})
