import { test, describe } from 'node:test'
import * as assert from 'assert'
import ts from 'typescript'
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * `#pikku` is the app tier's only door onto Pikku, and it is a namespace rather
 * than a module: `#pikku/http`, `#pikku/workflow`, one subpath per wiring.
 *
 * The bare specifier used to resolve to `.pikku/pikku-types.gen.ts`, which
 * re-exported all twelve wiring leaves with `export *` — undoing the split the
 * leaves exist for, each of which still says so in its own header ("HTTP-specific
 * type definitions for tree-shaking optimization"). Reaching that barrel put 33
 * distinct `@pikku/core` subpaths into the module graph, and neither of the two
 * consumers could drop them again: bundlers keep `export *` chains because the
 * app declares no `sideEffects`, and Node and tsx do not tree-shake at all, so
 * an app with no queues still executed `@pikku/core/queue` at boot.
 *
 * Deleting the barrel also turns the addon boundary from advice into a rule. An
 * addon's leaves are never generated, so `#pikku/http` fails to resolve at the
 * specifier rather than yielding "no exported member" from a hub that quietly
 * dropped the re-export.
 */
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../../..')

/**
 * Membership is discovered, not listed: every directory holding a
 * `pikku.config.json` is a Pikku project, so a project added later arrives
 * guarded rather than invisible. Listing them by hand is how an earlier
 * version of this guard reported green on four packages it had never scanned.
 */
const skipped = new Set([
  'node_modules',
  'dist',
  '.pikku',
  '.next',
  'build',
  '.git',
  'coverage',
  // Agent scratch worktrees are whole Pikku projects generated by whatever CLI
  // version happened to scaffold them, so discovery finds them and reports a
  // barrel this repo does not own. They are gitignored and belong to no
  // workspace, which is what makes them out of scope rather than merely noisy.
  '.claude',
])

const findProjects = (dir: string, out: string[] = []): string[] => {
  for (const entry of readdirSync(dir)) {
    if (skipped.has(entry)) continue
    const path = join(dir, entry)
    if (!statSync(path).isDirectory()) continue
    if (existsSync(join(path, 'pikku.config.json'))) out.push(path)
    findProjects(path, out)
  }
  return out
}

const walk = (dir: string, out: string[] = []): string[] => {
  for (const entry of readdirSync(dir)) {
    if (skipped.has(entry)) continue
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) walk(path, out)
    else if (path.endsWith('.ts') || path.endsWith('.tsx')) out.push(path)
  }
  return out
}

/**
 * `.gen.*` and `.d.ts` are the generator's own output — what they import is
 * decided by the codegen templates, and `.pikku` is skipped outright.
 */
const isGenerated = (path: string) =>
  path.includes('.gen.') || path.endsWith('.d.ts')

const projectSourceFiles = (project: string) => {
  const files: string[] = []
  for (const entry of readdirSync(project)) {
    if (skipped.has(entry)) continue
    const path = join(project, entry)
    if (!statSync(path).isDirectory()) continue
    if (existsSync(join(path, 'pikku.config.json'))) continue
    walk(path, files)
  }
  return files.filter((file) => !isGenerated(file))
}

/**
 * Parsed rather than grepped: the CLI's serializers hold the specifiers they
 * emit inside template literals, and those are output text rather than imports
 * the CLI itself makes.
 */
const barrelSpecifiers = (file: string) => {
  const source = ts.createSourceFile(
    file,
    readFileSync(file, 'utf8'),
    ts.ScriptTarget.Latest,
    true
  )
  const found: { specifier: string; line: number }[] = []
  for (const statement of source.statements) {
    if (
      !ts.isImportDeclaration(statement) &&
      !ts.isExportDeclaration(statement)
    ) {
      continue
    }
    const moduleSpecifier = statement.moduleSpecifier
    if (!moduleSpecifier || !ts.isStringLiteral(moduleSpecifier)) continue
    const specifier = moduleSpecifier.text
    const isBarrel =
      specifier === '#pikku' ||
      /^#pikku\/pikku-types\.gen(\.js)?$/.test(specifier)
    if (!isBarrel) continue
    const { line } = source.getLineAndCharacterOfPosition(
      statement.getStart(source)
    )
    found.push({ specifier, line: line + 1 })
  }
  return found
}

/**
 * Names a leaf carries, mapped to the leaf that carries them. An app reaching
 * `@pikku/core` for one of these is the smell that says the generator is not
 * emitting something it should — the definer is already generated into the
 * project's own `.pikku`, so naming core instead couples the app to a package
 * it otherwise never imports.
 */
const namesOwnedByALeaf = new Map<string, string>([
  ['defineCredential', '#pikku/auth'],
  ['defineSecret', '#pikku/secrets'],
  ['defineVariable', '#pikku/variables'],
  ['defineScope', '#pikku/scopes'],
  ['defineSystemRole', '#pikku/scopes'],
  ['cors', '#pikku/middleware'],
  ['InvalidOriginError', '#pikku/error'],
])

const coreNamesThatHaveALeaf = (file: string) => {
  const source = ts.createSourceFile(
    file,
    readFileSync(file, 'utf8'),
    ts.ScriptTarget.Latest,
    true
  )
  const found: { name: string; leaf: string; line: number }[] = []
  for (const statement of source.statements) {
    if (!ts.isImportDeclaration(statement)) continue
    const moduleSpecifier = statement.moduleSpecifier
    if (!ts.isStringLiteral(moduleSpecifier)) continue
    if (!/^@pikku\/core(\/|$)/.test(moduleSpecifier.text)) continue

    const bindings = statement.importClause?.namedBindings
    if (!bindings || !ts.isNamedImports(bindings)) continue
    for (const element of bindings.elements) {
      const name = (element.propertyName ?? element.name).text
      const leaf = namesOwnedByALeaf.get(name)
      if (!leaf) continue
      const { line } = source.getLineAndCharacterOfPosition(
        element.getStart(source)
      )
      found.push({ name, leaf, line: line + 1 })
    }
  }
  return found
}

describe('app leaf surface', () => {
  test('no Pikku project reaches past a leaf for a name the leaf carries', () => {
    const projects = findProjects(repoRoot)
    assert.ok(projects.length > 0, 'expected to discover Pikku projects')

    // A project nested inside another (an addon under `e2e/packages`) is
    // discovered on its own account and again as its parent's source, so the
    // same offence is reached twice.
    const offenders = new Set<string>()
    for (const project of projects) {
      for (const file of projectSourceFiles(project)) {
        for (const { name, leaf, line } of coreNamesThatHaveALeaf(file)) {
          offenders.add(
            `${relative(repoRoot, file)}:${line}  ${name} — import it from '${leaf}'`
          )
        }
      }
    }

    assert.deepStrictEqual(
      [...offenders].sort(),
      [],
      `An app developer imports from '#pikku/<leaf>'. Reaching past it to ` +
        `'@pikku/core' for a name the leaf already carries is the smell that ` +
        `says the generator is not emitting something it should.\n\n` +
        [...offenders].sort().join('\n')
    )
  })

  test('no Pikku project reaches the app tier through a barrel', () => {
    const projects = findProjects(repoRoot)
    assert.ok(projects.length > 0, 'expected to discover Pikku projects')

    const offenders: string[] = []
    for (const project of projects) {
      for (const file of projectSourceFiles(project)) {
        for (const { specifier, line } of barrelSpecifiers(file)) {
          offenders.push(`${relative(repoRoot, file)}:${line}  ${specifier}`)
        }
      }
    }

    assert.deepStrictEqual(
      offenders,
      [],
      `The app tier reaches Pikku through one subpath per wiring — ` +
        `'#pikku/http', '#pikku/workflow', '#pikku/function'.\n` +
        `A barrel import pulls every wiring's core dependencies into the ` +
        `module graph, and nothing downstream can drop them again.\n\n` +
        offenders.join('\n')
    )
  })
})
