import { test, describe } from 'node:test'
import * as assert from 'assert'
import ts from 'typescript'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * The package root was one barrel of 206 names that no bundler could take
 * apart, and the one specifier that revealed nothing about what a consumer
 * actually used.
 *
 * It is gone. Every name lives on the subpath that owns it, and every import
 * carries that subpath. What survives is a bootstrap shim, which the second
 * test here holds to its exact contents.
 */
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../../..')

const skipDirectory = new Set([
  'node_modules',
  'dist',
  '.git',
  'build',
  'coverage',
  // Agent scratch worktrees are whole Pikku projects scaffolded by whatever CLI
  // version happened to write them, so they carry specifiers this repo does not
  // own. They are gitignored and belong to no workspace, which is what puts them
  // out of scope rather than merely making them noisy.
  '.claude',
])

/** A verifier's scratch project, left behind by a run that did not clean up. */
const isScratchProject = (entry: string) => entry.startsWith('.tmp-')

const walk = (dir: string, out: string[] = []): string[] => {
  for (const entry of readdirSync(dir)) {
    if (skipDirectory.has(entry) || isScratchProject(entry)) continue
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) walk(path, out)
    else if (path.endsWith('.ts') || path.endsWith('.tsx')) out.push(path)
  }
  return out
}

/**
 * Generated output belongs to whichever CLI wrote it — including the pinned
 * published one that bootstraps `packages/cli` and still emits the old
 * specifiers. What this branch's serializers emit is covered by the CLI's own
 * tests, against the template rather than its output.
 */
const isGenerated = (path: string) =>
  path.includes('.gen.') || path.endsWith('.d.ts') || path.includes('/.pikku/')

describe('no root barrel', () => {
  /**
   * Parsed rather than grepped: several tests hold a user's file as a template
   * literal, and `import { pikkuSessionlessFunc } from '@pikku/core'` inside
   * one is fixture text for the inspector, not an import this repo makes.
   */
  test('nothing imports the package root', () => {
    const offenders: string[] = []

    for (const file of walk(repoRoot)) {
      if (isGenerated(file)) continue
      const source = ts.createSourceFile(
        file,
        readFileSync(file, 'utf8'),
        ts.ScriptTarget.Latest,
        true
      )
      for (const statement of source.statements) {
        if (
          !ts.isImportDeclaration(statement) &&
          !ts.isExportDeclaration(statement)
        ) {
          continue
        }
        const specifier = statement.moduleSpecifier
        if (!specifier || !ts.isStringLiteral(specifier)) continue
        if (specifier.text !== '@pikku/core') continue
        const { line } = source.getLineAndCharacterOfPosition(
          statement.getStart(source)
        )
        offenders.push(`${relative(repoRoot, file)}:${line + 1}`)
      }
    }

    assert.deepStrictEqual(
      offenders,
      [],
      `The '@pikku/core' root is a bootstrap shim, not an entry point. Every ` +
        `import carries the subpath that owns the name — '@pikku/core/types' ` +
        `for the shared types, '@pikku/core/services' for the services.\n\n` +
        offenders.join('\n')
    )
  })

  /**
   * The shim exists because `packages/cli` is generated by the published CLI
   * pinned in its `build.sh`, which still writes these specifiers. Holding it
   * to an exact list is what keeps it a shim: a name can only be added here by
   * someone who has read why it should not be.
   */
  test('the bootstrap shim carries only what the pinned CLI emits', () => {
    const surface = (file: string) =>
      readFileSync(join(dirname(fileURLToPath(import.meta.url)), file), 'utf8')
        .replace(/\/\*\*[\s\S]*?\*\//g, '')
        .match(/\b[A-Za-z][A-Za-z0-9]*\b(?=[,\n\s]*(?:,|\}))/g)
        ?.sort() ?? []

    assert.deepStrictEqual(surface('bootstrap-compat/root.ts'), [
      'CorePermissionGroup',
      'CorePikkuMiddleware',
      'ListInput',
      'ListOutput',
      'PickRequired',
      'PikkuWire',
      'SecretService',
      'SecretlessServices',
    ])
  })
})
