#:schema node_modules/wrangler/config-schema.json
name = "functions-mcp-server"
main = "bundle.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[[services]]
binding = "CREATE_TODO"
service = "functions-create-todo"

[[services]]
binding = "DELETE_TODO"
service = "functions-delete-todo"

[[services]]
binding = "COMPLETE_TODO"
service = "functions-complete-todo"

[[services]]
binding = "CREATE_TODO_TOOL"
service = "functions-create-todo-tool"

[[services]]
binding = "GET_TODO_RESOURCE"
service = "functions-get-todo-resource"

[[services]]
binding = "PLAN_DAY_PROMPT"
service = "functions-plan-day-prompt"

[[services]]
binding = "PRIORITIZE_PROMPT"
service = "functions-prioritize-prompt"
