/**
 * Main esbuild bundling pipeline for Pikku.
 *
 * For each deployment unit in a DeploymentManifest, this module:
 * 1. Takes a pre-generated entry point (provided by the deploy provider)
 * 2. Runs esbuild with bundle:true, platform:browser, packages:external
 * 3. Parses the metafile to extract external dependencies
 * 4. Generates a minimal package.json with exact versions
 * 5. Writes all artifacts to `<outputDir>/<unit-name>/`
 */

import { build } from 'esbuild'
import { writeFile, mkdir, stat } from 'node:fs/promises'
import { join } from 'node:path'

import {
  extractDependencies,
  generateMinimalPackageJson,
} from './dep-extractor.js'
import type {
  DeploymentManifest,
  DeploymentUnit,
  BundleResult,
  BundleError,
  BundleOutput,
} from './types.js'

const BUNDLE_FILENAME = 'bundle.js'
const METAFILE_FILENAME = 'metafile.json'
const PACKAGE_JSON_FILENAME = 'package.json'

interface BundleUnitOptions {
  unit: DeploymentUnit
  entryPath: string
  unitOutputDir: string
  projectDir: string
}

/**
 * Bundles a single deployment unit using esbuild.
 *
 * Produces three files in the unit output directory:
 * - bundle.js: The bundled code (user code only, external deps as bare imports)
 * - metafile.json: esbuild's metafile for analysis
 * - package.json: Minimal manifest with only the external deps this unit needs
 */
async function bundleUnit(options: BundleUnitOptions): Promise<BundleResult> {
  const { unit, entryPath, unitOutputDir, projectDir } = options

  await mkdir(unitOutputDir, { recursive: true })

  const bundlePath = join(unitOutputDir, BUNDLE_FILENAME)
  const metafilePath = join(unitOutputDir, METAFILE_FILENAME)
  const packageJsonPath = join(unitOutputDir, PACKAGE_JSON_FILENAME)

  // Run esbuild
  const result = await build({
    entryPoints: [entryPath],
    bundle: true,
    platform: 'browser',
    format: 'esm',
    packages: 'external',
    metafile: true,
    target: 'es2022',
    outfile: bundlePath,
    minify: false,
    sourcemap: false,
    logLevel: 'warning',
    // Ensure we handle TypeScript entry points
    loader: { '.ts': 'ts' },
  })

  // Write metafile
  const metafileJson = JSON.stringify(result.metafile, null, 2)
  await writeFile(metafilePath, metafileJson, 'utf-8')

  // Extract dependencies and generate minimal package.json
  const dependencies = await extractDependencies(result.metafile, projectDir)
  const packageJson = generateMinimalPackageJson(unit.name, dependencies)
  await writeFile(
    packageJsonPath,
    JSON.stringify(packageJson, null, 2),
    'utf-8'
  )

  // Get bundle size
  const bundleStat = await stat(bundlePath)

  return {
    unitName: unit.name,
    bundlePath,
    packageJsonPath,
    metafilePath,
    bundleSizeBytes: bundleStat.size,
    externalPackages: dependencies,
  }
}

/**
 * Bundles all deployment units defined in a DeploymentManifest.
 *
 * Entry points must be pre-generated by the provider-specific package
 * (e.g. @pikku/deploy-cloudflare) and passed in as entryFiles.
 *
 * @param projectDir - Root directory of the Pikku project
 * @param manifest - The deployment manifest describing all units
 * @param entryFiles - Map of unit name -> entry file path (generated by the deploy provider)
 * @param outputDir - Base output directory (defaults to `<projectDir>/.deploy/build`)
 */
export async function bundleUnits(
  projectDir: string,
  manifest: DeploymentManifest,
  entryFiles: Map<string, string>,
  outputDir?: string
): Promise<BundleOutput> {
  const buildDir = outputDir ?? join(projectDir, '.deploy', 'build')
  const results: BundleResult[] = []
  const errors: BundleError[] = []

  if (manifest.units.length === 0) {
    return { results, errors }
  }

  for (const unit of manifest.units) {
    const entryPath = entryFiles.get(unit.name)
    if (!entryPath) {
      errors.push({
        unitName: unit.name,
        error: `No entry point provided for unit "${unit.name}"`,
      })
      continue
    }

    const unitOutputDir = join(buildDir, unit.name)

    try {
      const result = await bundleUnit({
        unit,
        entryPath,
        unitOutputDir,
        projectDir,
      })
      results.push(result)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      errors.push({
        unitName: unit.name,
        error: message,
      })
    }
  }

  return { results, errors }
}
