import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseCva } from '../src/cva.js'
import type { Block, ComponentEntry } from '../src/types.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'src/registry.gen.ts')
const SHARED = new Set(['react', 'react-dom'])

const read = (path: string) => readFileSync(path, 'utf8')

const packageName = (specifier: string) =>
  specifier.startsWith('@') ? specifier.split('/').slice(0, 2).join('/') : specifier.split('/')[0]!

function imports(source: string): string[] {
  return [...source.matchAll(/from\s+['"]([^'"]+)['"]/g)].map((m) => m[1]!)
}

const components: ComponentEntry[] = []
const uiDir = join(ROOT, 'ui')
for (const file of readdirSync(uiDir).sort()) {
  if (!file.endsWith('.tsx') || file.includes('.stories.')) continue
  const name = file.slice(0, -'.tsx'.length)
  const source = read(join(uiDir, file))
  const files: Record<string, string> = { [`components/ui/${file}`]: source }
  const stories = `${name}.stories.tsx`
  let group: string | undefined
  let description: string | undefined
  if (existsSync(join(uiDir, stories))) {
    const storySource = read(join(uiDir, stories))
    files[`components/ui/${stories}`] = storySource
    group = storySource.match(/group:\s*'([^']+)'/)?.[1]
    description = storySource.match(/description:\s*'([^']+)'/)?.[1]
  }
  const specifiers = imports(source)
  const cva = parseCva(source)
  components.push({
    name,
    ...(group ? { group } : {}),
    ...(description ? { description } : {}),
    variants: cva?.variants ?? {},
    defaultVariants: cva?.defaultVariants ?? {},
    npmDeps: [
      ...new Set(
        specifiers
          .filter((s) => !s.startsWith('.') && !s.startsWith('@/'))
          .map(packageName)
          .filter((p) => !SHARED.has(p))
      ),
    ].sort(),
    registryDeps: [...new Set(specifiers.filter((s) => s.startsWith('./')).map((s) => s.slice(2)))].sort(),
    files,
  })
}

const blocks: Block[] = []
const blocksDir = join(ROOT, 'blocks')
for (const dir of readdirSync(blocksDir).sort()) {
  const metaPath = join(blocksDir, dir, 'meta.json')
  if (!existsSync(metaPath)) continue
  const meta = JSON.parse(read(metaPath)) as Partial<Block> & { name: string; title: string; description: string }
  const source: Record<string, string> = {}
  for (const file of readdirSync(join(blocksDir, dir)).sort()) {
    if (file !== 'meta.json') source[file] = read(join(blocksDir, dir, file))
  }
  const used = new Set<string>()
  for (const content of Object.values(source)) {
    for (const specifier of imports(content)) {
      const match = specifier.match(/^@\/components\/ui\/(.+)$/)
      if (match) used.add(match[1]!)
    }
  }
  blocks.push({
    name: meta.name,
    title: meta.title,
    description: meta.description,
    tags: meta.tags ?? [],
    dependsOn: meta.dependsOn ?? [],
    components: [...used].sort(),
    npmDeps: meta.npmDeps ?? [],
    internal: meta.internal ?? false,
    i18nKeys: meta.i18nKeys ?? {},
    ...(meta.usage ? { usage: meta.usage } : {}),
    source,
  })
}

const banner = [
  '// Generated by scripts/generate-registry.ts from ui/ and blocks/ — do not edit by hand.',
  "import type { Block, ComponentEntry } from './types.js'",
  '',
].join('\n')

writeFileSync(
  OUT,
  `${banner}\nexport const COMPONENTS: ComponentEntry[] = ${JSON.stringify(components, null, 2)}\n\nexport const BLOCKS: Block[] = ${JSON.stringify(blocks, null, 2)}\n`
)
console.log(`wrote ${OUT}: ${components.length} components, ${blocks.length} blocks`)
