/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  onConnect: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L9C3',
    exposed: false,
  },
  onDisconnect: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L18C3',
    exposed: false,
  },
  authenticate: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L28C3',
    exposed: false,
  },
  subscribe: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L37C3',
    exposed: false,
  },
  unsubscribe: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L43C3',
    exposed: false,
  },
  emitMessage: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L51C3',
    exposed: false,
  },
  onMessage: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L60C3',
    exposed: false,
  },
  progressiveEnhancementExample: {
    pikkuFuncName: 'pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3',
    exposed: false,
  },
  timeSinceOpened: {
    pikkuFuncName: 'pikkuFn_src_http_sse_functions_ts_L6C3',
    exposed: false,
  },
  helloWorld: {
    pikkuFuncName: 'pikkuFn_src_http_functions_ts_L3C54',
    exposed: false,
  },
  sayHello: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L12C3',
    exposed: false,
  },
  disableTool: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L25C3',
    exposed: false,
  },
  calculate: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L52C4',
    exposed: false,
  },
  getStaticResource: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L88C55',
    exposed: false,
  },
  getUserInfo: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L101C3',
    exposed: false,
  },
  staticPromptGenerator: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L140C66',
    exposed: false,
  },
  dynamicPromptGenerator: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L159C4',
    exposed: false,
  },
  queueWorker: {
    pikkuFuncName: 'pikkuFn_src_queue_worker_functions_ts_L6C3',
    exposed: false,
  },
  rpcTest: {
    pikkuFuncName: 'pikkuFn_src_rpc_functions_ts_L4C3',
    exposed: false,
  },
  rpcCaller: {
    pikkuFuncName: 'pikkuFn_src_rpc_functions_ts_L15C80',
    exposed: false,
  },
  myScheduledTask: {
    pikkuFuncName: 'pikkuFn_src_scheduled_task_functions_ts_L4C3',
    exposed: false,
  },
})
