/**
 * This file was generated by @pikku/cli@0.10.0
 */
/**
 * WebSocket channel backend for 'my-cli' CLI commands
 */
import {
  wireChannel,
  pikkuChannelMiddleware,
} from '../.pikku/channel/pikku-channel-types.gen.js'
import { greetUser } from '../../functions/src/cli.functions.js'
import { addNumbers } from '../../functions/src/cli.functions.js'
import { subtractNumbers } from '../../functions/src/cli.functions.js'
import { multiplyNumbers } from '../../functions/src/cli.functions.js'
import { divideNumbers } from '../../functions/src/cli.functions.js'
import { createUser } from '../../functions/src/cli.functions.js'
import { listUsers } from '../../functions/src/cli.functions.js'
import { processFile } from '../../functions/src/cli.functions.js'

// Middleware to close the channel after each CLI command completes
const closeAfterCommand = pikkuChannelMiddleware(async ({ channel }, next) => {
  try {
    await next()
  } finally {
    // Close the channel after the command completes
    channel.close()
  }
})

wireChannel({
  name: 'cli',
  route: '/cli',
  auth: false,
  middleware: [closeAfterCommand],
  onMessageWiring: {
    command: {
      greet: greetUser,
      'calc.add': addNumbers,
      'calc.subtract': subtractNumbers,
      'calc.multiply': multiplyNumbers,
      'calc.divide': divideNumbers,
      'user.create': createUser,
      'user.list': listUsers,
      file: processFile,
    },
  },
  tags: ['cli', 'my-cli'],
})
