/**
 * This file was generated by @pikku/cli@0.10.0
 */
/**
 * WebSocket channel backend for 'my-cli' CLI commands
 */
import { wireChannel } from '../.pikku/channel/pikku-channel-types.gen.js'
import { greetUser } from '../../functions/src/cli.functions.js'
import { addNumbers } from '../../functions/src/cli.functions.js'
import { subtractNumbers } from '../../functions/src/cli.functions.js'
import { multiplyNumbers } from '../../functions/src/cli.functions.js'
import { divideNumbers } from '../../functions/src/cli.functions.js'
import { createUser } from '../../functions/src/cli.functions.js'
import { listUsers } from '../../functions/src/cli.functions.js'
import { processFile } from '../../functions/src/cli.functions.js'

wireChannel({
  name: 'cli',
  route: '/cli',
  auth: false,
  onMessageWiring: {
    command: {
      greet: greetUser,
      'calc.add': addNumbers,
      'calc.subtract': subtractNumbers,
      'calc.multiply': multiplyNumbers,
      'calc.divide': divideNumbers,
      'user.create': createUser,
      'user.list': listUsers,
      file: processFile,
    },
  },
  tags: ['cli', 'my-cli'],
})
