/**
 * Generates type definitions for CLI wirings
 */
export const serializeCLITypes = (
  functionTypesImportPath: string,
  userSessionTypeImport: string,
  userSessionTypeName: string,
  singletonServicesTypeImport: string,
  singletonServicesTypeName: string
) => {
  return `/**
 * This file was generated by the @pikku/cli
 * CLI-specific type definitions for tree-shaking optimization
 */

import { CoreCLI, wireCLI as wireCLICore, CorePikkuCLIRender, CoreCLICommandConfig } from '@pikku/core'
import type { PikkuFunctionConfig, PikkuMiddleware } from '${functionTypesImportPath}'
${userSessionTypeImport}
${singletonServicesTypeImport}

${singletonServicesTypeName !== 'SingletonServices' ? `type SingletonServices = ${singletonServicesTypeName}` : ''}
${userSessionTypeName !== 'Session' ? `type Session = ${userSessionTypeName}` : ''}

/**
 * Type-safe CLI renderer definition that can access your application's services.
 * Use this to define custom renderers for CLI command output.
 *
 * @template Data - The output data type from the CLI command
 * @template RequiredServices - The services required for this renderer
 */
type PikkuCLIRender<Data, RequiredServices extends SingletonServices = SingletonServices> = CorePikkuCLIRender<Data, RequiredServices, Session>

/**
 * CLI command configuration with project-specific types.
 * Uses CoreCLICommandConfig from @pikku/core with local middleware and render types.
 */
type CLICommandConfig<Func extends PikkuFunctionConfig<In, Out>, In = any, Out = any, Params extends string = string> = CoreCLICommandConfig<Func, PikkuMiddleware, PikkuCLIRender<any>, Params>

/**
 * Result type for CLI command configuration
 */
type CLICommandResult<Func extends PikkuFunctionConfig<In, Out>, In = any, Out = any, Params extends string = string> = CoreCLICommandConfig<Func, PikkuMiddleware, PikkuCLIRender<any>, Params>

/**
 * Type definition for CLI applications with commands and global options.
 *
 * @template Commands - Type describing the command structure
 * @template GlobalOptions - Type for global CLI options
 */
type CLIWiring<Commands extends Record<string, CoreCLICommandConfig<any, PikkuMiddleware, PikkuCLIRender<any>, any>>, GlobalOptions> = CoreCLI<Commands, GlobalOptions, PikkuMiddleware, PikkuCLIRender<any>>

/**
 * Registers a CLI application with the Pikku framework.
 * Creates command-line interfaces with type-safe commands and options.
 *
 * @template Commands - Type describing the command structure
 * @template GlobalOptions - Type for global CLI options
 * @param cli - CLI definition with program name, commands, and global options
 */
export const wireCLI = <Commands extends Record<string, CoreCLICommandConfig<any, PikkuMiddleware, PikkuCLIRender<any>, any>>, GlobalOptions>(
  cli: CLIWiring<Commands, GlobalOptions>
) => {
  wireCLICore(cli as any)
}

/**
 * Creates a CLI command definition with automatic option inference from the function's input type.
 * This allows TypeScript to automatically derive CLI options from the function signature.
 *
 * @template FuncConfig - The Pikku function config type
 * @template Params - The parameters string literal type
 * @param config - CLI command configuration
 * @returns CLI command configuration with inferred types
 */
export const pikkuCLICommand = <
  FuncConfig extends PikkuFunctionConfig<any, any>,
  Params extends string
>(
  config: CLICommandConfig<FuncConfig, any, any, Params>
): CoreCLICommandConfig<FuncConfig, PikkuMiddleware, PikkuCLIRender<any>, string> => {
  return config as any
}
`
}
