#!/usr/bin/env node
// Generates src/skills.gen.ts — every file under skills/ as a path -> contents map.
//
// Why embed markdown into a TypeScript module at all: the `bun build --compile`
// native CLI binaries only contain the JS import graph, so 80-odd files reached
// through `readdir` are invisible to the bundler. Before this manifest existed,
// `pikku skills install` threw "Could not locate bundled skills directory" on
// every Homebrew/binary install — the skills shipped to npm but not to the
// binary most people run. Importing the manifest makes the bundler carry it.
//
// Every file under skills/ is text (enforced by the test suite), so the map is a
// lossless representation and callers never need a second code path for content.
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, dirname, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const skillsRoot = join(root, 'skills')

/** Every file under skills/, as POSIX-relative paths, sorted for a stable diff. */
function collect(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) collect(full, out)
    else if (entry.isFile())
      out.push(relative(skillsRoot, full).split(sep).join('/'))
  }
  return out
}

if (!statSync(skillsRoot, { throwIfNoEntry: false })?.isDirectory()) {
  throw new Error(`No skills directory at ${skillsRoot}`)
}

const files = collect(skillsRoot)
const manifest = Object.fromEntries(
  files.map((rel) => [rel, readFileSync(join(skillsRoot, rel), 'utf-8')])
)

const out = `// Generated by scripts/embed.mjs — do not edit.
// Run \`yarn embed\` in @pikku/skills after changing anything under skills/.
//
// Maps each file under skills/ to its contents, so the skill set survives
// bundling into the \`bun --compile\` CLI binaries, where there is no filesystem
// copy to read. See scripts/embed.mjs for why.

export const SKILL_FILES: Record<string, string> = ${JSON.stringify(manifest, null, 0)}
`

writeFileSync(join(root, 'src', 'skills.gen.ts'), out)

const bytes = Buffer.byteLength(out)
console.log(
  `Embedded ${files.length} files from ${new Set(files.map((f) => f.split('/')[0])).size} skills (${(bytes / 1024).toFixed(0)} KB)`
)
