#!/usr/bin/env bun
// Generates src/skills.gen.ts — every file under skills/ as a path -> contents
// map, with `snippet:<region>` fences replaced by the region's compiled code.
//
// Why embed markdown into a TypeScript module at all: the `bun build --compile`
// native CLI binaries only contain the JS import graph, so 80-odd files reached
// through `readdir` are invisible to the bundler. Before this manifest existed,
// `pikku skills install` threw "Could not locate bundled skills directory" on
// every Homebrew/binary install — the skills shipped to npm but not to the
// binary most people run. Importing the manifest makes the bundler carry it.
//
// Snippets come from the same `@snippet` regions the website's code blocks use,
// in compiled example projects. A region renamed or removed fails this script;
// a region whose code stops compiling fails the example's own build. That is
// what makes the code in a skill a typed, tested thing rather than prose.
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, dirname, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { collectSnippets, expandSkillMarkdown } from '../src/snippets.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const skillsRoot = join(root, 'skills')

/** Compiled projects whose @snippet regions skills may reference. */
const SNIPPET_SOURCES = [join(root, '..', '..', 'examples', 'online-shop')]

/** Every file under skills/, as POSIX-relative paths, sorted for a stable diff. */
function collect(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) collect(full, out)
    else if (entry.isFile())
      out.push(relative(skillsRoot, full).split(sep).join('/'))
  }
  return out
}

if (!statSync(skillsRoot, { throwIfNoEntry: false })?.isDirectory()) {
  throw new Error(`No skills directory at ${skillsRoot}`)
}

const snippets = new Map()
for (const source of SNIPPET_SOURCES) {
  if (!statSync(source, { throwIfNoEntry: false })?.isDirectory()) {
    throw new Error(`No snippet source at ${source}`)
  }
  await collectSnippets(source, snippets)
}

const files = collect(skillsRoot)
const manifest = Object.fromEntries(
  files.map((rel) => {
    const raw = readFileSync(join(skillsRoot, rel), 'utf-8')
    return [
      rel,
      rel.endsWith('.md') ? expandSkillMarkdown(raw, snippets, rel) : raw,
    ]
  })
)

const snippetMap = Object.fromEntries(
  [...snippets.entries()].sort(([a], [b]) => a.localeCompare(b))
)

const out = `// Generated by scripts/embed.ts — do not edit.
// Run \`bun run embed\` in @pikku/skills after changing anything under skills/.
//
// Maps each file under skills/ to its contents, so the skill set survives
// bundling into the \`bun --compile\` CLI binaries, where there is no filesystem
// copy to read. Snippet fences are expanded here, and SKILL_SNIPPETS lets a
// filesystem read expand them the same way. See scripts/embed.ts for why.

export const SKILL_FILES: Record<string, string> = ${JSON.stringify(manifest, null, 0)}

export const SKILL_SNIPPETS: Record<string, string> = ${JSON.stringify(snippetMap, null, 0)}
`

writeFileSync(join(root, 'src', 'skills.gen.ts'), out)

const bytes = Buffer.byteLength(out)
console.log(
  `Embedded ${files.length} files from ${new Set(files.map((f) => f.split('/')[0])).size} skills (${(bytes / 1024).toFixed(0)} KB, ${snippets.size} snippets)`
)
