/**
 * Embed a built frontend into a `bun build --compile` binary.
 *
 * Bun embeds a file imported with `with { type: 'file' }` and hands back an
 * opaque `/$bunfs/…` path at runtime. That attribute cannot be applied to a
 * dynamic import, and there is no way to embed a directory, so each file needs
 * its own literal `import` statement — hence a generated module rather than a
 * walk at startup.
 *
 * esbuild rejects the attribute outright ("Importing with a type attribute of
 * \"file\" is not supported"), so this module is kept out of the esbuild bundle
 * as an external and is resolved by the later `bun build --compile` step, which
 * follows the import from the emitted `bundle.js`.
 *
 * The manifest can only name files that already exist, which fixes the build
 * order: frontend build → manifest generation → server bundle → compile.
 */

import { cp, readdir, rm, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

export const FRONTEND_ASSET_MANIFEST_FILE = 'frontend-assets.gen.js'

/** Directory name the built frontend is copied to inside a deploy unit. */
export const FRONTEND_DIR_NAME = 'frontend'

export interface FrontendAsset {
  /** Mount-relative request path, POSIX-separated (`assets/app-a1b2c3.js`). */
  key: string
  /** Absolute path of the built file. */
  path: string
}

const toPosix = (value: string): string => value.replace(/\\/g, '/')

/**
 * Every file under `dir`, keyed by its path relative to it.
 *
 * Sorted by key: directory read order is not stable across filesystems, and the
 * manifest feeds a build whose output should not change run to run.
 */
export async function collectFrontendAssets(
  dir: string
): Promise<FrontendAsset[]> {
  const assets: FrontendAsset[] = []

  const walk = async (current: string): Promise<void> => {
    const entries = await readdir(current, { withFileTypes: true })
    for (const entry of entries) {
      const absolute = join(current, entry.name)
      if (entry.isDirectory()) {
        await walk(absolute)
      } else if (entry.isFile()) {
        assets.push({ key: toPosix(relative(dir, absolute)), path: absolute })
      }
    }
  }

  await walk(dir)
  return assets.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))
}

/**
 * The manifest module source, with specifiers relative to `manifestDir` — the
 * directory the file itself is written to.
 */
export function generateFrontendAssetManifest(
  assets: FrontendAsset[],
  manifestDir: string
): string {
  const lines: string[] = ['// Generated by @pikku/cli — do not edit']

  assets.forEach((asset, index) => {
    const specifier = toPosix(relative(manifestDir, asset.path))
    lines.push(
      `import asset${index} from './${specifier}' with { type: 'file' }`
    )
  })

  lines.push('', 'export const frontendAssets = {')
  assets.forEach((asset, index) => {
    lines.push(`  '${asset.key}': asset${index},`)
  })
  lines.push('}', '')

  return lines.join('\n')
}

/**
 * Copy a built frontend into a deploy unit and write the manifest beside it.
 *
 * The copy comes first and the manifest is generated from the copy, not the
 * source: the unit directory is what the bundle and the compile step see, and
 * the machine that compiles has no reason to still hold the frontend's build
 * tree. A stale copy is removed rather than merged into, so a file dropped
 * from the frontend's output cannot survive into the next binary.
 *
 * Returns the keys that were embedded, in manifest order.
 */
export async function materializeFrontend(
  frontendDir: string,
  unitDir: string
): Promise<string[]> {
  const target = join(unitDir, FRONTEND_DIR_NAME)
  await rm(target, { recursive: true, force: true })
  await cp(frontendDir, target, { recursive: true })

  const assets = await collectFrontendAssets(target)
  await writeFile(
    join(unitDir, FRONTEND_ASSET_MANIFEST_FILE),
    generateFrontendAssetManifest(assets, unitDir),
    'utf-8'
  )

  return assets.map((asset) => asset.key)
}
