/**
 * Provider-agnostic Node server entry generator for `target: 'server'` units.
 *
 * Produces a `node:http`-based HTTP entry built on `@pikku/node-http-server`
 * — the same runtime `pikku dev` uses. Containers sit behind something
 * (Cloudflare Workers, a load balancer) so raw uWS throughput isn't
 * required; sharing the dev server keeps one HTTP path to maintain.
 *
 * The same bundle runs anywhere a Node process can run: CF Containers,
 * fly.io, ECS, bare VM. Provider-specific config (Dockerfile, infra) is
 * emitted by the provider adapter on top of this entry + bundle.js.
 */

import type { EntryGenerationContext } from './provider-adapter.js'

export function generateServerEntrySource(ctx: EntryGenerationContext): string {
  const lines: string[] = [
    `// Generated server entry for "${ctx.unit.name}" (${ctx.unit.role})`,
    `import { PikkuNodeHTTPServer } from '@pikku/node-http-server'`,
    `import { pikkuState } from '@pikku/core/internal'`,
    ctx.configImport,
    ctx.servicesImport,
    `import '${ctx.bootstrapPath}'`,
    ``,
    `const PORT = Number(process.env.PORT ?? 4003)`,
    `const HOST = process.env.HOST ?? '0.0.0.0'`,
    ``,
    `async function main(): Promise<void> {`,
    `  const config = await ${ctx.configVar}()`,
    `  const singletonServices = await ${ctx.servicesVar}(config)`,
    `  pikkuState(null, 'package', 'singletonServices', singletonServices)`,
    ``,
    `  const server = new PikkuNodeHTTPServer(`,
    `    { ...config, hostname: HOST, port: PORT, healthCheckPath: '/__pikku/health' },`,
    `    singletonServices.logger`,
    `  )`,
    `  server.enableExitOnSignals()`,
    `  await server.init()`,
    `  await server.start()`,
    `}`,
    ``,
    `main().catch((err) => {`,
    `  console.error('pikku-server: fatal', err)`,
    `  process.exit(1)`,
    `})`,
    ``,
  ]
  return lines.join('\n')
}

export const SERVER_DOCKERFILE = `# Generated by @pikku/cli — do not edit
FROM node:22-slim

RUN apt-get update \\
  && apt-get install -y --no-install-recommends tini ca-certificates \\
  && rm -rf /var/lib/apt/lists/*

RUN groupadd -r pikku && useradd -r -g pikku -u 1001 pikku

WORKDIR /app

COPY --chown=pikku:pikku package.json ./
RUN npm ci --omit=dev --no-audit --no-fund || npm install --omit=dev --no-audit --no-fund

COPY --chown=pikku:pikku bundle.js ./
COPY --chown=pikku:pikku bundle.js.map ./

USER pikku
ENV NODE_ENV=production
ENV PORT=4003
EXPOSE 4003

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["node", "bundle.js"]
`

export const SERVER_DOCKERIGNORE = `node_modules
.git
*.log
metafile.json
exact-dependencies.json
`
