/**
 * Provider-agnostic Node server entry generator for `target: 'server'` units.
 *
 * Produces a `Bun.serve`-based HTTP entry built on `@pikku/bun-server`.
 *
 * The same bundle runs anywhere a Bun process can run: CF Containers,
 * fly.io, ECS, bare VM. Provider-specific config (Dockerfile, infra) is
 * emitted by the provider adapter on top of this entry + bundle.js.
 */

import type { EntryGenerationContext } from '@pikku/deploy'

export function generateServerEntrySource(ctx: EntryGenerationContext): string {
  const lines: string[] = [
    `// Generated server entry for "${ctx.unit.name}" (${ctx.unit.role})`,
    `import { PikkuBunServer } from '@pikku/bun-server'`,
    `import { pikkuState } from '@pikku/core/state'`,
    ctx.configImport,
    ctx.servicesImport,
    ctx.mcpImport,
    ...(ctx.lifecycle
      ? [
          `import { ${ctx.lifecycle.variable} as __pikkuLifecycle } from '${ctx.lifecycle.importPath}'`,
        ]
      : []),
    `import '${ctx.bootstrapPath}'`,
    ``,
    `const PORT = Number(process.env.PORT ?? 8080)`,
    `const HOST = process.env.HOST ?? '0.0.0.0'`,
    ``,
    `async function main(): Promise<void> {`,
    `  const config = await ${ctx.configVar}()`,
    `  const singletonServices = await ${ctx.servicesVar}(config)`,
    `  pikkuState(null, 'package', 'singletonServices', singletonServices)`,
    ``,
    `  const server = new PikkuBunServer(`,
    `    { ...config, hostname: HOST, port: PORT, healthCheckPath: '/__pikku/health' },`,
    `    singletonServices.logger,`,
    `    { ${ctx.mcpServerOption}}`,
    `  )`,
    `  server.enableExitOnSignals(${
      ctx.lifecycle
        ? `{ beforeStop: () => __pikkuLifecycle?.beforeStop?.(singletonServices), afterStop: () => __pikkuLifecycle?.afterStop?.(singletonServices) }`
        : ''
    })`,
    `  await server.init()`,
    ...(ctx.lifecycle
      ? [`  await __pikkuLifecycle?.beforeStart?.(singletonServices)`]
      : []),
    `  await server.start()`,
    ...(ctx.lifecycle
      ? [`  await __pikkuLifecycle?.afterStart?.(singletonServices)`]
      : []),
    `}`,
    ``,
    `main().catch((err) => {`,
    `  console.error('pikku-server: fatal', err)`,
    `  process.exit(1)`,
    `})`,
    ``,
  ]
  return lines.join('\n')
}

export const SERVER_DOCKERFILE = `# Generated by @pikku/cli — do not edit
# Full image (not -slim): carries the build toolchain so externalised deps with
# native addons can compile from source at \`npm install\` time.
FROM oven/bun:1

RUN apt-get update \\
  && apt-get install -y --no-install-recommends tini ca-certificates \\
  && rm -rf /var/lib/apt/lists/*

RUN groupadd -r pikku && useradd -r -g pikku -u 1001 -m pikku

WORKDIR /app

# Pikku bundles user code + first-party deps inline; only externalised deps
# (typically empty for pure-JS apps) are listed in package.json. We ship no
# lockfile because the bundle has already pinned everything via the
# extracted exact-dependencies — \`bun install --production\` resolves the
# leftover externals (if any) at build time.
COPY --chown=pikku:pikku package.json ./
RUN bun install --production

COPY --chown=pikku:pikku bundle.js ./

USER pikku
ENV NODE_ENV=production
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["bun", "bundle.js"]
`

export const SERVER_DOCKERIGNORE = `node_modules
.git
*.log
metafile.json
exact-dependencies.json
`
