/**
 * Ship a SQLite build's loadable extensions inside its standalone artifact.
 *
 * `pikku dev` loads `db.sqliteExtensions` from the project's node_modules; a
 * deployed artifact has no node_modules, so a migration that creates a vec0
 * table would pass locally and fail on the first boot in production. The build
 * copies each extension's library into the unit instead, and writes a manifest
 * that embeds them for a runtime that compiles to a single binary — the same
 * two-step the frontend takes (see frontend-assets.ts for why the manifest has
 * to be a generated module of literal imports).
 *
 * The libraries are the build machine's. That is right because a standalone
 * artifact is built on, and for, one platform: `bun build --compile` targets
 * its host, and the node bundle ships beside nothing else native.
 */

import { copyFile, mkdir, rm, writeFile } from 'node:fs/promises'
import { basename, join } from 'node:path'
import {
  DEFAULT_SQLITE_EXTENSIONS,
  resolveSqliteExtension,
} from '../functions/db/sqlite/sqlite-extensions.js'
import {
  findSqliteLibrary,
  needsSqliteLibrary,
} from '../functions/db/sqlite/sqlite-library.js'

export const SQLITE_EXTENSIONS_DIR_NAME = 'sqlite-extensions'
export const SQLITE_EXTENSIONS_MANIFEST_FILE = 'sqlite-extensions.gen.js'

/**
 * The manifest module: each library embedded, paired with its original name,
 * which SQLite derives the entry point from and bun does not preserve. The
 * libsqlite3 to open them with, when one was staged, is embedded the same way.
 */
export function generateSqliteExtensionManifest(
  names: string[],
  library?: string
): string {
  const lines = ['// Generated by @pikku/cli — do not edit']
  names.forEach((name, index) => {
    lines.push(
      `import extension${index} from './${SQLITE_EXTENSIONS_DIR_NAME}/${name}' with { type: 'file' }`
    )
  })
  if (library) {
    lines.push(
      `import library from './${SQLITE_EXTENSIONS_DIR_NAME}/${library}' with { type: 'file' }`
    )
  }
  lines.push('', 'export const sqliteExtensions = [')
  names.forEach((name, index) => {
    lines.push(`  { name: '${name}', path: extension${index} },`)
  })
  lines.push(']')
  if (library) {
    lines.push(
      '',
      `export const sqliteLibrary = { name: '${library}', path: library }`
    )
  }
  lines.push('')
  return lines.join('\n')
}

export interface StagedSqliteAssets {
  /** Extension file names, in load order. */
  extensions: string[]
  /** The libsqlite3's file name, when one was staged. */
  library?: string
}

/**
 * Copy the project's SQLite extensions into `unitDir` and write the manifest.
 *
 * Unlike `pikku dev`, nothing here is skipped quietly: a default that cannot be
 * resolved on this platform fails the build, since an artifact that silently
 * lacks vec0 fails later, on a machine further from the fix. `[]` in
 * `db.sqliteExtensions` is how a project builds without them.
 *
 * With `withLibrary`, the host's libsqlite3 is staged too, wherever the target
 * runtime would otherwise open one that cannot load extensions (bun on macOS).
 * It is staged even with no extensions, so the artifact runs on the same
 * SQLite whether or not the project loads any; not finding one fails the build.
 */
export async function stageSqliteExtensions(
  projectDir: string,
  unitDir: string,
  declared: string[] | undefined,
  { withLibrary = false }: { withLibrary?: boolean } = {}
): Promise<StagedSqliteAssets> {
  const specs = declared ?? DEFAULT_SQLITE_EXTENSIONS
  const target = join(unitDir, SQLITE_EXTENSIONS_DIR_NAME)
  await rm(target, { recursive: true, force: true })
  await rm(join(unitDir, SQLITE_EXTENSIONS_MANIFEST_FILE), { force: true })

  const libraryPath = withLibrary ? stagedLibraryPath() : undefined
  if (specs.length === 0 && !libraryPath) return { extensions: [] }

  const names: string[] = []
  await mkdir(target, { recursive: true })
  for (const spec of specs) {
    let path: string
    try {
      path = resolveSqliteExtension(spec, projectDir)
    } catch (error: any) {
      throw new Error(
        `The SQLite extension '${spec}' cannot be shipped in this build: ` +
          `${error?.message ?? error}` +
          (declared === undefined
            ? ` It is loaded by default; set db.sqliteExtensions to [] in ` +
              `pikku.config.json to build without it.`
            : ''),
        { cause: error }
      )
    }
    const name = basename(path)
    if (names.includes(name)) {
      throw new Error(
        `Two SQLite extensions in db.sqliteExtensions are both named ${name}. ` +
          `They would overwrite each other in the artifact; rename one.`
      )
    }
    await copyFile(path, join(target, name))
    names.push(name)
  }

  let library: string | undefined
  if (libraryPath) {
    library = basename(libraryPath)
    if (names.includes(library)) {
      throw new Error(
        `A SQLite extension in db.sqliteExtensions is named ${library}, the ` +
          `same as the SQLite library the build ships; rename it.`
      )
    }
    await copyFile(libraryPath, join(target, library))
  }

  await writeFile(
    join(unitDir, SQLITE_EXTENSIONS_MANIFEST_FILE),
    generateSqliteExtensionManifest(names, library),
    'utf-8'
  )
  return { extensions: names, ...(library ? { library } : {}) }
}

/** The host's libsqlite3 when the target needs one, failing if it has none. */
function stagedLibraryPath(): string | undefined {
  if (!needsSqliteLibrary()) return undefined
  const lookup = findSqliteLibrary()
  if (lookup.reason !== undefined) {
    throw new Error(
      `A bun build on macOS ships its own libsqlite3, since bun there would ` +
        `otherwise open Apple's SQLite, which cannot load extensions — but ` +
        `${lookup.reason}.`
    )
  }
  return lookup.path
}
