import type { AuthProvider } from '@pikku/auth-js'

export const ALL_OAUTH_PROVIDERS: AuthProvider[] = [
  'github',
  'google',
  'discord',
  'twitter',
  'apple',
  'facebook',
  'linkedin',
  'slack',
  'spotify',
  'twitch',
  'gitlab',
  'reddit',
  'notion',
  'instagram',
  'zoom',
  'tiktok',
  'threads',
  'patreon',
  'dropbox',
  'hubspot',
  'salesforce',
  'atlassian',
  'strava',
  'auth0',
  'okta',
  'microsoft-entra-id',
  'keycloak',
  'cognito',
]
