import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Who declared a table, and where the declaration came from.
 *
 * `source` is the stable identifier a consumer filters on — the same label
 * `db generate` gives the migration it writes (`better-auth`, `pikku-runtime`,
 * an addon's flattened package name). `origin` is the prose from the migration
 * header, written for a human reading a tooltip.
 */
export interface TableProvenance {
  source: string
  origin: string
}

/**
 * The header `db generate` stamps on every migration it writes.
 *
 * Matching it is what separates a generated migration from one the project
 * authored: a file without this line declares the project's own tables, and
 * anything it creates is app-owned by definition.
 */
const GENERATED_HEADER = /^-- Generated by `pikku db generate` from (.+)\.\s*$/m

/** `0002-pikku-runtime.sql` → `pikku-runtime`. */
const MIGRATION_LABEL = /^\d+-(.+)\.sql$/

/**
 * Strip `--` line comments so a `CREATE TABLE` quoted inside a REVIEW note is
 * not mistaken for one the migration actually runs.
 */
const stripComments = (sql: string): string => sql.replace(/--[^\n]*/g, '')

const CREATE_TABLE = /\bCREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([^\s(;]+)/gi

/**
 * Drop the schema qualifier and any quoting, so `"app"."user"` and `user` are
 * the same key.
 *
 * Introspection reports a bare name on SQLite and a qualified one on Postgres,
 * while a migration may write either — comparing on the bare, unquoted name is
 * the only form both sides agree on.
 */
export function bareUnquotedTableName(name: string): string {
  const last = name.split('.').pop() ?? name
  return last.replace(/^["'`[]|["'`\]]$/g, '')
}

/**
 * Read the table→source map out of a project's migration directory.
 *
 * Provenance is decided at `db generate` time, but the schema JSON is written
 * at `db migrate` time, and the two commands do not have to run together. The
 * migration files are the durable record that survives between them: each
 * generated one carries its origin in a header and its source in its filename,
 * so re-reading them costs a directory scan and needs neither a Better Auth
 * config load nor a live database.
 *
 * Tables absent from the result are app-owned — including every table when the
 * project has no generated migrations at all.
 */
export function readMigrationProvenance(
  migrationsDir: string
): Map<string, TableProvenance> {
  const provenance = new Map<string, TableProvenance>()

  let files: string[]
  try {
    files = readdirSync(migrationsDir)
  } catch {
    // No migrations directory is the ordinary case for a project that has not
    // run `db generate` yet — every table is app-owned.
    return provenance
  }

  for (const file of files.filter((f) => f.endsWith('.sql')).sort()) {
    let sql: string
    try {
      sql = readFileSync(join(migrationsDir, file), 'utf8')
    } catch {
      continue
    }

    const header = GENERATED_HEADER.exec(sql)
    if (!header) continue

    const label = MIGRATION_LABEL.exec(file)
    if (!label) continue

    const source = label[1]!
    const origin = header[1]!

    for (const match of stripComments(sql).matchAll(CREATE_TABLE)) {
      const table = bareUnquotedTableName(match[1]!)
      // First writer wins: a later migration that recreates a table is fixing
      // it, not claiming it.
      if (!provenance.has(table)) provenance.set(table, { source, origin })
    }
  }

  return provenance
}
