import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  bareUnquotedTableName,
  readMigrationProvenance,
} from './migration-provenance.js'

const generated = (origin: string, body: string) =>
  `-- Generated by \`pikku db generate\` from ${origin}.\n` +
  '-- Re-run the command after changing that source.\n\n' +
  body +
  '\n'

function migrationsDir(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), 'migration-provenance-'))
  const migrations = join(dir, 'db', 'sqlite')
  mkdirSync(migrations, { recursive: true })
  for (const [name, contents] of Object.entries(files)) {
    writeFileSync(join(migrations, name), contents, 'utf8')
  }
  return migrations
}

test('a generated migration attributes the tables it creates', () => {
  const dir = migrationsDir({
    '0001-better-auth.sql': generated(
      'pikkuBetterAuth (Better Auth)',
      'CREATE TABLE "user" (id TEXT PRIMARY KEY);\n\nCREATE TABLE session (id TEXT PRIMARY KEY);'
    ),
    '0002-pikku-runtime.sql': generated(
      "@pikku/kysely's runtime services",
      'CREATE TABLE IF NOT EXISTS secrets (name TEXT PRIMARY KEY);'
    ),
  })

  const provenance = readMigrationProvenance(dir)

  assert.deepEqual(provenance.get('user'), {
    source: 'better-auth',
    origin: 'pikkuBetterAuth (Better Auth)',
  })
  assert.equal(provenance.get('session')?.source, 'better-auth')
  assert.deepEqual(provenance.get('secrets'), {
    source: 'pikku-runtime',
    origin: "@pikku/kysely's runtime services",
  })
})

test('an addon migration is attributed to the addon', () => {
  const dir = migrationsDir({
    '0003-pikku-addon-billing.sql': generated(
      "the '@pikku/addon-billing' addon",
      'CREATE TABLE invoice (id TEXT PRIMARY KEY);'
    ),
  })

  assert.deepEqual(readMigrationProvenance(dir).get('invoice'), {
    source: 'pikku-addon-billing',
    origin: "the '@pikku/addon-billing' addon",
  })
})

test('a hand-authored migration claims nothing', () => {
  const dir = migrationsDir({
    '0001-init.sql': 'CREATE TABLE widget (id TEXT PRIMARY KEY);',
  })

  assert.equal(readMigrationProvenance(dir).size, 0)
})

test('a project with no migrations directory yields an empty map', () => {
  assert.equal(
    readMigrationProvenance(join(tmpdir(), 'pikku-does-not-exist-ever')).size,
    0
  )
})

test('a CREATE TABLE quoted inside a REVIEW comment is not a declaration', () => {
  const dir = migrationsDir({
    '0001-pikku-runtime.sql': generated(
      "@pikku/kysely's runtime services",
      '-- REVIEW: channels is new. Copy its CREATE TABLE from the source.\n' +
        'CREATE TABLE channels (id TEXT PRIMARY KEY);'
    ),
  })

  const provenance = readMigrationProvenance(dir)
  assert.equal(provenance.size, 1)
  assert.equal(provenance.get('channels')?.source, 'pikku-runtime')
})

test('a schema-qualified or quoted name reduces to its bare form', () => {
  const dir = migrationsDir({
    '0001-pikku-runtime.sql': generated(
      "@pikku/kysely's runtime services",
      'CREATE TABLE "app"."webhook_delivery" (id TEXT PRIMARY KEY);'
    ),
  })

  assert.equal(
    readMigrationProvenance(dir).get('webhook_delivery')?.source,
    'pikku-runtime'
  )
  assert.equal(bareUnquotedTableName('"app"."user"'), 'user')
  assert.equal(bareUnquotedTableName('widget'), 'widget')
})

test('the migration that creates a table owns it, not one that recreates it', () => {
  const dir = migrationsDir({
    '0001-better-auth.sql': generated(
      'pikkuBetterAuth (Better Auth)',
      'CREATE TABLE account (id TEXT PRIMARY KEY);'
    ),
    '0002-pikku-runtime.sql': generated(
      "@pikku/kysely's runtime services",
      'CREATE TABLE IF NOT EXISTS account (id TEXT PRIMARY KEY);'
    ),
  })

  assert.equal(
    readMigrationProvenance(dir).get('account')?.source,
    'better-auth'
  )
})
