import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import type { DatabaseSync } from 'node:sqlite'

interface ColumnInfo {
  name: string
  type: string
  notnull: number
  pk: number
  dflt_value: unknown
}

interface TableInfo {
  name: string
  columns: ColumnInfo[]
}

const SKIP_TABLES = new Set(['sqlite_sequence', 'sql_migrations'])

function snakeToPascal(name: string): string {
  return name
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('')
}

function snakeToCamel(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
}

function mapType(sqlType: string): string {
  const upper = sqlType.toUpperCase()
  if (upper.includes('INT')) return 'number'
  if (
    upper.includes('CHAR') ||
    upper.includes('CLOB') ||
    upper.includes('TEXT')
  ) {
    return 'string'
  }
  if (upper.includes('BLOB')) return 'Buffer'
  if (
    upper.includes('REAL') ||
    upper.includes('FLOA') ||
    upper.includes('DOUB')
  ) {
    return 'number'
  }
  if (upper.includes('NUMERIC') || upper.includes('DECIMAL')) return 'number'
  if (upper.includes('BOOL')) return 'number'
  return 'string'
}

function listTables(db: DatabaseSync): TableInfo[] {
  const tableRows = db
    .prepare(
      `SELECT name FROM sqlite_master
         WHERE type = 'table'
           AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\'
         ORDER BY name`
    )
    .all() as Array<{ name: string }>

  return tableRows
    .filter((t) => !SKIP_TABLES.has(t.name))
    .map((t) => {
      const columns = db
        .prepare(`PRAGMA table_info(${escapeIdentifier(t.name)})`)
        .all() as unknown as ColumnInfo[]
      return { name: t.name, columns }
    })
}

function escapeIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`
}

function columnTypeExpression(col: ColumnInfo): string {
  const base = mapType(col.type)
  // Integer primary keys are auto-assigned by SQLite; treat as Generated.
  if (col.pk === 1 && mapType(col.type) === 'number') {
    return `Generated<${base}>`
  }
  // Columns with a default value can be omitted on insert.
  if (col.dflt_value !== null && col.dflt_value !== undefined) {
    return `Generated<${base}${col.notnull ? '' : ' | null'}>`
  }
  return col.notnull ? base : `${base} | null`
}

function emitInterface(table: TableInfo, camelCase: boolean): string {
  const ifaceName = snakeToPascal(table.name)
  const fields = table.columns
    .map((col) => {
      const fieldName = camelCase ? snakeToCamel(col.name) : col.name
      const type = columnTypeExpression(col)
      const safeName = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(fieldName)
        ? fieldName
        : JSON.stringify(fieldName)
      return `  ${safeName}: ${type}`
    })
    .join('\n')
  return `export interface ${ifaceName} {\n${fields}\n}`
}

export interface CodegenOptions {
  outFile: string
  camelCase?: boolean
}

export interface CodegenResult {
  outFile: string
  written: boolean
  tables: string[]
}

/**
 * Introspect the open SQLite database and emit a Kysely DB type to outFile.
 * Output shape mirrors kysely-codegen for SQLite: one interface per table,
 * a top-level `DB` interface mapping table names → row types, and
 * `Generated<T>` for autoincrement / default-valued columns.
 *
 * Returns `written: false` if the on-disk file already matches — used by
 * the dev watcher to avoid restart loops.
 */
export function generateSchemaTypes(
  db: DatabaseSync,
  options: CodegenOptions
): CodegenResult {
  const camelCase = options.camelCase ?? true
  const tables = listTables(db)

  const interfaces = tables.map((t) => emitInterface(t, camelCase)).join('\n\n')
  const dbEntries = tables
    .map((t) => {
      const tableKey = camelCase ? snakeToCamel(t.name) : t.name
      const safe = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(tableKey)
        ? tableKey
        : JSON.stringify(tableKey)
      return `  ${safe}: ${snakeToPascal(t.name)}`
    })
    .join('\n')

  const body = [
    `// Generated by @pikku/cli — do not edit by hand.`,
    `// Run \`pikku db migrate\` to refresh.`,
    ``,
    `import type { ColumnType } from 'kysely'`,
    ``,
    `export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>`,
    `  ? ColumnType<S, I | undefined, U>`,
    `  : ColumnType<T, T | undefined, T>`,
    ``,
    interfaces,
    ``,
    `export interface DB {`,
    dbEntries,
    `}`,
    ``,
  ].join('\n')

  let existing: string | null = null
  try {
    existing = readFileSync(options.outFile, 'utf8')
  } catch {
    existing = null
  }

  if (existing === body) {
    return {
      outFile: options.outFile,
      written: false,
      tables: tables.map((t) => t.name),
    }
  }

  mkdirSync(dirname(options.outFile), { recursive: true })
  writeFileSync(options.outFile, body, 'utf8')
  return {
    outFile: options.outFile,
    written: true,
    tables: tables.map((t) => t.name),
  }
}
