import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

export interface ZodCodegenOptions {
  schemaFile: string
  outFile: string
}

export interface ZodCodegenResult {
  outFile: string
  written: boolean
  tables: string[]
}

interface TableDef {
  name: string
  fields: Array<{ name: string; type: string }>
}

const INTERFACE_RE = /export\s+interface\s+(\w+)\s*\{([^}]*)\}/g
const FIELD_RE = /^\s*(\w+)\s*:\s*(.+?)\s*$/gm

export function generateZodTypes(options: ZodCodegenOptions): ZodCodegenResult {
  const src = readFileSync(options.schemaFile, 'utf8')
  const tables = parseTables(src)
  const body = emitZodModule(tables)

  let existing: string | null = null
  try {
    existing = readFileSync(options.outFile, 'utf8')
  } catch {
    // ok
  }

  const written = existing !== body
  if (written) {
    mkdirSync(dirname(options.outFile), { recursive: true })
    writeFileSync(options.outFile, body, 'utf8')
  }

  return {
    outFile: options.outFile,
    written,
    tables: tables.map((table) => table.name),
  }
}

function parseTables(src: string): TableDef[] {
  const tables: TableDef[] = []
  for (const match of src.matchAll(INTERFACE_RE)) {
    const name = match[1]
    if (name === 'DB') continue
    const body = match[2]
    const fields: TableDef['fields'] = []
    for (const field of body.matchAll(FIELD_RE)) {
      fields.push({ name: field[1], type: field[2].trim() })
    }
    tables.push({ name, fields })
  }
  return tables
}

function emitZodModule(tables: TableDef[]): string {
  const lines: string[] = []
  lines.push('// Generated by @pikku/cli — do not edit by hand.')
  lines.push('// Run `pikku db migrate` to refresh.')
  lines.push('')
  lines.push("import { z } from 'zod'")
  lines.push('')

  for (const table of tables) {
    const rowFields: string[] = []
    const insertFields: string[] = []

    for (const field of table.fields) {
      const { schema, generated } = zodForType(field.type)
      rowFields.push(`  ${field.name}: ${schema},`)
      insertFields.push(
        `  ${field.name}: ${schema}${generated ? '.optional()' : ''},`
      )
    }

    lines.push(`export const ${table.name}Z = z.object({`)
    lines.push(...rowFields)
    lines.push('})')
    lines.push('')
    lines.push(`export const ${table.name}InsertZ = z.object({`)
    lines.push(...insertFields)
    lines.push('})')
    lines.push('')
    lines.push(`export const ${table.name}PatchZ = ${table.name}Z.partial()`)
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

/**
 * Resolve a Kysely field type to a `{ schema, generated }` pair, where `schema`
 * is the zod expression for the *row* (select) shape and `generated` is true
 * when the column is optional on insert.
 *
 * `db-codegen` emits two field shapes depending on a column's classification:
 *   - public columns →  `Generated<T>`, bare `T`, `T | null`, or a public
 *                       bool/date column as `Generated<ColumnType<base, rw, rw>>`
 *   - private/pii/secret columns (the default is `private`) →
 *                       `ColumnType<Brand<base> | null, insert | undefined, update>`
 *                       where Brand is `Private` | `Pii` | `Secret`.
 *
 * For `ColumnType<Select, Insert, Update>` the row schema comes from `Select`
 * and the column is insert-optional when `Insert` admits `undefined` (Kysely's
 * encoding for default/auto/generated columns).
 */
function zodForType(tsType: string): { schema: string; generated: boolean } {
  let inner = tsType.trim()
  let generated = false

  // Peel a single `Generated<…>` wrapper. For public bool/date columns this
  // wraps a `ColumnType<…>`, so the unwrapped inner is handled below.
  const generatedMatch = inner.match(/^Generated<(.+)>$/)
  if (generatedMatch) {
    generated = true
    inner = generatedMatch[1].trim()
  }

  // `ColumnType<Select, Insert, Update>` — classified columns and wrapped
  // public bool/date columns. Row schema from Select; optional from Insert.
  if (inner.startsWith('ColumnType<') && inner.endsWith('>')) {
    const args = splitGenericArgs(inner.slice('ColumnType<'.length, -1))
    const selectT = args[0]?.trim() ?? 'unknown'
    const insertT = args[1]?.trim() ?? ''
    if (unionIncludesUndefined(insertT)) {
      generated = true
    }
    return { schema: scalarSchema(selectT), generated }
  }

  return { schema: scalarSchema(inner), generated }
}

/**
 * Resolve a scalar/select type expression to a zod expression. Handles a
 * trailing `| null`, classification brands (`Private`/`Pii`/`Secret`), arrays,
 * and the known scalar bases. Unknown bases fall back to `z.unknown()` so
 * generation stays total.
 */
function scalarSchema(tsType: string): string {
  let inner = tsType.trim()

  // Defensive: a Select arg may itself be `Generated<…>` in older schemas.
  const generatedMatch = inner.match(/^Generated<(.+)>$/)
  if (generatedMatch) {
    inner = generatedMatch[1].trim()
  }

  const nullable = inner.endsWith(' | null')
  if (nullable) {
    inner = inner.slice(0, -' | null'.length).trim()
  }

  // Unwrap a classification brand: `Private<T>` / `Pii<T>` / `Secret<T>` → T.
  const brandMatch = inner.match(/^(?:Private|Pii|Secret)<(.+)>$/)
  if (brandMatch) {
    inner = brandMatch[1].trim()
  }

  let schema: string
  switch (inner) {
    case 'string':
      schema = 'z.string()'
      break
    case 'number':
      schema = 'z.number()'
      break
    case 'boolean':
      schema = 'z.boolean()'
      break
    case 'Date':
      schema = 'z.date()'
      break
    case 'unknown':
      schema = 'z.unknown()'
      break
    default:
      if (inner.endsWith('[]')) {
        schema = `z.array(${scalarSchema(inner.slice(0, -2).trim())})`
      } else {
        schema = 'z.unknown()'
      }
      break
  }

  if (nullable) {
    schema += '.nullable()'
  }

  return schema
}

/** Split the generic argument list of `Foo<a, b, c>` on top-level commas. */
function splitGenericArgs(args: string): string[] {
  const parts: string[] = []
  let depth = 0
  let start = 0
  for (let i = 0; i < args.length; i++) {
    const char = args[i]
    if (char === '<') depth++
    else if (char === '>') depth--
    else if (char === ',' && depth === 0) {
      parts.push(args.slice(start, i))
      start = i + 1
    }
  }
  parts.push(args.slice(start))
  return parts
}

/** True when a union type expression contains `undefined` as a top-level member. */
function unionIncludesUndefined(union: string): boolean {
  return union.split('|').some((member) => member.trim() === 'undefined')
}
