import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

export interface ZodCodegenOptions {
  schemaFile: string
  outFile: string
}

export interface ZodCodegenResult {
  outFile: string
  written: boolean
  tables: string[]
}

interface TableDef {
  name: string
  fields: Array<{ name: string; type: string }>
}

const INTERFACE_RE = /export\s+interface\s+(\w+)\s*\{([^}]*)\}/g
const FIELD_RE = /^\s*(\w+)\s*:\s*(.+?)\s*$/gm

export function generateZodTypes(options: ZodCodegenOptions): ZodCodegenResult {
  const src = readFileSync(options.schemaFile, 'utf8')
  const tables = parseTables(src)
  const body = emitZodModule(tables)

  let existing: string | null = null
  try {
    existing = readFileSync(options.outFile, 'utf8')
  } catch {
    // ok
  }

  const written = existing !== body
  if (written) {
    mkdirSync(dirname(options.outFile), { recursive: true })
    writeFileSync(options.outFile, body, 'utf8')
  }

  return {
    outFile: options.outFile,
    written,
    tables: tables.map((table) => table.name),
  }
}

function parseTables(src: string): TableDef[] {
  const tables: TableDef[] = []
  for (const match of src.matchAll(INTERFACE_RE)) {
    const name = match[1]
    if (name === 'DB') continue
    const body = match[2]
    const fields: TableDef['fields'] = []
    for (const field of body.matchAll(FIELD_RE)) {
      fields.push({ name: field[1], type: field[2].trim() })
    }
    tables.push({ name, fields })
  }
  return tables
}

function emitZodModule(tables: TableDef[]): string {
  const lines: string[] = []
  lines.push('// Generated by @pikku/cli — do not edit by hand.')
  lines.push('// Run `pikku db migrate` to refresh.')
  lines.push('')
  lines.push("import { z } from 'zod'")
  lines.push('')

  for (const table of tables) {
    const rowFields: string[] = []
    const insertFields: string[] = []

    for (const field of table.fields) {
      const { schema, generated } = zodForType(field.type)
      rowFields.push(`  ${field.name}: ${schema},`)
      insertFields.push(
        `  ${field.name}: ${schema}${generated ? '.optional()' : ''},`
      )
    }

    lines.push(`export const ${table.name}Z = z.object({`)
    lines.push(...rowFields)
    lines.push('})')
    lines.push('')
    lines.push(`export const ${table.name}InsertZ = z.object({`)
    lines.push(...insertFields)
    lines.push('})')
    lines.push('')
    lines.push(`export const ${table.name}PatchZ = ${table.name}Z.partial()`)
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

function zodForType(tsType: string): { schema: string; generated: boolean } {
  const generatedMatch = tsType.match(/^Generated<(.+)>$/)
  const generated = generatedMatch !== null
  let inner = generated ? generatedMatch[1].trim() : tsType

  const nullable = inner.endsWith(' | null')
  if (nullable) {
    inner = inner.slice(0, -' | null'.length).trim()
  }

  let schema: string
  switch (inner) {
    case 'string':
      schema = 'z.string()'
      break
    case 'number':
      schema = 'z.number()'
      break
    case 'boolean':
      schema = 'z.boolean()'
      break
    case 'Date':
      schema = 'z.date()'
      break
    case 'unknown':
      schema = 'z.unknown()'
      break
    default:
      if (inner.endsWith('[]')) {
        const item = zodForType(inner.slice(0, -2).trim()).schema
        schema = `z.array(${item})`
      } else {
        schema = 'z.unknown()'
      }
      break
  }

  if (nullable) {
    schema += '.nullable()'
  }

  return { schema, generated }
}
