import { describe, test } from 'node:test'
import assert from 'node:assert/strict'
import { serializeAuthGen } from './serialize-auth-gen.js'
import type { AuthDefinition } from '@pikku/inspector'

const AUTH_FILE = '/project/.pikku/auth.gen.ts'
const SOURCE_FILE = '/project/src/auth.ts'

const def = (overrides: Partial<AuthDefinition> = {}): AuthDefinition => ({
  exportName: 'auth',
  sourceFile: SOURCE_FILE,
  basePath: '/auth',
  services: { optimized: true, services: ['kysely', 'secrets', 'variables'] },
  ...overrides,
})

const gen = (providers: string[], d: AuthDefinition = def()) =>
  serializeAuthGen(d, providers, AUTH_FILE, {})

describe('serializeAuthGen', () => {
  test('throws for unknown providers', () => {
    assert.throws(
      () => gen(['nonexistent-provider']),
      /defineAuth: unknown providers: nonexistent-provider/
    )
  })

  test('generates provider import for github', () => {
    assert.match(gen(['github']), /import GitHub from '@auth\/core\/providers\/github'/)
  })

  test('generates provider import for google', () => {
    assert.match(gen(['google']), /import Google from '@auth\/core\/providers\/google'/)
  })

  test('generates imports for all framework modules', () => {
    const output = gen(['github'])
    assert.match(output, /import { pikkuSessionlessFunc } from '#pikku'/)
    assert.match(output, /import { wireSecret } from '@pikku\/core\/secret'/)
    assert.match(output, /import { wireVariable } from '@pikku\/core\/variable'/)
    assert.match(output, /import { wireHTTPRoutes } from '@pikku\/core\/http'/)
    assert.match(output, /import { createAuthHandler } from '@pikku\/auth-js'/)
    assert.match(output, /import { z } from 'zod'/)
  })

  test('imports the exported config from the user source file', () => {
    const output = gen(['github'])
    // /project/.pikku/auth.gen.ts -> /project/src/auth.ts == ../src/auth.js
    assert.match(output, /import { auth } from '\.\.\/src\/auth\.js'/)
  })

  test('honours a custom export name', () => {
    const output = gen(['github'], def({ exportName: 'myAuth' }))
    assert.match(output, /import { myAuth } from /)
    assert.match(output, /createAuthHandler\(myAuth\.configFactory\)/)
  })

  test('generates Zod schema for github provider', () => {
    const output = gen(['github'])
    assert.match(output, /const GithubOAuthSchema = z\.object\({/)
    assert.match(output, /clientId:/)
    assert.match(output, /clientSecret:/)
  })

  test('generates wireSecret for AUTH_SECRET', () => {
    const output = gen(['github'])
    assert.match(output, /wireSecret\({/)
    assert.match(output, /secretId: 'AUTH_SECRET'/)
    assert.match(output, /displayName: 'Auth Secret'/)
  })

  test('generates wireSecret for provider credentials', () => {
    assert.match(gen(['github']), /secretId: 'GITHUB_OAUTH'/)
  })

  test('generates one shared exported handler', () => {
    const output = gen(['github'])
    assert.match(
      output,
      /export const authHandler = pikkuSessionlessFunc\(\{ func: createAuthHandler\(auth\.configFactory\)\.func \}\)/
    )
  })

  test('wires every auth route to the shared handler with auth:false', () => {
    const output = gen(['github'])
    assert.match(output, /wireHTTPRoutes\(\{/)
    assert.match(output, /route: '\/auth\/csrf', func: authHandler, auth: false/)
    assert.match(output, /route: '\/auth\/session', func: authHandler, auth: false/)
    assert.match(
      output,
      /route: '\/auth\/callback\/:provider', func: authHandler, auth: false/
    )
    assert.match(
      output,
      /route: '\/auth\/signin\/:provider', func: authHandler, auth: false/
    )
  })

  test('applies a custom basePath to every route', () => {
    const output = gen(['github'], def({ basePath: '/api/auth' }))
    assert.match(output, /route: '\/api\/auth\/csrf'/)
    assert.match(output, /route: '\/api\/auth\/session'/)
  })

  test('works with credentials-only auth (no providers)', () => {
    const output = gen([])
    assert.doesNotMatch(output, /import GitHub/)
    assert.match(output, /export const authHandler = pikkuSessionlessFunc/)
    assert.match(output, /route: '\/auth\/csrf', func: authHandler/)
    assert.match(output, /secretId: 'AUTH_SECRET'/)
  })

  test('generates code for multiple providers', () => {
    const output = gen(['github', 'google'])
    assert.match(output, /import GitHub from '@auth\/core\/providers\/github'/)
    assert.match(output, /import Google from '@auth\/core\/providers\/google'/)
    assert.match(output, /secretId: 'GITHUB_OAUTH'/)
    assert.match(output, /secretId: 'GOOGLE_OAUTH'/)
  })

  test('output starts with auto-generated comment', () => {
    assert.match(gen(['github']), /^\/\/ AUTO-GENERATED by pikku CLI/)
  })

  test('generates hyphenated provider names correctly (microsoft-entra-id)', () => {
    const output = gen(['microsoft-entra-id'])
    assert.match(output, /MicrosoftEntraIdOAuthSchema/)
    assert.match(output, /microsoftEntraIdOAuth/)
  })

  test('does not emit wireVariable for standard oauth providers', () => {
    assert.doesNotMatch(gen(['github']), /wireVariable\({/)
  })

  test('emits wireVariable for auth0 issuer', () => {
    const output = gen(['auth0'])
    assert.match(output, /wireVariable\({/)
    assert.match(output, /variableId: 'AUTH0_ISSUER'/)
    assert.match(output, /description: 'Auth0 tenant URL/)
  })

  test('emits wireVariable for okta issuer', () => {
    assert.match(gen(['okta']), /variableId: 'OKTA_ISSUER'/)
  })

  test('emits wireVariable for microsoft-entra-id tenantId', () => {
    assert.match(gen(['microsoft-entra-id']), /variableId: 'MICROSOFT_ENTRA_ID_TENANT_ID'/)
  })
})
