import { describe, test } from 'node:test'
import assert from 'node:assert/strict'
import { serializeAuthGen } from './serialize-auth-gen.js'

describe('serializeAuthGen', () => {
  test('throws for unknown providers', () => {
    assert.throws(
      () => serializeAuthGen(['nonexistent-provider']),
      /wireAuth: unknown providers: nonexistent-provider/
    )
  })

  test('generates provider import for github', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /import GitHub from '@auth\/core\/providers\/github'/)
  })

  test('generates provider import for google', () => {
    const output = serializeAuthGen(['google'])
    assert.match(output, /import Google from '@auth\/core\/providers\/google'/)
  })

  test('generates imports for all framework modules', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /import { wireSecret } from '@pikku\/core\/secret'/)
    assert.match(
      output,
      /import { wireVariable } from '@pikku\/core\/variable'/
    )
    assert.match(output, /import { wireHTTPRoutes } from '@pikku\/core\/http'/)
    assert.match(output, /import { createAuthRoutes } from '@pikku\/auth-js'/)
    assert.match(output, /import { z } from 'zod'/)
  })

  test('generates Zod schema for github provider', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /const GithubOAuthSchema = z\.object\({/)
    assert.match(output, /clientId:/)
    assert.match(output, /clientSecret:/)
  })

  test('generates wireSecret for AUTH_SECRET', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /wireSecret\({/)
    assert.match(output, /secretId: 'AUTH_SECRET'/)
    assert.match(output, /displayName: 'Auth Secret'/)
  })

  test('generates wireSecret for provider credentials', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /secretId: 'GITHUB_OAUTH'/)
  })

  test('generates createAuthRoutes call', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /const authRoutes = createAuthRoutes\(async/)
  })

  test('generates getSecrets call with AUTH_SECRET and provider secret IDs', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /services\.secrets\.getSecrets\(/)
    assert.match(output, /'AUTH_SECRET'/)
    assert.match(output, /'GITHUB_OAUTH'/)
  })

  test('generates wireHTTPRoutes registration', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /wireHTTPRoutes\({ routes: { auth: authRoutes } }\)/)
  })

  test('generates code for multiple providers', () => {
    const output = serializeAuthGen(['github', 'google'])
    assert.match(output, /import GitHub from '@auth\/core\/providers\/github'/)
    assert.match(output, /import Google from '@auth\/core\/providers\/google'/)
    assert.match(output, /secretId: 'GITHUB_OAUTH'/)
    assert.match(output, /secretId: 'GOOGLE_OAUTH'/)
    assert.match(output, /'GITHUB_OAUTH'/)
    assert.match(output, /'GOOGLE_OAUTH'/)
  })

  test('output starts with auto-generated comment', () => {
    const output = serializeAuthGen(['github'])
    assert.match(output, /^\/\/ AUTO-GENERATED by pikku CLI/)
  })

  test('generates hyphenated provider names correctly (microsoft-entra-id)', () => {
    const output = serializeAuthGen(['microsoft-entra-id'])
    assert.match(output, /MicrosoftEntraIdOAuthSchema/)
    assert.match(output, /microsoftEntraIdOAuth/)
  })

  test('does not emit wireVariable call for standard oauth providers (no variables field)', () => {
    const output = serializeAuthGen(['github'])
    assert.doesNotMatch(output, /wireVariable\({/)
  })

  test('emits wireVariable for auth0 issuer', () => {
    const output = serializeAuthGen(['auth0'])
    assert.match(output, /wireVariable\({/)
    assert.match(output, /variableId: 'AUTH0_ISSUER'/)
    assert.match(output, /description: 'Auth0 tenant URL/)
  })

  test('emits wireVariable for okta issuer', () => {
    const output = serializeAuthGen(['okta'])
    assert.match(output, /variableId: 'OKTA_ISSUER'/)
  })

  test('emits wireVariable for microsoft-entra-id tenantId', () => {
    const output = serializeAuthGen(['microsoft-entra-id'])
    assert.match(output, /variableId: 'MICROSOFT_ENTRA_ID_TENANT_ID'/)
  })

  test('uses services.variables.get in factory for OIDC providers', () => {
    const output = serializeAuthGen(['auth0'])
    assert.match(output, /services\.variables\.get\('AUTH0_ISSUER'\)/)
  })
})
