import { PROVIDER_REGISTRY, AUTH_ROUTES } from '@pikku/auth-js'
import { AUTH_HANDLER_FUNC_ID } from '@pikku/inspector'
import type { AuthDefinition } from '@pikku/inspector'
import { getFileImportRelativePath } from '../../../utils/file-import-path.js'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function providerSchemaName(name: string): string {
  return `${capitalize(name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()))}OAuthSchema`
}

function providerSecretName(name: string): string {
  return `${name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}OAuth`
}

/** A stable, valid identifier key for a route in the wireHTTPRoutes map. */
function routeKey(method: string, route: string): string {
  return `${method}${route.replace(/[^a-z0-9]/gi, '_')}`
}

/**
 * Generates the `auth.gen.ts` file from a `defineAuth` export.
 *
 * The generated file imports the user's exported config (`auth`), builds ONE
 * shared sessionless handler that delegates to Auth.js, and wires every
 * `/auth/*` route to it via `wireHTTPRoutes`. Because this is normal, statically
 * inspectable HTTP wiring, the routes flow through inspection into the deploy
 * manifest (one worker for all routes) — unlike the old runtime side-channel.
 */
export const serializeAuthGen = (
  definition: AuthDefinition,
  providers: string[],
  authFile: string,
  packageMappings: Record<string, string>
): string => {
  const known = providers.filter((p) => PROVIDER_REGISTRY[p])
  const unknown = providers.filter((p) => !PROVIDER_REGISTRY[p])

  if (unknown.length > 0) {
    throw new Error(
      `defineAuth: unknown providers: ${unknown.join(', ')}. Supported: ${Object.keys(PROVIDER_REGISTRY).join(', ')}`
    )
  }

  const basePath = definition.basePath
  const configImportPath = getFileImportRelativePath(
    authFile,
    definition.sourceFile,
    packageMappings
  )

  const lines: string[] = ['// AUTO-GENERATED by pikku CLI — do not edit', '']

  // Provider imports
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    lines.push(`import ${def.importName} from '${def.importPath}'`)
  }
  if (known.length > 0) lines.push('')

  lines.push(`import { pikkuSessionlessFunc } from '#pikku'`)
  lines.push(`import { wireSecret } from '@pikku/core/secret'`)
  lines.push(`import { wireVariable } from '@pikku/core/variable'`)
  lines.push(`import { wireHTTPRoutes } from '@pikku/core/http'`)
  lines.push(`import { createAuthHandler } from '@pikku/auth-js'`)
  lines.push(`import { ${definition.exportName} } from '${configImportPath}'`)
  lines.push(`import { z } from 'zod'`)
  lines.push('')

  // Zod schemas for each provider
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    const schemaName = providerSchemaName(name)
    const fieldLines = Object.entries(def.fields).map(
      ([field, zodExpr]) => `  ${field}: ${zodExpr},`
    )
    lines.push(`export const ${schemaName} = z.object({`)
    lines.push(...fieldLines)
    lines.push(`})`)
    lines.push('')
  }

  // wireSecret for AUTH_SECRET
  lines.push(`export const AuthSecretSchema = z.string()`)
  lines.push('')
  lines.push(`wireSecret({`)
  lines.push(`  name: 'authSecret',`)
  lines.push(`  displayName: 'Auth Secret',`)
  lines.push(`  description: 'JWT signing secret for Auth.js sessions',`)
  lines.push(`  secretId: 'AUTH_SECRET',`)
  lines.push(`  schema: AuthSecretSchema,`)
  lines.push(`})`)
  lines.push('')

  // wireSecret for each provider
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    const schemaName = providerSchemaName(name)
    const secretName = providerSecretName(name)
    lines.push(`wireSecret({`)
    lines.push(`  name: '${secretName}',`)
    lines.push(`  displayName: '${def.displayName}',`)
    lines.push(`  secretId: '${def.secretId}',`)
    lines.push(`  schema: ${schemaName},`)
    lines.push(`})`)
    lines.push('')
  }

  // wireVariable for providers with non-secret config (issuer, tenantId, etc.)
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    if (!def.variables) continue
    for (const [field, meta] of Object.entries(def.variables) as [
      string,
      { variableId: string; description: string },
    ][]) {
      lines.push(`wireVariable({`)
      lines.push(`  name: '${name}_${field}',`)
      lines.push(`  displayName: '${def.displayName} ${capitalize(field)}',`)
      lines.push(`  description: '${meta.description}',`)
      lines.push(`  variableId: '${meta.variableId}',`)
      lines.push(`  schema: z.string(),`)
      lines.push(`})`)
      lines.push('')
    }
  }

  // One shared handler for every /auth/* route. Exporting the const gives all
  // routes the same pikkuFuncId (= the export name), so they collapse to a
  // single deployed worker — and the inspector's post-process stamps this
  // handler's required services (authorize/callbacks deps) onto that same id.
  lines.push(
    `export const ${AUTH_HANDLER_FUNC_ID} = pikkuSessionlessFunc({ func: createAuthHandler(${definition.exportName}.configFactory).func })`
  )
  lines.push('')

  // Explicit HTTP wiring for the fixed Auth.js route set.
  lines.push(`wireHTTPRoutes({`)
  lines.push(`  routes: {`)
  for (const { method, route } of AUTH_ROUTES) {
    const key = routeKey(method, route)
    const fullRoute = basePath + route
    lines.push(
      `    ${key}: { method: '${method}', route: '${fullRoute}', func: ${AUTH_HANDLER_FUNC_ID}, auth: false },`
    )
  }
  lines.push(`  },`)
  lines.push(`})`)
  lines.push('')

  return lines.join('\n')
}
