import { getFileImportRelativePath } from '../../../utils/file-import-path.js'

/**
 * Generates `.pikku/auth/auth.types.ts` — a typed wrapper around `pikkuBetterAuth`
 * from `@pikku/better-auth` that substitutes the project's specific
 * `SingletonServices` type for the generic `CoreSingletonServices`. This lets
 * users write:
 *
 *   import { pikkuBetterAuth } from '#pikku'
 *
 * and get proper autocomplete on the factory's `services` param (e.g.
 * `(services) => betterAuth({ database: { db: services.kysely } })` types
 * `services.kysely` as the project's Kysely instance, not the loose `any` from
 * `CoreSingletonServices`).
 *
 * The file is re-exported from `.pikku/pikku-types.gen.ts` (the `#pikku` hub)
 * so the single import resolves correctly.
 */
export const serializeAuthTypes = (
  authTypesFile: string,
  functionTypesFile: string
): string => {
  const functionTypesImport = getFileImportRelativePath(
    authTypesFile,
    functionTypesFile,
    {}
  )

  return [
    '// AUTO-GENERATED by pikku CLI — do not edit',
    '',
    `import { pikkuBetterAuth as _pikkuBetterAuth } from '@pikku/better-auth'`,
    `import type { BetterAuthInstance, PikkuBetterAuthFactory } from '@pikku/better-auth'`,
    `import type { SingletonServices } from '${functionTypesImport}'`,
    '',
    `export const pikkuBetterAuth = <I extends BetterAuthInstance>(`,
    `  factory: (services: SingletonServices) => I | Promise<I>`,
    `): PikkuBetterAuthFactory<I> => _pikkuBetterAuth(factory as any)`,
    '',
  ].join('\n')
}
