import { getFileImportRelativePath } from '../../../utils/file-import-path.js'

/**
 * Generates `.pikku/auth/auth.types.ts` — a typed wrapper around `defineAuth`
 * from `@pikku/auth-js` that substitutes the project's specific `SingletonServices`
 * type for the generic `CoreSingletonServices`. This lets users write:
 *
 *   import { defineAuth } from '#pikku'
 *
 * and get proper autocomplete on the `authorize` / `callbacks` factory params
 * (e.g. `({ kysely }) =>` types `kysely` as the project's Kysely instance, not
 * the loose `any` from `CoreSingletonServices`).
 *
 * The file is re-exported from `.pikku/pikku-types.gen.ts` (the `#pikku` hub)
 * so the single import resolves correctly.
 */
export const serializeAuthTypes = (
  authTypesFile: string,
  functionTypesFile: string
): string => {
  const functionTypesImport = getFileImportRelativePath(
    authTypesFile,
    functionTypesFile,
    {}
  )

  return [
    '// AUTO-GENERATED by pikku CLI — do not edit',
    '',
    `import { defineAuth as _defineAuth } from '@pikku/auth-js'`,
    `import type { AuthProvider, DefineAuthOptions, DefinedAuth } from '@pikku/auth-js'`,
    `import type { SingletonServices } from '${functionTypesImport}'`,
    '',
    `export type { AuthProvider }`,
    '',
    `type TypedDefineAuthCredentials = {`,
    `  fields?: Record<string, { label?: string; type?: string; placeholder?: string; required?: boolean }>`,
    `  authorize: (services: SingletonServices, rpc: any) => (credentials: Record<string, unknown>) => Promise<any>`,
    `}`,
    '',
    `type TypedDefineAuthOptions = Omit<DefineAuthOptions, 'credentials' | 'callbacks'> & {`,
    `  credentials?: TypedDefineAuthCredentials`,
    `  callbacks?: (services: SingletonServices, rpc: any) => Record<string, (...args: any[]) => any>`,
    `}`,
    '',
    `export const defineAuth = (options: TypedDefineAuthOptions): DefinedAuth =>`,
    `  _defineAuth(options as DefineAuthOptions)`,
    '',
  ].join('\n')
}
