import { PROVIDER_REGISTRY } from '@pikku/better-auth'
import { AUTH_HANDLER_FUNC_ID } from '@pikku/inspector'
import type { AuthDefinition } from '@pikku/inspector'
import { getFileImportRelativePath } from '../../../utils/file-import-path.js'

// better-auth uses GET and POST for all of its endpoints (sign-in, callbacks,
// session, sign-out, plugin routes). A single catch-all per method forwards
// everything under basePath to better-auth's own internal router.
const AUTH_METHODS = ['get', 'post'] as const

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function providerSchemaName(name: string): string {
  return `${capitalize(name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()))}OAuthSchema`
}

function providerSecretName(name: string): string {
  return `${name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}OAuth`
}

/**
 * The two files generated from a `defineAuth` export.
 *
 * They are split because the CLI's schema/wiring-separation rule (PKU490)
 * forbids a file from declaring Zod schemas AND `wireHTTPRoutes` together —
 * schema files are imported at runtime, which would fire HTTP wiring
 * side-effects without a server context. `wireSecret`/`wireVariable` are NOT
 * HTTP wiring, so schemas may sit alongside them; only the route wiring must be
 * separated out.
 */
export interface AuthGenOutput {
  /** The HTTP wiring file (authFile): handler + catch-all routes + session middleware. */
  wiring: string
  /** The secrets file: Zod schemas + wireSecret/wireVariable. */
  secrets: string
}

/**
 * Generates the `auth.gen.ts` (HTTP wiring) and `auth-secrets.gen.ts` (schemas +
 * secret/variable wiring) files from a `defineAuth((services) => betterAuth(...))`
 * export.
 *
 * The wiring file imports the user's exported `DefinedAuth`, builds ONE shared
 * sessionless handler that delegates to better-auth's fetch handler, wires a
 * catch-all `${basePath}{/*splat}` route per method to it, registers the
 * better-auth session-bridge middleware globally, and records provider metadata
 * via `setAuthRegistry` (consumed by the console's getAuthProviders). Because
 * this is normal, statically inspectable HTTP wiring, the routes flow through
 * inspection into the deploy manifest (one worker for all auth routes).
 */
export const serializeAuthGen = (
  definition: AuthDefinition,
  providers: string[],
  authFile: string,
  packageMappings: Record<string, string>
): AuthGenOutput => {
  const known = providers.filter((p) => p in PROVIDER_REGISTRY)

  const basePath = definition.basePath
  const configImportPath = getFileImportRelativePath(
    authFile,
    definition.sourceFile,
    packageMappings
  )

  // ─── Secrets file: Zod schemas + wireSecret/wireVariable ──────────────────
  const secrets: string[] = [
    '// AUTO-GENERATED by pikku CLI — do not edit',
    '',
    `import { wireSecret } from '@pikku/core/secret'`,
  ]
  const hasVariables = known.some(
    (name) => (PROVIDER_REGISTRY as any)[name].variables
  )
  if (hasVariables) {
    secrets.push(`import { wireVariable } from '@pikku/core/variable'`)
  }
  secrets.push(`import { z } from 'zod'`, '')

  // better-auth's session-signing secret is always required (its BETTER_AUTH_SECRET
  // env convention). Wire it so the platform collects it, regardless of providers.
  secrets.push(`export const BetterAuthSecretSchema = z.string()`)
  secrets.push('')
  secrets.push(`wireSecret({`)
  secrets.push(`  name: 'betterAuthSecret',`)
  secrets.push(`  displayName: 'Better Auth Secret',`)
  secrets.push(`  description: 'Signing secret for better-auth sessions',`)
  secrets.push(`  secretId: 'BETTER_AUTH_SECRET',`)
  secrets.push(`  schema: BetterAuthSecretSchema,`)
  secrets.push(`})`)
  secrets.push('')

  // Zod schemas for each provider's OAuth credentials secret.
  for (const name of known) {
    const def = (PROVIDER_REGISTRY as any)[name]
    const schemaName = providerSchemaName(name)
    const fieldLines = Object.entries(def.fields as Record<string, string>).map(
      ([field, zodExpr]) => `  ${field}: ${zodExpr},`
    )
    secrets.push(`export const ${schemaName} = z.object({`)
    secrets.push(...fieldLines)
    secrets.push(`})`)
    secrets.push('')
  }

  // wireSecret for each provider.
  for (const name of known) {
    const def = (PROVIDER_REGISTRY as any)[name]
    const schemaName = providerSchemaName(name)
    const secretName = providerSecretName(name)
    secrets.push(`wireSecret({`)
    secrets.push(`  name: '${secretName}',`)
    secrets.push(`  displayName: '${def.displayName}',`)
    secrets.push(`  secretId: '${def.secretId}',`)
    secrets.push(`  schema: ${schemaName},`)
    secrets.push(`})`)
    secrets.push('')
  }

  // wireVariable for providers with non-secret config (issuer, tenantId, etc.).
  for (const name of known) {
    const def = (PROVIDER_REGISTRY as any)[name]
    if (!def.variables) continue
    for (const [field, meta] of Object.entries(def.variables) as [
      string,
      { variableId: string; description: string },
    ][]) {
      secrets.push(`wireVariable({`)
      secrets.push(`  name: '${name}_${field}',`)
      secrets.push(`  displayName: '${def.displayName} ${capitalize(field)}',`)
      secrets.push(`  description: '${meta.description}',`)
      secrets.push(`  variableId: '${meta.variableId}',`)
      secrets.push(`  schema: z.string(),`)
      secrets.push(`})`)
      secrets.push('')
    }
  }

  // ─── Wiring file: handler + catch-all routes + session middleware ─────────
  const registryProviders = known
    .map((name) => {
      const def = (PROVIDER_REGISTRY as any)[name]
      return `    { id: '${name}', displayName: '${def.displayName}', secretId: '${def.secretId}' },`
    })
    .join('\n')

  const wiring: string[] = [
    '// AUTO-GENERATED by pikku CLI — do not edit',
    '',
    `import { pikkuSessionlessFunc, wireHTTPRoutes, addHTTPMiddleware } from '#pikku'`,
    `import { createAuthHandler, betterAuthSession } from '@pikku/better-auth'`,
    `import { setAuthRegistry } from '@pikku/core'`,
    `import { ${definition.exportName} } from '${configImportPath}'`,
    '',
    // Provider metadata for the console (getAuthProviders reads this registry).
    // Set at module load so it is populated independently of when the lazy
    // better-auth factory first runs.
    `setAuthRegistry({`,
    `  providers: [`,
    registryProviders,
    `  ],`,
    `  hasCredentials: ${definition.hasCredentials},`,
    `})`,
    '',
    // createAuthHandler is called once at module load; the exported handler is a
    // plain arrow (so the inspector can resolve a valid `func`) that delegates to
    // it. The handler's required services are stamped onto its meta by the
    // inspector from the defineAuth factory.
    `const authConfigHandler = createAuthHandler(${definition.exportName})`,
    `export const ${AUTH_HANDLER_FUNC_ID} = pikkuSessionlessFunc({`,
    `  func: (services: any, data: any, interaction: any) =>`,
    `    authConfigHandler.func(services, data, interaction),`,
    `})`,
    '',
    // Bridge the better-auth session into the Pikku session on every request.
    `addHTTPMiddleware('*', [betterAuthSession({ auth: ${definition.exportName} })])`,
    '',
    `wireHTTPRoutes({`,
    `  routes: {`,
  ]
  // One catch-all route per method. `{/*splat}` matches both the bare basePath
  // and every sub-path under it, so better-auth's internal router sees the full
  // request and handles all of its own endpoints.
  for (const method of AUTH_METHODS) {
    wiring.push(
      `    ${method}AuthCatchAll: { method: '${method}', route: '${basePath}{/*splat}', func: ${AUTH_HANDLER_FUNC_ID}, auth: false },`
    )
  }
  wiring.push(`  },`)
  wiring.push(`})`)
  wiring.push('')

  return { wiring: wiring.join('\n'), secrets: secrets.join('\n') }
}
