import { PROVIDER_REGISTRY } from '@pikku/auth-js'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function providerSchemaName(name: string): string {
  return `${capitalize(name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()))}OAuthSchema`
}

function providerSecretName(name: string): string {
  return `${name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}OAuth`
}

export const serializeAuthGen = (providers: string[]): string => {
  const known = providers.filter((p) => PROVIDER_REGISTRY[p])
  const unknown = providers.filter((p) => !PROVIDER_REGISTRY[p])

  if (unknown.length > 0) {
    throw new Error(
      `wireAuth: unknown providers: ${unknown.join(', ')}. Supported: ${Object.keys(PROVIDER_REGISTRY).join(', ')}`
    )
  }

  const lines: string[] = ['// AUTO-GENERATED by pikku CLI — do not edit', '']

  // Provider imports
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    lines.push(`import ${def.importName} from '${def.importPath}'`)
  }
  if (known.length > 0) lines.push('')

  lines.push(`import { wireSecret } from '@pikku/core/secret'`)
  lines.push(`import { wireVariable } from '@pikku/core/variable'`)
  lines.push(`import { wireHTTPRoutes } from '@pikku/core/http'`)
  lines.push(`import { createAuthRoutes } from '@pikku/auth-js'`)
  lines.push(`import { z } from 'zod'`)
  lines.push('')

  // Zod schemas for each provider
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    const schemaName = providerSchemaName(name)
    const fieldLines = Object.entries(def.fields).map(
      ([field, zodExpr]) => `  ${field}: ${zodExpr},`
    )
    lines.push(`export const ${schemaName} = z.object({`)
    lines.push(...fieldLines)
    lines.push(`})`)
    lines.push('')
  }

  // wireSecret for AUTH_SECRET
  lines.push(`export const AuthSecretSchema = z.string()`)
  lines.push('')
  lines.push(`wireSecret({`)
  lines.push(`  name: 'authSecret',`)
  lines.push(`  displayName: 'Auth Secret',`)
  lines.push(`  description: 'JWT signing secret for Auth.js sessions',`)
  lines.push(`  secretId: 'AUTH_SECRET',`)
  lines.push(`  schema: AuthSecretSchema,`)
  lines.push(`})`)
  lines.push('')

  // wireSecret for each provider
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    const schemaName = providerSchemaName(name)
    const secretName = providerSecretName(name)
    lines.push(`wireSecret({`)
    lines.push(`  name: '${secretName}',`)
    lines.push(`  displayName: '${def.displayName}',`)
    lines.push(`  secretId: '${def.secretId}',`)
    lines.push(`  schema: ${schemaName},`)
    lines.push(`})`)
    lines.push('')
  }

  // wireVariable for providers with non-secret config (issuer, tenantId, etc.)
  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    if (!def.variables) continue
    for (const [field, meta] of Object.entries(def.variables) as [
      string,
      { variableId: string; description: string },
    ][]) {
      lines.push(`wireVariable({`)
      lines.push(`  name: '${name}_${field}',`)
      lines.push(`  displayName: '${def.displayName} ${capitalize(field)}',`)
      lines.push(`  description: '${meta.description}',`)
      lines.push(`  variableId: '${meta.variableId}',`)
      lines.push(`  schema: z.string(),`)
      lines.push(`})`)
      lines.push('')
    }
  }

  // Auth route setup
  lines.push(`const authRoutes = createAuthRoutes(async (services) => {`)
  lines.push(
    `  const secretIds = ['AUTH_SECRET', ${known.map((n) => `'${PROVIDER_REGISTRY[n].secretId}'`).join(', ')}]`
  )
  lines.push(
    `  const secretsMap = new Map(Object.entries(await services.secrets.getSecrets(secretIds)))`
  )
  lines.push('')
  lines.push(
    `  const authSecret = secretsMap.get('AUTH_SECRET') as string | undefined`
  )
  lines.push(`  const providers: any[] = []`)
  lines.push('')

  for (const name of known) {
    const def = PROVIDER_REGISTRY[name]
    const varName = providerSecretName(name)
    const hasVariables = def.variables && Object.keys(def.variables).length > 0

    lines.push(`  const ${varName}Secrets = secretsMap.get('${def.secretId}')`)
    lines.push(`  if (${varName}Secrets) {`)
    lines.push(`    const ${varName}Config = { ...${varName}Secrets as any }`)

    if (hasVariables && def.variables) {
      for (const [field, meta] of Object.entries(def.variables) as [
        string,
        { variableId: string },
      ][]) {
        lines.push(
          `    const ${varName}${capitalize(field)} = await services.variables.get('${meta.variableId}')`
        )
        lines.push(
          `    if (${varName}${capitalize(field)} !== undefined) ${varName}Config.${field} = ${varName}${capitalize(field)}`
        )
      }
    }

    lines.push(`    providers.push(${def.importName}(${varName}Config))`)
    lines.push(`  }`)
  }

  lines.push('')
  lines.push(`  return {`)
  lines.push(`    providers,`)
  lines.push(`    secret: authSecret,`)
  lines.push(`    trustHost: true,`)
  lines.push(`    basePath: '/auth',`)
  lines.push(`  }`)
  lines.push(`})`)
  lines.push('')
  lines.push(`wireHTTPRoutes({ routes: { auth: authRoutes } })`)
  lines.push('')

  return lines.join('\n')
}
