/**
 * This file was generated by @pikku/cli@0.12.21
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */

import type { StreamWorkflowRunInput } from '@pikku/addon-console/dist/.pikku/rpc/pikku-rpc-wirings-map.internal.gen'
import type { WorkflowRunStatus } from '@pikku/core/dist/wirings/workflow/workflow.types'



export type AddStageCustomHostnameInput = {
    stageId: string;
    hostname: string;
    target: "api" | "app";
    isPrimary?: boolean | undefined;
}
export type AddStageCustomHostnameOutput = {
    customHostnameId: string;
    cfCustomHostnameId: string;
    status: "pending" | "validating" | "active" | "failed";
    ownershipVerification: {
        name?: string | undefined;
        type?: string | undefined;
        value?: string | undefined;
    } | null;
}
export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type ApplyProjectDomainsInput = {
    projectId: string;
    config: {
        apps?: {
            [key: string]: {
                slug?: string | undefined;
            };
        } | undefined;
        production?: {
            branch?: string | undefined;
            domain?: string | undefined;
        } | undefined;
    };
    dryRun?: boolean | undefined;
}
export type ApplyProjectDomainsOutput = {
    dryRun: boolean;
    adds: {
        hostname: string;
        target: "api" | "app";
        isPrimary: boolean;
        applied: boolean;
        cnameTarget: string;
        ownershipVerification: {
            name?: string | undefined;
            type?: string | undefined;
            value?: string | undefined;
        } | null;
    }[];
    removes: {
        hostname: string;
        target: "api" | "app";
        applied: boolean;
    }[];
    keeps: {
        hostname: string;
        target: "api" | "app";
        cnameTarget: string;
    }[];
}
export type CheckInvitationInput = {
    email: string;
}
export type CheckInvitationOutput = {
    invited: boolean;
}
export type ConfirmCliAuthInput = {
    code: string;
}
export type ConfirmCliAuthOutput = {
    ok: boolean;
}
export type CreateCliTokenInput = {
    /** CLI localhost callback URL */
    callbackUrl: string;
}
export type CreateCliTokenOutput = {
    token: string;
    redirectUrl: string;
}
export type CreateDatabaseProjectInput = {
    neonName: string;
    projectId: string;
}
export type CreateDatabaseProjectOutput = {
    dbProjectId?: string | undefined;
    dbBranchId?: string | undefined;
    databaseUrl?: string | undefined;
}
export type CreateGitRepoInput = {
    repoName: string;
    projectId: string;
}
export type CreateGitRepoOutput = {
    repoUrl: string;
}
export type CreateProjectInput = {
    name?: string | undefined;
    templateSlug: string;
    addons: string[];
    specs: {
        content: string;
        format: string;
    }[];
    onboardingPath?: ("greenfield" | "brownfield") | undefined;
    description?: string | undefined;
    mode: "autopilot" | "manual";
}
export type CreateProjectOutput = {
    runId: string;
    projectId: string;
    projectSlug: string;
}
export type CreateProjectRecordInput = {
    organizationId: string;
    projectName: string;
    templateSlug: string;
    addons: string[];
    specFormats: string[];
    onboardingPath?: ("greenfield" | "brownfield") | undefined;
    projectDescription?: string | undefined;
    mode?: ("autopilot" | "manual") | undefined;
}
export type CreateProjectRecordOutput = {
    projectId: string;
    projectShortId: string;
    projectSlug: string;
    templateRepo: string | null;
}
export type CreateProjectWorkflowInput = { organizationId: string; orgShortId: string; userId: string; projectId: string; projectSlug: string; projectShortId: string; addons?: string[]; specs?: { content: string; format: string; }[]; onboardingPath?: "greenfield" | "brownfield"; description?: string; mode?: "autopilot" | "manual"; }
export type CreateProjectWorkflowOutput = { success: boolean; projectId: string; projectSlug: string; mainStageId: string; }
export type CreateStageRecordInput = {
    projectId: string;
}
export type CreateStageRecordOutput = {
    stageId: string;
    stageShortId: string;
    contentTokenRaw: string;
    contentTokenHash: string;
    databaseUrl?: string | undefined;
    dbBranchId?: string | undefined;
}
export type DeleteContentFileInput = {
    fileName: string;
}
export type DeleteContentFileOutput = {
    success: boolean;
}
export type DeleteProjectInput = {
    projectId: string;
}
export type DeleteProjectOutput = {
    success: boolean;
}
export type DeleteStageInput = {
    stageId: string;
}
export type DeleteStageOutput = {
    success: boolean;
    deleted: string[];
    warnings: string[];
}
export type DeployByStageKindInput = {
    projectId: string;
    branch: string;
    ref?: string | undefined;
    expectedHeadSha?: string | undefined;
}
export type DeployByStageKindOutput = {
    deploymentId: string;
    runId: string;
    stageId: string;
}
export type DeployStageInput = {
    stageId: string;
    expectedHeadSha?: string | undefined;
}
export type DeployStageOutput = {
    deploymentId: string;
    runId: string;
}
export type DeployWorkflowInput = { deploymentId: string; stageId: string; repoName: string; }
export type DeployWorkflowOutput = { success: boolean; workersDeployed: string[]; routeBound: string; }
export type DescribeStageInput = {
    stageId: string;
}
export type DescribeStageOutput = {
    namespace: {
        name: string;
        exists: boolean;
    };
    dispatcher: {
        name: string;
        exists: boolean;
    };
    scripts: string[];
    queues: {
        id: string;
        name: string;
        consumers: string[];
    }[];
    containerApps: {
        id: string;
        name: string;
        instances: number;
        max_instances: number;
    }[];
}
export type EnqueueTenantJobInput = {
    stageId: string;
    pikkuQueueName: string;
    payload: unknown;
    traceId?: string | undefined;
    jobId?: string | undefined;
}
export type EnqueueTenantJobOutput = {
    jobId: string;
    queue: string;
}
export type EnsureTelemetryOrgInput = {
    organizationId: string;
}
export type EnsureTelemetryOrgOutput = {
    created: boolean;
}
export type GetContentUploadUrlInput = {
    fileKey: string;
    contentType: string;
}
export type GetContentUploadUrlOutput = {
    uploadUrl: string;
    assetKey: string;
    uploadHeaders?: {
        [key: string]: string;
    } | undefined;
    uploadMethod?: ("PUT" | "POST") | undefined;
}
export type GetDeployArtifactUploadUrlInput = {
    deploymentId: string;
}
export type GetDeployArtifactUploadUrlOutput = {
    uploadUrl: string;
    assetKey: string;
    uploadMethod?: ("PUT" | "POST") | undefined;
    uploadHeaders?: {
        [key: string]: string;
    } | undefined;
}
export type GetFabricLogsByStageKindInput = {
    projectId: string;
    branch: string;
    source?: ("workspace" | "deploy") | undefined;
    functionName?: string | undefined;
    level?: string | undefined;
    search?: string | undefined;
    traceId?: string | undefined;
}
export type GetFabricLogsByStageKindOutput = {
    logs: {
        timestamp: string;
        level: string;
        functionName: string;
        message: string;
        traceId?: string | undefined;
    }[];
}
export type GetFabricLogsInput = {
    stageId: string;
    source?: ("workspace" | "deploy") | undefined;
    functionName?: string | undefined;
    level?: string | undefined;
    search?: string | undefined;
    traceId?: string | undefined;
}
export type GetFabricLogsOutput = {
    logs: {
        timestamp: string;
        level: string;
        functionName: string;
        message: string;
        traceId?: string | undefined;
    }[];
}
export type GetGithubInstallationInput = {
    organizationId: string;
}
export type GetGithubInstallationOutput = {
    installed: boolean;
    installation: {
        accountLogin: string;
        repositorySelection: string;
        suspended: boolean;
        manageUrl: string;
    } | null;
}
export type GetProjectDeploymentsInput = {
    /** Project slug */
    projectId: string;
}
export type GetProjectDeploymentsOutput = {
    stages: {
        stageId: string;
        branch: string;
        type: "production" | "environment" | "preview";
        url: string | null;
        containerUrl: string | null;
        cname: string | null;
        autoDeployOnPush: boolean;
        createdAt: string;
        lastUpdatedAt: string;
        deployments: {
            deploymentId: string;
            status: string;
            manifest: {
                deployment: {
                    [key: string]: unknown;
                } | null;
                versions: {
                    [key: string]: unknown;
                } | null;
                workflowHashes: {
                    [key: string]: string;
                };
            } | {
                [key: string]: unknown;
            };
            plan: {
                [key: string]: unknown;
            };
            buildLog: string | null;
            trigger: string;
            triggeredBy: string | null;
            gitSha: string | null;
            deployedAt: string | null;
            createdAt: string;
            versionMajor: number;
            versionMinor: number;
            versionPatch: number;
            bumpType: "major" | "minor" | "patch" | "none";
            promotedFromDeploymentId: string | null;
            diff: {
                units: {
                    added: string[];
                    removed: string[];
                    unchanged: string[];
                };
                handlers: {
                    added: {
                        unit: string;
                        kind: string;
                        id: string;
                        schedule?: string | undefined;
                    }[];
                    removed: {
                        unit: string;
                        kind: string;
                        id: string;
                        schedule?: string | undefined;
                    }[];
                };
                contracts: {
                    addedFunctions: string[];
                    removedFunctions: string[];
                    addedVersions: {
                        functionKey: string;
                        version: number;
                    }[];
                    removedVersions: {
                        functionKey: string;
                        version: number;
                    }[];
                    hashChanged: {
                        functionKey: string;
                        version: number;
                    }[];
                };
                workflows: {
                    added: string[];
                    removed: string[];
                    hashChanged: string[];
                };
                secrets: {
                    added: string[];
                    removed: string[];
                    modified: string[];
                };
                variables: {
                    added: string[];
                    removed: string[];
                    modified: string[];
                };
            } | null;
            changesets: {
                featurePlanId: string;
                title: string;
                summary: string | null;
                mergedAt: string;
                bumpType: "major" | "minor" | "patch" | "none";
            }[] | null;
            migrations: {
                migrationName: string;
                migrationHash: string | null;
                executedAt: string;
            }[];
        }[];
    }[];
    branchHeads: {
        branch: string;
        sha: string;
        pushedAt: string;
        pushedBy: string | null;
    }[];
}
export type GetProjectDetailsInput = {
    projectId: string;
}
export type GetProjectDetailsOutput = {
    projectId: string;
    name: string;
    slug: string;
    status: string;
    creationWorkflowRunId: string | null;
    repoName: string | null;
    config: {
        [key: string]: unknown;
    };
    createdAt: string | null;
}
export type GetProjectMetricsByStageKindInput = {
    projectId: string;
    branch: string;
    hours?: number | undefined;
    functionName?: string | undefined;
}
export type GetProjectMetricsByStageKindOutput = {
    metrics: {
        timestamp: string;
        requests: number;
        errors: number;
        avgDuration: number;
        minDuration: number;
        maxDuration: number;
    }[];
    wireTypes: {
        wireType: string;
        requests: number;
    }[];
}
export type GetProjectMetricsInput = {
    stageId: string;
    hours?: number | undefined;
    functionName?: string | undefined;
}
export type GetProjectMetricsOutput = {
    metrics: {
        timestamp: string;
        requests: number;
        errors: number;
        avgDuration: number;
        minDuration: number;
        maxDuration: number;
    }[];
    wireTypes: {
        wireType: string;
        requests: number;
    }[];
}
export type GetProjectStatusInput = {
    /** Project slug */
    projectId: string;
}
export type GetProjectStatusOutput = {
    exists: boolean;
    projectId?: string | undefined;
    projectName?: string | undefined;
    config?: {
        [key: string]: unknown;
    } | undefined;
    mcpUrl?: (string | null) | undefined;
    active?: ({
        deploymentId: string;
        stageId: string;
        stageBranch: string;
        status: string;
        trigger: string;
        gitSha: string | null;
        deployedAt: string | null;
        url: string | null;
        createdAt: string;
    } | null) | undefined;
    deploying?: ({
        deploymentId: string;
        stageId: string;
        stageBranch: string;
        status: string;
        trigger: string;
        gitSha: string | null;
        deployedAt: string | null;
        url: string | null;
        createdAt: string;
    } | null) | undefined;
    domainsDrift?: ({
        adds: number;
        removes: number;
        configMissing: boolean;
        reason: string | null;
    } | null) | undefined;
}
export type GetSessionInput = {}
export type GetSessionOutput = {
    userId: string;
    name: string | null;
    email: string;
    image: string | null;
    organizationId: string;
}
export type GetStageDatabaseSchemaInput = {
    stageId: string;
}
export type GetStageDatabaseSchemaOutput = {
    schema: any | null;
    snapshots: {
        id: string;
        migrationName: string;
        createdAt: string;
    }[];
}
export type GetStageDatabaseSchemaSnapshotInput = {
    snapshotId: string;
}
export type GetStageDatabaseSchemaSnapshotOutput = {
    schema: any;
    migrationName: string;
    createdAt: string;
}
export type GetTraceByStageKindInput = {
    projectId: string;
    branch: string;
    traceId: string;
}
export type GetTraceByStageKindOutput = {
    events: {
        timestamp: string;
        type: string;
        scriptName: string;
        wireType?: string | undefined;
        wireId?: string | undefined;
        level?: string | undefined;
        message?: string | undefined;
        outcome?: string | undefined;
        totalDuration?: number | undefined;
        functionDuration?: number | undefined;
        pikkuUserId?: string | undefined;
        httpStatus?: number | undefined;
        httpMethod?: string | undefined;
        httpPath?: string | undefined;
        errorMessage?: string | undefined;
    }[];
}
export type GetTraceInput = {
    stageId: string;
    traceId: string;
}
export type GetTraceOutput = {
    events: {
        timestamp: string;
        type: string;
        scriptName: string;
        wireType?: string | undefined;
        wireId?: string | undefined;
        level?: string | undefined;
        message?: string | undefined;
        outcome?: string | undefined;
        totalDuration?: number | undefined;
        functionDuration?: number | undefined;
        pikkuUserId?: string | undefined;
        httpStatus?: number | undefined;
        httpMethod?: string | undefined;
        httpPath?: string | undefined;
        errorMessage?: string | undefined;
    }[];
}
export type GithubInstallCallbackInput = {
    installation_id: string;
    setup_action?: string | undefined;
    state: string;
}
export type GithubInstallCallbackOutput = void | undefined
export type GithubPushWebhookInput = {
    ref: string;
    after: string;
    before?: string | undefined;
    deleted?: boolean | undefined;
    repository: {
        full_name: string;
        html_url: string;
        clone_url: string;
        default_branch?: string | undefined;
        [x: string]: unknown;
    };
    sender?: {
        login: string;
        [x: string]: unknown;
    } | undefined;
    [x: string]: unknown;
}
export type GithubPushWebhookOutput = {
    status: "queued" | "skipped";
    reason?: string | undefined;
    deploymentId?: string | undefined;
    stageId?: string | undefined;
    branch?: string | undefined;
}
export type GraphStarterInput = { workflowName: string; nodeId: string; data?: unknown; }
export type GraphStarterOutput = { runId: string; }
export type HealthCheckOutput = { ok: boolean; services: Record<string, ServiceHealth>; timestamp: string; }
export type ImportProjectInput = {
    repoUrl: string;
    defaultBranch?: string | undefined;
    name?: string | undefined;
}
export type ImportProjectOutput = {
    projectId: string;
    projectSlug: string;
    projectShortId: string;
    organizationId: string;
    mainStageId: string;
}
export type InstallAddonsInput = {
    repoName: string;
    addons: string[];
}
export type InstallAddonsOutput = {
    installed: boolean;
}
export type ListDeploymentsInput = {
    stageId: string;
}
export type ListDeploymentsOutput = {
    deployments: {
        deploymentId: string;
        stageBranch: string;
        status: string;
        trigger: string;
        triggeredBy: string | null;
        gitSha: string | null;
        manifest: {
            [key: string]: unknown;
        };
        plan: {
            [key: string]: unknown;
        };
        deployedAt: string | null;
        createdAt: string;
        versionMajor: number;
        versionMinor: number;
        versionPatch: number;
        bumpType: "major" | "minor" | "patch" | "none";
        promotedFromDeploymentId: string | null;
    }[];
}
export type ListDeploymentWorkersInput = {
    stageId: string;
}
export type ListDeploymentWorkersOutput = {
    workers: {
        name: string;
        role: string;
        status: string;
        functionIds: string[];
        createdAt: string;
    }[];
}
export type ListGithubReposInput = {
    organizationId: string;
}
export type ListGithubReposOutput = {
    repos: {
        id: number;
        fullName: string;
        name: string;
        defaultBranch: string;
        htmlUrl: string;
        cloneUrl: string;
        private: boolean;
    }[];
    installation: {
        accountLogin: string;
        repositorySelection: string;
        manageUrl: string;
    };
}
export type ListProjectsInput = {}
export type ListProjectsOutput = {
    projects: {
        id: string;
        name: string;
        slug: string;
        status: "creating" | "running" | "stopped" | "error";
        stages: {
            branch: string;
            version: string;
            status: string;
            deployedAt: string | null;
            url: string | null;
        }[];
        features: {
            active: number;
            readyToMerge: number;
        };
        activity: {
            kind: "feature_merged" | "feature_created" | "feature_building" | "deployed";
            title: string;
            timestamp: string;
        }[];
        unhealthyWorkers: string[];
    }[];
}
export type ListStageCustomHostnamesInput = {
    stageId: string;
}
export type ListStageCustomHostnamesOutput = {
    hostnames: {
        customHostnameId: string;
        hostname: string;
        target: "api" | "app";
        isPrimary: boolean;
        status: "pending" | "validating" | "active" | "failed";
        sslStatus: string | null;
        validationErrors: any | null;
        cfCustomHostnameId: string | null;
        lastCheckedAt: string | null;
        createdAt: string;
    }[];
}
export type ListStageSecretsInput = {
    projectId: string;
    branch: string;
}
export type ListStageSecretsOutput = {
    names: string[];
}
export type ListStagesInput = {
    /** Project UUID or slug */
    projectId: string;
}
export type ListStagesOutput = {
    stages: {
        stageId: string;
        branch: string;
        type: "production" | "environment" | "preview";
        url: string | null;
        containerUrl: string | null;
        createdAt: string;
        hasActiveDeployment: boolean;
    }[];
}
export type LoadDeployContextInput = {
    deploymentId: string;
}
export type LoadDeployContextOutput = {
    stageId: string;
    projectId: string;
    projectSlug: string;
    orgShortId: string;
    projectShortId: string;
    role: string;
    gitRepoUrl: string;
    gitBranch: string;
    gitSha: string;
    databaseUrl: string | null;
    hostname: string;
}
export type MarkDeploymentActiveInput = {
    deploymentId: string;
    stageId: string;
}
export type MarkDeploymentActiveOutput = {
    archivedDeploymentIds: string[];
}
export type MintConsoleTokenInput = {
    stageId: string;
}
export type MintConsoleTokenOutput = {
    token: string;
    apiUrl: string;
    expiresAt: number;
}
export type PikkuConsoleGetSecretInput = { secretId: string; }
export type PikkuConsoleGetSecretOutput = { exists: boolean; value: unknown; }
export type PikkuConsoleGetVariableInput = { variableId: string; }
export type PikkuConsoleGetVariableOutput = { exists: boolean; value: unknown; }
export type PikkuConsoleHasSecretInput = { secretId: string; }
export type PikkuConsoleHasSecretOutput = { exists: boolean; }
export type PikkuConsoleSetSecretInput = { secretId: string; value: unknown; }
export type PikkuConsoleSetSecretOutput = { success: boolean; }
export type PikkuConsoleSetVariableInput = { variableId: string; value: unknown; }
export type PikkuConsoleSetVariableOutput = { success: boolean; }
export type PikkuRemoteInternalRPCInput = { rpcName: string; data?: any; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowSleeperInput = { runId: string; stepId: string; }
export type PingStageInput = {
    stageId: string;
    path?: string | undefined;
    timeoutMs: number;
}
export type PingStageOutput = {
    hostname: string | null;
    reachable: boolean;
    status: number | null;
    latencyMs: number | null;
    error: string | null;
}
export type PollCliAuthInput = {
    code: string;
}
export type PollCliAuthOutput = {
    status: "pending" | "confirmed" | "expired";
    token?: string | undefined;
}
export type PublishCloudflareDeploymentInput = {
    deploymentId: string;
    projectId: string;
    stageId: string;
    projectSlug: string;
    orgShortId: string;
    projectShortId: string;
    gitBranch: string;
    role: string;
    gitSha: string;
    hostname: string;
    databaseUrl: string | null;
}
export type PublishCloudflareDeploymentOutput = {
    workersDeployed: string[];
    routeBound: string | null;
    namespace: string;
}
export type ReapplyDeploymentInput = {
    deploymentId: string;
}
export type ReapplyDeploymentOutput = {
    workersDeployed: string[];
    routeBound: string | null;
}
export type RecordDeployArtifactInput = {
    deploymentId: string;
    artifactHash: string;
    pikkuCliVersion?: string | undefined;
    pikkuCoreVersion?: string | undefined;
    pikkuCloudflareVersion?: string | undefined;
    pikkuDeployCloudflareVersion?: string | undefined;
    pikkuAddonConsoleVersion?: string | undefined;
    pikkufabricDeployCloudflareVersion?: string | undefined;
    hasServerUnit: boolean;
    environments?: string[] | undefined;
}
export type RecordDeployArtifactOutput = {
    artifactR2Key: string;
}
export type RefreshStageCustomHostnameInput = {
    customHostnameId: string;
}
export type RefreshStageCustomHostnameOutput = {
    status: "pending" | "validating" | "active" | "failed";
    sslStatus: string | null;
    validationErrors: any | null;
}
export type RefreshStageDatabaseSchemaInput = {
    stageId: string;
    migrationName?: string | undefined;
}
export type RefreshStageDatabaseSchemaOutput = {
    schema: any;
}
export type RemoteRPCHandlerInput = { rpcName: string; data?: unknown; }
export type RemoveStageCustomHostnameInput = {
    customHostnameId: string;
}
export type RemoveStageCustomHostnameOutput = {
    removed: boolean;
}
export type RequestCliAuthOutput = {
    code: string;
    expiresAt: string;
}
export type RollbackDeploymentInput = {
    projectId: string;
    target?: string | undefined;
}
export type RollbackDeploymentOutput = {
    candidates: {
        deploymentId: string;
        gitSha: string | null;
        artifactHash: string | null;
        deployedAt: string | null;
        versionMajor: number;
        versionMinor: number;
        versionPatch: number;
    }[];
    deploymentId?: string | undefined;
    runId?: string | undefined;
    rolledBackToDeploymentId?: string | undefined;
}
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type RunCloudflareBuildInput = {
    deploymentId: string;
    projectId: string;
    stageId: string;
    gitRepoUrl: string;
    gitBranch: string;
    gitSha: string;
    databaseUrl: string | null;
}
export type RunCloudflareBuildOutput = {
    exitCode: number;
    reused: boolean;
    hasServerUnit: boolean;
}
export type RunCloudflareImageBuildInput = {
    deploymentId: string;
    projectId: string;
    stageId: string;
    orgShortId: string;
    projectShortId: string;
    gitSha: string;
}
export type RunCloudflareImageBuildOutput = {
    imageUri: string | null;
    pushed: boolean;
    skipped: boolean;
}
export type SecretSchema_authSecret = string
export type SecretSchema_githubOAuth = {
    /** GitHub OAuth client ID */
    clientId: string;
    /** GitHub OAuth client secret */
    clientSecret: string;
}
export type SecretSchema_githubWebhookSecret = string
export type SecretSchema_gitToken = string
export type SecretSchema_googleOAuth = {
    /** Google OAuth client ID */
    clientId: string;
    /** Google OAuth client secret */
    clientSecret: string;
}
export type SetStageAutoDeployInput = {
    stageId: string;
    autoDeployOnPush: boolean;
}
export type SetStageAutoDeployOutput = {
    stageId: string;
    autoDeployOnPush: boolean;
}
export type SetStageSecretInput = {
    projectId: string;
    branch: string;
    name: string;
    value: string;
}
export type SetStageSecretOutput = {
    ok: boolean;
}
export type SignContentKeyInput = {
    contentKey: string;
    expiresInSeconds: number;
}
export type SignContentKeyOutput = {
    signedUrl: string;
}
export type StartGithubInstallInput = {
    organizationId: string;
}
export type StartGithubInstallOutput = {
    url: string;
}
export type SubmitContactFormInput = {
    name: string;
    email: string;
    company?: string | undefined;
    reason: "early_access" | "enterprise" | "question";
    message: string;
}
export type SubmitContactFormOutput = {
    success: boolean;
}
export type SubmitEarlyAccessInput = {
    name: string;
    email: string;
    company?: string | undefined;
}
export type SubmitEarlyAccessOutput = {
    success: boolean;
}
export type SyncStageInput = {
    stageId: string;
}
export type SyncStageOutput = {
    success: boolean;
    output?: string | undefined;
}
export type UpdateProjectDeploymentInput = {
    deploymentId: string;
    stageId?: string | undefined;
    url?: string | undefined;
    status?: ("active" | "stopped" | "deploying" | "error") | undefined;
    manifest?: {
        [key: string]: unknown;
    } | undefined;
    plan?: {
        [key: string]: unknown;
    } | undefined;
    buildLog?: string | undefined;
    deployedAt?: string | undefined;
}
export type UpdateProjectDeploymentOutput = {
    success: boolean;
}
export type UpdateProjectStatusInput = {
    projectId: string;
}
export type UpdateProjectStatusOutput = {
    updated: boolean;
}
export type UploadSpecsInput = {
    repoName: string;
    specs: {
        content: string;
        format: string;
    }[];
}
export type UploadSpecsOutput = {
    uploaded: boolean;
}
export type VariableSchema_gitProjectsOrg = string
export type VariableSchema_gitServerUrl = string
export type WorkflowCallerInput = { workflowName: string; input?: unknown; }
export type WorkflowCallerOutput = { runId: string; }
export type WorkflowRunnerInput = { workflowName: string; data?: unknown; }
export type WorkflowStarterInput = { workflowName: string; data?: unknown; }
export type WorkflowStarterOutput = { runId: string; }
export type WorkflowStatusCheckerInput = { workflowName: string; runId: string; }
export type WorkflowStatusStreamFullInput = { workflowName: string; runId: string; }
export type WorkflowStatusStreamInput = { workflowName: string; runId: string; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type AgentCallerInputParams = Pick<AgentCallerInput, 'agentName'> & {}
export type AgentCallerInputBody = Omit<AgentCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputParams = Pick<AgentStreamCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputBody = Omit<AgentStreamCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputParams = Pick<AgentApproveCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputBody = Omit<AgentApproveCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputParams = Pick<AgentResumeCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputBody = Omit<AgentResumeCallerInput, 'agentName'> & {}
export type StreamWorkflowRunInputParams = Pick<StreamWorkflowRunInput, 'runId'> & {}
export type StreamWorkflowRunInputBody = Omit<StreamWorkflowRunInput, 'runId'> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type RemoteRPCHandlerInputParams = Pick<RemoteRPCHandlerInput, 'rpcName'> & {}
export type RemoteRPCHandlerInputBody = Omit<RemoteRPCHandlerInput, 'rpcName'> & {}
export type WorkflowCallerInputParams = Pick<WorkflowCallerInput, 'workflowName'> & {}
export type WorkflowCallerInputBody = Omit<WorkflowCallerInput, 'workflowName'> & {}
export type WorkflowStarterInputParams = Pick<WorkflowStarterInput, 'workflowName'> & {}
export type WorkflowStarterInputBody = Omit<WorkflowStarterInput, 'workflowName'> & {}
export type WorkflowRunnerInputParams = Pick<WorkflowRunnerInput, 'workflowName'> & {}
export type WorkflowRunnerInputBody = Omit<WorkflowRunnerInput, 'workflowName'> & {}
export type WorkflowStatusCheckerInputParams = Pick<WorkflowStatusCheckerInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusCheckerInputBody = Omit<WorkflowStatusCheckerInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamInputParams = Pick<WorkflowStatusStreamInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamInputBody = Omit<WorkflowStatusStreamInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamFullInputParams = Pick<WorkflowStatusStreamFullInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamFullInputBody = Omit<WorkflowStatusStreamFullInput, 'workflowName' | 'runId'> & {}
export type GraphStarterInputParams = Pick<GraphStarterInput, 'workflowName' | 'nodeId'> & {}
export type GraphStarterInputBody = Omit<GraphStarterInput, 'workflowName' | 'nodeId'> & {}
export type GetDeployArtifactUploadUrlInputBody = GetDeployArtifactUploadUrlInput & {}
export type RecordDeployArtifactInputBody = RecordDeployArtifactInput & {}
export type GithubInstallCallbackInputBody = GithubInstallCallbackInput & {}
export type EnqueueTenantJobInputBody = EnqueueTenantJobInput & {}
export type GithubPushWebhookInputBody = GithubPushWebhookInput & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/workflow-run/:runId/stream': {
    readonly GET: HTTPWiringHandler<StreamWorkflowRunInput, null>,
  },
  readonly '/workflow/:workflowName/status/:runId': {
    readonly GET: HTTPWiringHandler<WorkflowStatusCheckerInput, WorkflowRunStatus>,
  },
  readonly '/workflow/:workflowName/status/:runId/stream': {
    readonly GET: HTTPWiringHandler<WorkflowStatusStreamInput, null>,
  },
  readonly '/workflow/:workflowName/status/:runId/stream/full': {
    readonly GET: HTTPWiringHandler<WorkflowStatusStreamFullInput, null>,
  },
  readonly '/auth/csrf': {
    readonly GET: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/providers': {
    readonly GET: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/session': {
    readonly GET: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/signin': {
    readonly GET: HTTPWiringHandler<null, null>,
    readonly POST: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/callback/:provider': {
    readonly GET: HTTPWiringHandler<null, null>,
    readonly POST: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/signout': {
    readonly GET: HTTPWiringHandler<null, null>,
    readonly POST: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/error': {
    readonly GET: HTTPWiringHandler<null, null>,
  },
  readonly '/auth/github/install/callback': {
    readonly GET: HTTPWiringHandler<GithubInstallCallbackInput, GithubInstallCallbackOutput>,
  },
  readonly '/health-check': {
    readonly GET: HTTPWiringHandler<null, HealthCheckOutput>,
  },
  readonly '/rpc/agent/:agentName': {
    readonly POST: HTTPWiringHandler<AgentCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/stream': {
    readonly POST: HTTPWiringHandler<AgentStreamCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/approve': {
    readonly POST: HTTPWiringHandler<AgentApproveCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/resume': {
    readonly POST: HTTPWiringHandler<AgentResumeCallerInput, null>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
  },
  readonly '/remote/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RemoteRPCHandlerInput, null>,
  },
  readonly '/rpc/workflow/:workflowName': {
    readonly POST: HTTPWiringHandler<WorkflowCallerInput, WorkflowCallerOutput>,
  },
  readonly '/workflow/:workflowName/start': {
    readonly POST: HTTPWiringHandler<WorkflowStarterInput, WorkflowStarterOutput>,
  },
  readonly '/workflow/:workflowName/run': {
    readonly POST: HTTPWiringHandler<WorkflowRunnerInput, null>,
  },
  readonly '/workflow/:workflowName/graph/:nodeId': {
    readonly POST: HTTPWiringHandler<GraphStarterInput, GraphStarterOutput>,
  },
  readonly '/auth/signin/:provider': {
    readonly POST: HTTPWiringHandler<null, null>,
  },
  readonly '/deploy/artifact-upload-url': {
    readonly POST: HTTPWiringHandler<GetDeployArtifactUploadUrlInput, GetDeployArtifactUploadUrlOutput>,
  },
  readonly '/deploy/artifact-recorded': {
    readonly POST: HTTPWiringHandler<RecordDeployArtifactInput, RecordDeployArtifactOutput>,
  },
  readonly '/tenant/enqueue': {
    readonly POST: HTTPWiringHandler<EnqueueTenantJobInput, EnqueueTenantJobOutput>,
  },
  readonly '/webhooks/github': {
    readonly POST: HTTPWiringHandler<GithubPushWebhookInput, GithubPushWebhookOutput>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  