-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "agent_message" ("id" varchar(36) primary key, "thread_id" varchar(36) not null references "agent_threads" ("id") on delete cascade, "role" varchar(50) not null, "content" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_message_thread" on "agent_message" ("thread_id", "created_at");

create table "agent_run" ("run_id" varchar(36) primary key, "agent_name" varchar(255) not null, "thread_id" varchar(36) not null references "agent_threads" ("id") on delete cascade, "resource_id" varchar(255) not null, "status" varchar(50) default 'running' not null, "error_message" text, "suspend_reason" text, "missing_rpcs" text, "pending_approvals" text, "usage_input_tokens" integer default 0 not null, "usage_output_tokens" integer default 0 not null, "usage_model" varchar(255) default '' not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_run_thread" on "agent_run" ("thread_id", "created_at");

create table "agent_run_score" ("id" varchar(36) primary key, "run_id" varchar(36) not null references "agent_run" ("run_id") on delete cascade, "scorer_name" varchar(255) not null, "score" real not null, "reason" text, "metadata" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_run_score_run" on "agent_run_score" ("run_id", "created_at");

create table "agent_threads" ("id" varchar(36) primary key, "resource_id" varchar(255) not null, "title" text, "metadata" text, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_threads_resource" on "agent_threads" ("resource_id");

create table "agent_tool_call" ("id" varchar(36) primary key, "thread_id" varchar(36) not null references "agent_threads" ("id") on delete cascade, "message_id" varchar(36) not null references "agent_message" ("id") on delete cascade, "run_id" varchar(36), "tool_name" varchar(255) not null, "args" text not null, "result" text, "approval_status" varchar(50), "approval_type" varchar(50), "agent_run_id" varchar(36), "display_tool_name" varchar(255), "display_args" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_agent_tool_call_thread" on "agent_tool_call" ("thread_id");

create index "idx_agent_tool_call_message" on "agent_tool_call" ("message_id");

create table "agent_working_memory" ("id" varchar(255) not null, "scope" varchar(50) not null, "data" text not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null, constraint "agent_working_memory_pk" primary key ("id", "scope"));

create table "audit" ("audit_id" text primary key, "occurred_at" text not null, "type" text not null, "source" text default 'auto' not null, "outcome" text, "function_id" text, "wire_type" text, "trace_id" text, "transaction_id" text, "query_id" text, "user_id" text, "org_id" text, "pikku_user_id" text, "tables" text, "changed_cols" text, "event" text, "old" text, "data" text);

create index "idx_audit_occurred_at" on "audit" ("occurred_at");

create index "idx_audit_user_id" on "audit" ("user_id");

create index "idx_audit_type" on "audit" ("type");

create table "credential_kek_salts" ("key_version" integer primary key, "salt" varchar(64) not null, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create table "secret_kek_salts" ("key_version" integer primary key, "salt" varchar(64) not null, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create table "virtual_user_run" ("run_id" varchar(36) primary key, "persona" varchar(255) not null, "disposition" varchar(50) not null, "seed" bigint not null, "status" varchar(50) default 'running' not null, "goals" text default '[]' not null, "memory" text default '{}' not null, "findings" text default '[]' not null, "intents" text default '[]' not null, "tally" text, "stopped_by" varchar(255), "error" text, "started_by" varchar(255), "created_at" timestamp default CURRENT_TIMESTAMP not null, "finished_at" timestamp);

create index "idx_virtual_user_run_created" on "virtual_user_run" ("created_at");

create index "idx_virtual_user_run_persona" on "virtual_user_run" ("persona", "created_at");

create table "virtual_user_run_step" ("run_id" varchar(36) not null, "step_index" integer not null, "intent_id" varchar(255), "action" text not null, "status" integer, "ok" integer, "response" text, "finding_kinds" text, "tokens_in" integer default 0 not null, "tokens_out" integer default 0 not null, constraint "pk_virtual_user_run_step" primary key ("run_id", "step_index"));

create table "virtual_user_schedule" ("persona" varchar(255) primary key, "enabled" integer default 0 not null, "disposition" varchar(50) not null, "goals" text default '[]' not null, "budget" text, "min_interval_ms" bigint not null, "max_interval_ms" bigint not null, "next_run_at" timestamp not null, "last_run_id" varchar(36), "last_run_at" timestamp);

create index "idx_virtual_user_schedule_due" on "virtual_user_schedule" ("enabled", "next_run_at");

ALTER TABLE workflow_step ADD COLUMN current_attempt INTEGER;

ALTER TABLE workflow_step_history ADD COLUMN attempt INTEGER;
