-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "pikku_lease" ("key" text primary key, "holder" text not null, "token" integer not null, "expires_at" bigint not null);

ALTER TABLE workflow_step ADD COLUMN lease_expires_at bigint;
