import { PikkuCLIConfig } from '../../pikku-cli-config.js'
import { InspectorState } from '@pikku/inspector'
import {
  writeFileInDir,
  getFileImportRelativePath,
  getPikkuFilesAndMethods,
} from '../../utils.js'
import { PikkuCommand } from '../../types.js'

export const pikkuCLIBootstrap: PikkuCommand = async (
  logger,
  config: PikkuCLIConfig,
  visitState: InspectorState
) => {
  if (visitState.cli.files.size === 0) {
    return true
  }

  // Generate bootstrap files for each program
  for (const [programName, programMeta] of Object.entries(
    visitState.cli.meta
  )) {
    const bootstrapFile = `.pikku/cli/pikku-bootstrap-${programName}-cli.gen.ts`

    // Get service factories
    const { singletonServicesFactory, sessionServicesFactory } =
      await getPikkuFilesAndMethods(
        logger,
        visitState,
        config.packageMappings,
        bootstrapFile,
        {}, // options
        {
          singletonServicesFactory: true,
          sessionServicesFactory: true,
        }
      )

    const bootstrapCode = generateCLIBootstrap(
      programName,
      programMeta,
      bootstrapFile,
      config,
      singletonServicesFactory,
      sessionServicesFactory
    )

    await writeFileInDir(logger, bootstrapFile, bootstrapCode)
    logger.info(`Generated CLI bootstrap for ${programName}: ${bootstrapFile}`)
  }

  return true
}

/**
 * Generates the CLI bootstrap code for a specific program
 */
function generateCLIBootstrap(
  programName: string,
  programMeta: any,
  bootstrapFile: string,
  config: PikkuCLIConfig,
  singletonServicesFactory: { file: string; variable: string },
  sessionServicesFactory: { file: string; variable: string }
): string {
  const capitalizedName =
    programName.charAt(0).toUpperCase() + programName.slice(1).replace(/-/g, '')

  // Get relative import paths
  const singletonServicesPath = getFileImportRelativePath(
    bootstrapFile,
    singletonServicesFactory.file,
    config.packageMappings
  )
  const sessionServicesPath = getFileImportRelativePath(
    bootstrapFile,
    sessionServicesFactory.file,
    config.packageMappings
  )
  const cliWiringsPath = getFileImportRelativePath(
    bootstrapFile,
    config.cliWiringsFile,
    config.packageMappings
  )
  const cliMetaPath = getFileImportRelativePath(
    bootstrapFile,
    config.cliWiringMetaFile,
    config.packageMappings
  )
  const functionsMetaPath = getFileImportRelativePath(
    bootstrapFile,
    config.functionsMetaFile,
    config.packageMappings
  )
  const schemasPath = getFileImportRelativePath(
    bootstrapFile,
    `${config.schemaDirectory}/register.gen.ts`,
    config.packageMappings
  )

  return `/**
 * This file was generated by the @pikku/cli
 */
import { parseCLIArguments, runCLICommand, generateCommandHelp, pikkuState } from '@pikku/core'
import { ${singletonServicesFactory.variable} as createSingletonServices } from '${singletonServicesPath}'
import { ${sessionServicesFactory.variable} as createSessionServices } from '${sessionServicesPath}'
import '${cliMetaPath}'
import '${functionsMetaPath}'
import '${cliWiringsPath}'
import '${schemasPath}'

/**
 * ${capitalizedName} CLI function
 * Handles command line arguments and executes the appropriate function
 */
export async function ${capitalizedName}CLI(args: string[] = process.argv.slice(2)): Promise<void> {
  try {
    // Get CLI metadata from state
    const allCLIMeta = pikkuState('cli', 'meta') || {}
    const programMeta = allCLIMeta['${programName}']

    if (!programMeta) {
      console.error('Error: CLI program "${programName}" not found')
      process.exit(1)
    }

    // Handle help
    if (args.includes('--help') || args.includes('-h') || args.length === 0) {
      showHelp(programMeta)
      return
    }

    // Parse arguments for this specific program
    const parsed = parseCLIArguments(args, '${programName}', allCLIMeta)

    if (parsed.errors.length > 0) {
      console.error('Errors:')
      parsed.errors.forEach(error => console.error(\`  \${error}\`))
      process.exit(1)
    }

    // Create services
    const singletonServices = await createSingletonServices()

    // Execute the command
    await runCLICommand({
      program: '${programName}',
      commandPath: parsed.commandPath,
      positionals: parsed.positionals,
      options: parsed.options,
      singletonServices,
      createSessionServices,
    })

  } catch (error: any) {
    console.error('Error:', error.message)

    // Show stack trace in verbose mode
    if (args.includes('--verbose') || args.includes('-v')) {
      console.error('Stack trace:', error.stack)
    }

    process.exit(1)
  }
}

/**
 * Show help for the CLI program
 */
function showHelp(programMeta: any): void {
  console.log(\`Usage: ${programName} [options] <command>\`)
  console.log()

  if (programMeta.description) {
    console.log(programMeta.description)
    console.log()
  }

  // Show global options
  if (programMeta.options && Object.keys(programMeta.options).length > 0) {
    console.log('Global Options:')
    for (const [name, option] of Object.entries(programMeta.options)) {
      const opt = option as any
      const short = opt.short ? \`-\${opt.short}, \` : ''
      const defaultVal = opt.default !== undefined ? \` (default: \${opt.default})\` : ''
      console.log(\`  \${short}--\${name}  \${opt.description || ''}\${defaultVal}\`)
    }
    console.log()
  }

  // Show commands
  if (programMeta.commands && Object.keys(programMeta.commands).length > 0) {
    console.log('Commands:')
    showCommandsHelp(programMeta.commands, '')
  }

  console.log()
  console.log('Use --help with any command for more details')
}

/**
 * Recursively show commands help
 */
function showCommandsHelp(commands: any, prefix: string): void {
  for (const [name, command] of Object.entries(commands)) {
    const cmd = command as any
    const fullName = prefix ? \`\${prefix} \${name}\` : name

    if (cmd.command) {
      // Leaf command
      console.log(\`  \${fullName.padEnd(20)} \${cmd.description || ''}\`)
    } else if (cmd.subcommands) {
      // Command group
      console.log(\`  \${fullName.padEnd(20)} \${cmd.description || ''}\`)
      showCommandsHelp(cmd.subcommands, fullName)
    }
  }
}

// Export as default for easy importing
export default ${capitalizedName}CLI

// For direct execution (if this file is run directly)
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  ${capitalizedName}CLI().catch(error => {
    console.error('Fatal error:', error.message)
    process.exit(1)
  })
}
`
}
