import type { CorePikkuFunctionSessionless } from '@pikku/core/function'
import { toWebRequest } from '@pikku/core/http'
import type { DefinedAuth } from './define-auth.js'

/**
 * Creates a Pikku sessionless function that delegates to better-auth.
 *
 * A single catch-all `${basePath}/**` route (generated by the pikku CLI) points
 * at this handler. better-auth owns all of its sub-routing internally — sign-in,
 * callbacks, session, sign-out, plugin routes — so Pikku needs exactly one
 * handler regardless of which providers/plugins are enabled.
 *
 * The handler converts the Pikku request into a Web `Request`, hands it to
 * better-auth's fetch handler, and returns the Web `Response` directly. The
 * Pikku HTTP runner applies that response (status, headers, cookies, body).
 */
export const createAuthHandler = (
  auth: DefinedAuth
): { func: CorePikkuFunctionSessionless<any, any> } => ({
  func: async (services, _input, { http }) => {
    const request = http?.request
    if (!request) {
      return
    }
    const instance = await auth.getInstance(services)
    const webRequest = toWebRequest(request)
    return await instance.handler(webRequest)
  },
})
