/**
 * Generates the sibling secrets file for a project that declares personas.
 *
 * `SCENARIO_ACTOR_SECRET` is the platform's, not the application's: nothing in
 * app code reads it. It is consumed by the scenario service when it signs an
 * actor in, by `pikku scenario` / `pikku persona` / `pikku persona sync`, and by
 * the Playwright provider. Declaring it here — rather than leaving every project
 * to hand-write the same `defineSecret` — is the same reasoning that puts
 * `BETTER_AUTH_SECRET` in the auth scaffold: a value the framework requires
 * regardless of what the user wired should be collected by the platform, not
 * discovered missing at the first sign-in.
 *
 * The schema is a named const because the inspector only accepts a variable
 * reference for `schema`, never an inline expression.
 */
export const serializePersonasSecrets = () => {
  return `/**
 * This file was generated by the @pikku/cli
 */
import { defineSecret } from '@pikku/core/secret'
import { z } from 'zod'

export const ScenarioActorSecretSchema = z.string()

defineSecret({
  name: 'scenarioActorSecret',
  displayName: 'Scenario Actor Secret',
  description:
    'Signing secret that lets scenarios and virtual users sign in as a declared persona',
  secretId: 'SCENARIO_ACTOR_SECRET',
  schema: ScenarioActorSecretSchema,
})
`
}
