import type { PersonaDefinitions } from '@pikku/core/ecosystem/persona'

export interface SerializePersonasOptions {
  definitions: PersonaDefinitions
  /** Relative import path to the generated roles file. */
  rolesImportPath: string
  /** Keys of `environments` in pikku.config.json. */
  environmentNames: string[]
}

const quote = (value: string) => `'${value.replace(/'/g, "\\'")}'`

/**
 * Generates the `PersonaId` union and a `definePersonas` whose `roles` are
 * checked against the declared system roles.
 *
 * The wrapper is why this is generated rather than re-exported: `roles` typed
 * as `string[]` would let a persona name a role nobody declared, and the
 * failure — a scatter of 403s in a run days later — looks nothing like the
 * mistake. Typed as `SystemRoleName[]`, it is a red squiggle in the editor.
 */
export const serializePersonasTypes = ({
  rolesImportPath,
  environmentNames,
}: SerializePersonasOptions) => {
  const environmentUnion =
    environmentNames.length > 0
      ? `\n${[...environmentNames]
          .sort()
          .map((name) => `  | ${quote(name)}`)
          .join('\n')}`
      : ' never'

  return `/**
 * This file was generated by the @pikku/cli
 */
import { definePersonas as definePersonasCore } from '@pikku/core/persona'
import type { PersonaMeta, PersonasMeta } from '@pikku/core/persona'
import type { CorePersona } from '@pikku/core/ecosystem/persona'
import type { SystemRoleName } from '${rolesImportPath}'
import definitions from './pikku-personas-meta.gen.json' with { type: 'json' }

/** Every environment configured in pikku.config.json. */
type EnvironmentName =${environmentUnion}

/**
 * A persona whose roles are checked against \`defineSystemRole\` and whose
 * environments are checked against the config.
 *
 * Omitting \`environments\` means every environment except the ones flagged
 * \`production: true\`. Naming a production one additionally requires
 * \`disposition: 'accountable'\`, which the type cannot express and \`pikku\`
 * refuses at build time.
 */
type TypedPersona = Omit<CorePersona, 'roles' | 'environments'> & {
  roles?: SystemRoleName[]
  environments?: EnvironmentName[]
}

/**
 * Declare the people who use this application.
 *
 * A persona while running is a virtual user; there is no second declaration.
 */
export const definePersonas = (personas: Record<string, TypedPersona>): void =>
  definePersonasCore(personas)

/** Declared personas, keyed by id. Read by the console and \`pikku persona\`. */
export const PERSONAS: PersonasMeta = definitions as unknown as PersonasMeta

export const PERSONA_LIST: PersonaMeta[] = Object.values(PERSONAS)
`
}
