/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addChannel function call */
import '../src/channel.routes.js'

import { setChannelsMeta } from '@pikku/core/channel'
setChannelsMeta([
  {
    "name": "events",
    "route": "/",
    "input": null,
    "connect": true,
    "disconnect": true,
    "message": {
      "inputs": [
        "OnMessageInput"
      ],
      "outputs": [
        "OnMessageOutput"
      ]
    },
    "messageRoutes": {
      "action": {
        "auth": {
          "inputs": [
            "AuthInput"
          ],
          "outputs": [
            "AuthOutput"
          ]
        },
        "subscribe": {
          "inputs": [
            "SubscribeInput"
          ],
          "outputs": []
        },
        "unsubscribe": {
          "inputs": [
            "UnsubscribeInput"
          ],
          "outputs": []
        },
        "emit": {
          "inputs": [
            "EmitInput"
          ],
          "outputs": [
            "EmitOutput"
          ]
        }
      }
    }
  }
])