/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addFunction function call */
import '../src/channel.functions.js'
import '../src/http-progressive-enhancement.js'
import '../src/http-sse.js'
import '../src/http.js'
import '../src/rpc.js'
import '../src/scheduled-task.js'