/**
 * This file was generated by the @pikku/cli
 */
import './functions/pikku-functions-meta.gen.js'
import './rpc/pikku-rpc-meta.gen.js'
import './http/pikku-http-routes-meta.gen.js'
import './scheduler/pikku-schedules-meta.gen.js'
import './queue/pikku-queue-workers-meta.gen.js'
import './channels/pikku-channels-meta.gen.js'
import './functions/pikku-functions.gen.js'
import './schemas/register.gen.js'
import './http/pikku-http-routes.gen.js'
import './scheduler/pikku-schedules.gen.js'
import './queue/pikku-queue-workers.gen.js'
import './channels/pikku-channels.gen.js'
