/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addSerializedTasks function call */
import '../src/scheduled-task.js'

import { setScheduledTasksMeta } from '@pikku/core/scheduler'
setScheduledTasksMeta([
  {
    name: 'myScheduledTask',
    schedule: '*/1 * * * *',
    tags: ['hello'],
  },
])
export type ScheduledTaskNames = 'myScheduledTask'
