/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addRoute function call */
import '../src/http.js'

import { setHTTPRoutesMeta } from '@pikku/core/http'
setHTTPRoutesMeta([
  {
    "route": "/hello-world",
    "method": "get",
    "input": null,
    "output": "HelloWorldOutput"
  }
])