/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  pikkuFn_src_channel_functions_ts_L9C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L9C3',
    name: 'onConnect',
    services: {
      optimized: true,
      services: ['logger', 'channel'],
    },
    schemaName: 'OnConnectInput',
    inputs: ['OnConnectInput'],
    outputs: [],
  },
  pikkuFn_src_channel_functions_ts_L18C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L18C3',
    name: 'onDisconnect',
    services: {
      optimized: true,
      services: ['logger', 'channel'],
    },
    schemaName: null,
    inputs: [],
    outputs: [],
  },
  pikkuFn_src_channel_functions_ts_L28C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L28C3',
    name: 'authenticate',
    services: {
      optimized: true,
      services: ['userSession'],
    },
    schemaName: 'AuthenticateInput',
    inputs: ['AuthenticateInput'],
    outputs: ['AuthenticateOutput'],
  },
  pikkuFn_src_channel_functions_ts_L37C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L37C3',
    name: 'subscribe',
    services: {
      optimized: true,
      services: ['eventHub', 'channel'],
    },
    schemaName: 'SubscribeInput',
    inputs: ['SubscribeInput'],
    outputs: [],
  },
  pikkuFn_src_channel_functions_ts_L43C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L43C3',
    name: 'unsubscribe',
    services: {
      optimized: true,
      services: ['channel', 'eventHub'],
    },
    schemaName: 'UnsubscribeInput',
    inputs: ['UnsubscribeInput'],
    outputs: [],
  },
  pikkuFn_src_channel_functions_ts_L51C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L51C3',
    name: 'emitMessage',
    services: {
      optimized: true,
      services: ['userSession', 'eventHub', 'channel'],
    },
    schemaName: 'EmitMessageInput',
    inputs: ['EmitMessageInput'],
    outputs: ['EmitMessageOutput'],
  },
  pikkuFn_src_channel_functions_ts_L60C3: {
    pikkuFuncName: 'pikkuFn_src_channel_functions_ts_L60C3',
    name: 'onMessage',
    services: {
      optimized: true,
      services: ['logger', 'channel'],
    },
    schemaName: 'OnMessageInput',
    inputs: ['OnMessageInput'],
    outputs: ['OnMessageOutput'],
  },
  pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3: {
    pikkuFuncName: 'pikkuFn_src_http_progressive_enhancement_functions_ts_L6C3',
    name: 'progressiveEnhancementExample',
    services: {
      optimized: false,
      services: [],
    },
    schemaName: null,
    inputs: [],
    outputs: ['ProgressiveEnhancementExampleOutput'],
  },
  pikkuFn_src_http_sse_functions_ts_L6C3: {
    pikkuFuncName: 'pikkuFn_src_http_sse_functions_ts_L6C3',
    name: 'timeSinceOpened',
    services: {
      optimized: true,
      services: [],
    },
    schemaName: null,
    inputs: [],
    outputs: ['TimeSinceOpenedOutput'],
  },
  pikkuFn_src_http_functions_ts_L3C54: {
    pikkuFuncName: 'pikkuFn_src_http_functions_ts_L3C54',
    name: 'helloWorld',
    services: {
      optimized: true,
      services: [],
    },
    schemaName: null,
    inputs: [],
    outputs: ['string'],
  },
  pikkuFn_src_mcp_functions_ts_L10C3: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L10C3',
    name: 'sayHello',
    services: {
      optimized: false,
      services: [],
    },
    schemaName: 'SayHelloInput',
    inputs: ['SayHelloInput'],
    outputs: ['SayHelloOutput'],
  },
  pikkuFn_src_mcp_functions_ts_L27C3: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L27C3',
    name: 'calculate',
    services: {
      optimized: false,
      services: [],
    },
    schemaName: 'CalculateInput',
    inputs: ['CalculateInput'],
    outputs: ['CalculateOutput'],
  },
  pikkuFn_src_mcp_functions_ts_L66C3: {
    pikkuFuncName: 'pikkuFn_src_mcp_functions_ts_L66C3',
    name: 'getUserInfo',
    services: {
      optimized: false,
      services: [],
    },
    schemaName: 'GetUserInfoInput',
    inputs: ['GetUserInfoInput'],
    outputs: ['GetUserInfoOutput'],
  },
  pikkuFn_src_queue_worker_functions_ts_L6C3: {
    pikkuFuncName: 'pikkuFn_src_queue_worker_functions_ts_L6C3',
    name: 'queueWorker',
    services: {
      optimized: true,
      services: [],
    },
    schemaName: 'QueueWorkerInput',
    inputs: ['QueueWorkerInput'],
    outputs: ['QueueWorkerOutput'],
  },
  pikkuFn_src_rpc_functions_ts_L4C3: {
    pikkuFuncName: 'pikkuFn_src_rpc_functions_ts_L4C3',
    name: 'rpcTest',
    services: {
      optimized: true,
      services: ['logger', 'rpc'],
    },
    schemaName: 'RpcTestInput',
    inputs: ['RpcTestInput'],
    outputs: [],
  },
  pikkuFn_src_rpc_functions_ts_L15C47: {
    pikkuFuncName: 'pikkuFn_src_rpc_functions_ts_L15C47',
    name: 'rpcCaller',
    services: {
      optimized: true,
      services: ['rpc', 'logger'],
    },
    schemaName: null,
    inputs: [],
    outputs: [],
  },
  pikkuFn_src_scheduled_task_functions_ts_L4C3: {
    pikkuFuncName: 'pikkuFn_src_scheduled_task_functions_ts_L4C3',
    name: 'myScheduledTask',
    services: {
      optimized: true,
      services: ['logger'],
    },
    schemaName: null,
    inputs: [],
    outputs: [],
  },
})
