/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addChannel function call */
import '../src/channel.routes.js'

import { pikkuState } from '@pikku/core'
pikkuState('channel', 'meta', [
  {
    name: 'events',
    route: '/',
    input: null,
    connect: true,
    disconnect: true,
    message: {
      inputs: ['OnMessageInput'],
      outputs: ['OnMessageOutput'],
      type: 'ChannelMessage',
    },
    messageRoutes: {
      action: {
        auth: {
          inputs: ['AuthInput'],
          outputs: ['AuthOutput'],
          type: 'ChannelMessage',
        },
        subscribe: {
          inputs: ['SubscribeInput'],
          outputs: [],
          type: 'ChannelMessage',
        },
        unsubscribe: {
          inputs: ['UnsubscribeInput'],
          outputs: [],
          type: 'ChannelMessage',
        },
        emit: {
          inputs: ['EmitInput'],
          outputs: ['EmitOutput'],
          type: 'ChannelMessage',
        },
      },
    },
    tags: ['events'],
  },
])
