/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addRoute function call */
import '../src/http-progressive-enhancement.js'
import '../src/http-sse.js'
import '../src/http.js'

import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', [
  {
    route: '/status/sse',
    method: 'get',
    input: null,
    output: 'ProgressiveEnhancementExampleOutput',
  },
  {
    route: '/status/http',
    method: 'get',
    input: null,
    output: 'ProgressiveEnhancementExampleOutput',
  },
  {
    route: '/sse',
    method: 'get',
    input: null,
    output: 'TimeSinceOpenedOutput',
  },
  {
    route: '/hello-world',
    method: 'get',
    input: null,
    output: 'HelloWorldOutput',
    tags: ['hello'],
  },
])
