/**
 * This file was generated by the @pikku/cli
 */

import { PikkuFetch } from './pikku-fetch.gen.js'
import type { RPCInvoke } from './rpc/pikku-rpc-map.gen.js'

export class RPCHandler {
  pikkuFetch = new PikkuFetch()

  setPikkuFetch(pikkuFetch: PikkuFetch): void {
    this.pikkuFetch = pikkuFetch
  }

  setServerUrl(serverUrl: string): void {
    this.pikkuFetch.setServerUrl(serverUrl)
  }

  setAuthorizationJWT(jwt: string | null): void {
    this.pikkuFetch.setAuthorizationJWT(jwt)
  }

  // Generic RPC invoke method
  rpc: RPCInvoke = async (name, data) => {
    return await this.pikkuFetch.post('/rpc', { name, data })
  }
}

export const pikkuRPC = new RPCHandler()
