/**
 * This file was generated by the @pikku/cli
 */
import './pikku-functions-meta.gen.js'
import './pikku-queue-workers-meta.gen.js'
import './pikku-functions.gen.js'
import './pikku-schemas/register.gen.js'
import './pikku-queue-workers.gen.js'
