/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  pikkuFn____functions_src_channel_functions_ts_L9C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L9C3',
    name: 'onConnect',
    services: {
      optimized: true,
      services: ['logger', 'channel'],
    },
    schemaName: 'OnConnectInput',
    inputs: ['OnConnectInput'],
    outputs: [],
  },
  pikkuFn____functions_src_channel_functions_ts_L18C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L18C3',
    name: 'onDisconnect',
    services: {
      optimized: true,
      services: ['logger', 'channel'],
    },
    schemaName: null,
    inputs: [],
    outputs: [],
  },
  pikkuFn____functions_src_channel_functions_ts_L28C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L28C3',
    name: 'authenticate',
    services: {
      optimized: true,
      services: ['userSession'],
    },
    schemaName: 'AuthenticateInput',
    inputs: ['AuthenticateInput'],
    outputs: ['AuthenticateOutput'],
  },
  pikkuFn____functions_src_channel_functions_ts_L37C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L37C3',
    name: 'subscribe',
    services: {
      optimized: true,
      services: ['eventHub', 'channel'],
    },
    schemaName: 'SubscribeInput',
    inputs: ['SubscribeInput'],
    outputs: [],
  },
  pikkuFn____functions_src_channel_functions_ts_L43C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L43C3',
    name: 'unsubscribe',
    services: {
      optimized: true,
      services: ['channel', 'eventHub'],
    },
    schemaName: 'UnsubscribeInput',
    inputs: ['UnsubscribeInput'],
    outputs: [],
  },
  pikkuFn____functions_src_channel_functions_ts_L51C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L51C3',
    name: 'emitMessage',
    services: {
      optimized: true,
      services: ['userSession', 'eventHub', 'channel'],
    },
    schemaName: 'EmitMessageInput',
    inputs: ['EmitMessageInput'],
    outputs: ['EmitMessageOutput'],
  },
  pikkuFn____functions_src_channel_functions_ts_L60C3: {
    pikkuFuncName: 'pikkuFn____functions_src_channel_functions_ts_L60C3',
    name: 'onMessage',
    services: {
      optimized: true,
      services: ['logger', 'channel'],
    },
    schemaName: 'OnMessageInput',
    inputs: ['OnMessageInput'],
    outputs: ['OnMessageOutput'],
  },
  pikkuFn____functions_src_http_progressive_enhancement_ts_L10C3: {
    pikkuFuncName:
      'pikkuFn____functions_src_http_progressive_enhancement_ts_L10C3',
    name: 'progressiveEnhancementExample',
    services: {
      optimized: false,
      services: [],
    },
    schemaName: null,
    inputs: [],
    outputs: ['ProgressiveEnhancementExampleOutput'],
  },
  pikkuFn____functions_src_http_sse_ts_L7C3: {
    pikkuFuncName: 'pikkuFn____functions_src_http_sse_ts_L7C3',
    name: 'timeSinceOpened',
    services: {
      optimized: true,
      services: [],
    },
    schemaName: null,
    inputs: [],
    outputs: ['TimeSinceOpenedOutput'],
  },
  pikkuFn____functions_src_http_ts_L6C54: {
    pikkuFuncName: 'pikkuFn____functions_src_http_ts_L6C54',
    name: 'helloWorld',
    services: {
      optimized: true,
      services: [],
    },
    schemaName: null,
    inputs: [],
    outputs: ['string'],
  },
  pikkuFn____functions_src_rpc_ts_L7C3: {
    pikkuFuncName: 'pikkuFn____functions_src_rpc_ts_L7C3',
    name: 'rpcTest',
    services: {
      optimized: true,
      services: ['logger', 'rpc'],
    },
    schemaName: 'RpcTestInput',
    inputs: ['RpcTestInput'],
    outputs: [],
  },
  pikkuFn____functions_src_rpc_ts_L18C47: {
    pikkuFuncName: 'pikkuFn____functions_src_rpc_ts_L18C47',
    name: 'rpcCaller',
    services: {
      optimized: true,
      services: ['rpc', 'logger'],
    },
    schemaName: null,
    inputs: [],
    outputs: [],
  },
  pikkuFn____functions_src_scheduled_task_ts_L6C58: {
    pikkuFuncName: 'pikkuFn____functions_src_scheduled_task_ts_L6C58',
    name: 'pikkuFn____functions_src_scheduled_task_ts_L6C58',
    services: {
      optimized: true,
      services: ['logger'],
    },
    schemaName: null,
    inputs: [],
    outputs: [],
  },
})
