/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addHTTPRoute function call */
import '../src/http-progressive-enhancement.js'
import '../src/http-sse.js'
import '../src/http.js'
import '../src/rpc.js'
