/**
 * This file was generated by the @pikku/cli
 */
import './pikku-functions-meta.gen.js'
import './pikku-rpc-meta.gen.js'
import './pikku-http-routes-meta.gen.js'
import './pikku-schedules-meta.gen.js'
import './pikku-queue-workers-meta.gen.js'
import './pikku-channels-meta.gen.js'
import './pikku-functions.gen.js'
import './pikku-schemas/register.gen.js'
import './pikku-http-routes.gen.js'
import './pikku-schedules.gen.js'
import './pikku-queue-workers.gen.js'
import './pikku-channels.gen.js'
