/**
 * This file was generated by the @pikku/cli
 */
/* The files with an addRoute function call */
import '../src/http.js'

import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', [
  {
    route: '/hello-world',
    method: 'get',
    input: null,
    output: 'HelloWorldOutput',
    tags: ['hello'],
  },
])
