/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', [
  {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_ts_L10C3",
    "route": "/status/sse",
    "method": "get",
    "input": null,
    "output": "ProgressiveEnhancementExampleOutput"
  },
  {
    "pikkuFuncName": "pikkuFn_src_http_progressive_enhancement_ts_L10C3",
    "route": "/status/http",
    "method": "get",
    "input": null,
    "output": "ProgressiveEnhancementExampleOutput"
  },
  {
    "pikkuFuncName": "pikkuFn_src_http_sse_ts_L7C3",
    "route": "/sse",
    "method": "get",
    "input": null,
    "output": "TimeSinceOpenedOutput"
  },
  {
    "pikkuFuncName": "pikkuFn_src_http_ts_L6C54",
    "route": "/hello-world",
    "method": "get",
    "input": null,
    "output": "string",
    "tags": [
      "hello"
    ]
  }
])