import { dirname, join, relative, resolve } from 'path'
import { mkdir, readFile, rename, writeFile, rm } from 'fs/promises'
import { existsSync } from 'fs'
import type { CLILogger } from '../services/cli-logger.service.js'
import { getCLIVersion } from './get-cli-version.js'

export const DO_NOT_MODIFY_COMMENT = `/**
 * This file was generated by @pikku/cli@${getCLIVersion()}
 */
`

/**
 * While set, writes and removals under this directory are skipped.
 *
 * Deploy plan runs a full `pikku all` per unit with `--outDir` redirected to
 * that unit's `.pikku`. Scaffold files are project *source* — generated once,
 * then owned and edited by the developer — and their imports are computed
 * against `config.outDir`, so regenerating them under a redirected outDir
 * rewrites the developer's tree to point at
 * `.deploy/<provider>/units/<unit>/.pikku` and leaves it failing to typecheck
 * until the next ordinary `pikku all`.
 *
 * Guarding the writer rather than each generator is deliberate: generators are
 * added regularly, several write both scaffold source and `.pikku` artifacts in
 * one pass (so an all-or-nothing early return would skip too much), and a new
 * one that forgets the check is silently correct here.
 */
let scaffoldWriteGuardDir: string | undefined

export const setScaffoldWriteGuard = (dir: string | undefined) => {
  scaffoldWriteGuardDir = dir ? resolve(dir) : undefined
}

export const isScaffoldWriteGuarded = (path: string) =>
  scaffoldWriteGuardDir !== undefined &&
  !relative(scaffoldWriteGuardDir, resolve(path)).startsWith('..')

let tsWriteGeneration = 0
const TS_FILE_REGEX = /\.[mc]?tsx?$/

export const getTsWriteGeneration = () => tsWriteGeneration

export const writeFileInDir = async (
  logger: CLILogger,
  path: string,
  content: string,
  {
    ignoreModifyComment = false,
    logWrite = true,
  }: { ignoreModifyComment?: boolean; logWrite?: boolean } = {}
) => {
  if (isScaffoldWriteGuarded(path)) {
    logger.debug({
      message: `↷ Skipped scaffold write to ${path} (per-unit deploy codegen)`,
      type: 'info',
    })
    return
  }

  if (path.includes('.json')) {
    ignoreModifyComment = true
  }

  if (content.includes('server-only')) {
    content = content.replace(
      "'server-only'",
      `'server-only'\n\n${ignoreModifyComment ? '' : DO_NOT_MODIFY_COMMENT}`
    )
  } else {
    content = `${ignoreModifyComment ? '' : DO_NOT_MODIFY_COMMENT}${content}`
  }

  // Try to read existing file content
  let existingContent: string | undefined
  try {
    existingContent = await readFile(path, 'utf-8')
  } catch (error) {
    // Only suppress ENOENT (file not found) errors
    // Rethrow permission, I/O, encoding, or other errors
    const nodeError = error as NodeJS.ErrnoException
    if (nodeError.code !== 'ENOENT') {
      throw error
    }
    // File doesn't exist, so we need to write it
  }

  // Only write if content has changed or file doesn't exist
  if (existingContent !== content) {
    await mkdir(dirname(path), { recursive: true })
    // Atomically, because generated files are read while they are generated:
    // `pikku scenario run --spawn` bundles the registers while the dev server it
    // spawned is regenerating them, and `writeFile` truncates before it writes —
    // a reader that lands in that window gets an empty file, not an old one.
    const tmp = `${path}.${process.pid}.tmp`
    try {
      await writeFile(tmp, content, 'utf-8')
      await rename(tmp, path)
    } catch (e) {
      await rm(tmp, { force: true }).catch(() => {})
      throw e
    }
    if (TS_FILE_REGEX.test(path)) {
      tsWriteGeneration++
    }

    if (logWrite) {
      logger.debug({ message: `✓ File written to ${path}`, type: 'success' })
    }
  }
}

export function kebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

export function scaffoldFilePath(
  config: { rootDir: string; srcDirectories: string[] },
  subdir: string,
  name: string,
  suffix: string,
  overrideDir?: string
): string {
  const fileName = kebabCase(name)
  if (overrideDir) {
    return join(overrideDir, subdir, `${fileName}${suffix}`)
  }
  return join(
    config.rootDir,
    config.srcDirectories[0],
    subdir,
    `${fileName}${suffix}`
  )
}

export const removeFileInDir = async (
  logger: CLILogger,
  path: string,
  { logRemove = true }: { logRemove?: boolean } = {}
) => {
  if (isScaffoldWriteGuarded(path)) {
    logger.debug({
      message: `↷ Skipped scaffold removal of ${path} (per-unit deploy codegen)`,
      type: 'info',
    })
    return
  }

  // Check if file exists before attempting removal
  if (existsSync(path)) {
    await rm(path, { force: true })
    if (TS_FILE_REGEX.test(path)) {
      tsWriteGeneration++
    }

    if (logRemove) {
      logger.debug({ message: `✓ File removed at ${path}`, type: 'success' })
    }
  }
}
