import { dirname, join } from 'path'
import { mkdir, readFile, writeFile, rm } from 'fs/promises'
import { existsSync } from 'fs'
import type { CLILogger } from '../services/cli-logger.service.js'
import { getCLIVersion } from './get-cli-version.js'

export const DO_NOT_MODIFY_COMMENT = `/**
 * This file was generated by @pikku/cli@${getCLIVersion()}
 */
`

export const writeFileInDir = async (
  logger: CLILogger,
  path: string,
  content: string,
  {
    ignoreModifyComment = false,
    logWrite = true,
  }: { ignoreModifyComment?: boolean; logWrite?: boolean } = {}
) => {
  if (path.includes('.json')) {
    ignoreModifyComment = true
  }

  if (content.includes('server-only')) {
    content = content.replace(
      "'server-only'",
      `'server-only'\n\n${ignoreModifyComment ? '' : DO_NOT_MODIFY_COMMENT}`
    )
  } else {
    content = `${ignoreModifyComment ? '' : DO_NOT_MODIFY_COMMENT}${content}`
  }

  // Try to read existing file content
  let existingContent: string | undefined
  try {
    existingContent = await readFile(path, 'utf-8')
  } catch (error) {
    // Only suppress ENOENT (file not found) errors
    // Rethrow permission, I/O, encoding, or other errors
    const nodeError = error as NodeJS.ErrnoException
    if (nodeError.code !== 'ENOENT') {
      throw error
    }
    // File doesn't exist, so we need to write it
  }

  // Only write if content has changed or file doesn't exist
  if (existingContent !== content) {
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, content, 'utf-8')

    if (logWrite) {
      logger.debug({ message: `✓ File written to ${path}`, type: 'success' })
    }
  }
}

export function kebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

export function scaffoldFilePath(
  config: { rootDir: string; srcDirectories: string[] },
  subdir: string,
  name: string,
  suffix: string
): string {
  const fileName = kebabCase(name)
  return join(
    config.rootDir,
    config.srcDirectories[0],
    subdir,
    `${fileName}${suffix}`
  )
}

export const removeFileInDir = async (
  logger: CLILogger,
  path: string,
  { logRemove = true }: { logRemove?: boolean } = {}
) => {
  // Check if file exists before attempting removal
  if (existsSync(path)) {
    await rm(path, { force: true })

    if (logRemove) {
      logger.debug({ message: `✓ File removed at ${path}`, type: 'success' })
    }
  }
}
