export const serializeNextJsBackendWorkerRPCWrapper = (
  routesMapPath: string,
  rpcMapPath: string,
  fetcherImportPath: string,
  globalHTTPPrefix: string = ''
) => {
  return `'server-only'

/**
 * Worker-RPC variant of the Next.js backend wrapper. Function code is NOT
 * loaded in-process — every call is dispatched through the injected Fetcher.
 * Generated by @pikku/cli (nextBackendTransport: 'worker-rpc').
 */
import { PikkuNextJSWorkerRPC } from '@pikku/next'
import { NextRequest } from 'next/server.js'
import type { HTTPWiringsMap, HTTPWiringHandlerOf, HTTPWiringsWithMethod } from '${routesMapPath}'
import type { FlattenedRPCMap } from '${rpcMapPath}'
import { fetcher } from '${fetcherImportPath}'

type RouteContext = { params: Promise<Record<string, string | string[]>> }

let _pikku: PikkuNextJSWorkerRPC | undefined
let _removeAPIPrefix = true

export const removeAPIPrefix = (enable: boolean) => {
  _removeAPIPrefix = enable
}

export const pikku = (_options?: any) => {
  if (!_pikku) {
    _pikku = new PikkuNextJSWorkerRPC({ fetcher })
  }

  const dynamicActionRequest = async <
    Route extends keyof HTTPWiringsMap,
    Method extends keyof HTTPWiringsMap[Route]
  >(
    route: Route,
    method: Method,
    data: HTTPWiringHandlerOf<Route, Method>['input'] = null
  ): Promise<HTTPWiringHandlerOf<Route, Method>['output']> => {
    return _pikku!.actionRequest(route, method, data as any)
  }

  const staticActionRequest = async <
    Route extends keyof HTTPWiringsMap,
    Method extends keyof HTTPWiringsMap[Route]
  >(
    route: Route,
    method: Method,
    data: HTTPWiringHandlerOf<Route, Method>['input'] = null
  ): Promise<HTTPWiringHandlerOf<Route, Method>['output']> => {
    return _pikku!.staticActionRequest(route, method, data as any)
  }

  const dynamicPost = <Route extends HTTPWiringsWithMethod<'POST'>>(
    route: Route,
    ...args: HTTPWiringHandlerOf<Route, 'POST'>['input'] extends null | undefined
      ? [data?: HTTPWiringHandlerOf<Route, 'POST'>['input']]
      : [data: NonNullable<HTTPWiringHandlerOf<Route, 'POST'>['input']>]
  ): Promise<HTTPWiringHandlerOf<Route, 'POST'>['output']> => {
    return dynamicActionRequest(route, 'POST', args[0] ?? null)
  }

  const dynamicGet = <Route extends HTTPWiringsWithMethod<'GET'>>(
    route: Route,
    ...args: HTTPWiringHandlerOf<Route, 'GET'>['input'] extends null | undefined
      ? [data?: HTTPWiringHandlerOf<Route, 'GET'>['input']]
      : [data: NonNullable<HTTPWiringHandlerOf<Route, 'GET'>['input']>]
  ): Promise<HTTPWiringHandlerOf<Route, 'GET'>['output']> => {
    return dynamicActionRequest(route, 'GET', args[0] ?? null)
  }

  const dynamicPatch = <Route extends HTTPWiringsWithMethod<'PATCH'>>(
    route: Route,
    ...args: HTTPWiringHandlerOf<Route, 'PATCH'>['input'] extends null | undefined
      ? [data?: HTTPWiringHandlerOf<Route, 'PATCH'>['input']]
      : [data: NonNullable<HTTPWiringHandlerOf<Route, 'PATCH'>['input']>]
  ): Promise<HTTPWiringHandlerOf<Route, 'PATCH'>['output']> => {
    return dynamicActionRequest(route, 'PATCH', args[0] ?? null)
  }

  const dynamicDel = <Route extends HTTPWiringsWithMethod<'DELETE'>>(
    route: Route,
    ...args: HTTPWiringHandlerOf<Route, 'DELETE'>['input'] extends null | undefined
      ? [data?: HTTPWiringHandlerOf<Route, 'DELETE'>['input']]
      : [data: NonNullable<HTTPWiringHandlerOf<Route, 'DELETE'>['input']>]
  ): Promise<HTTPWiringHandlerOf<Route, 'DELETE'>['output']> => {
    return dynamicActionRequest(route, 'DELETE', args[0] ?? null)
  }

  const staticPost = <Route extends HTTPWiringsWithMethod<'POST'>>(
    route: Route,
    ...args: HTTPWiringHandlerOf<Route, 'POST'>['input'] extends null | undefined
      ? [data?: HTTPWiringHandlerOf<Route, 'POST'>['input']]
      : [data: NonNullable<HTTPWiringHandlerOf<Route, 'POST'>['input']>]
  ): Promise<HTTPWiringHandlerOf<Route, 'POST'>['output']> => {
    return staticActionRequest(route, 'POST', args[0] ?? null)
  }

  const staticGet = <Route extends HTTPWiringsWithMethod<'GET'>>(
    route: Route,
    ...args: HTTPWiringHandlerOf<Route, 'GET'>['input'] extends null | undefined
      ? [data?: HTTPWiringHandlerOf<Route, 'GET'>['input']]
      : [data: NonNullable<HTTPWiringHandlerOf<Route, 'GET'>['input']>]
  ): Promise<HTTPWiringHandlerOf<Route, 'GET'>['output']> => {
    return staticActionRequest(route, 'GET', args[0] ?? null)
  }

  // RPC dispatch goes through the underlying actionRequest (route: unknown)
  // rather than the typed dynamic/static wrappers — '/rpc/:rpcName' isn't
  // necessarily registered as an HTTPWiringsMap key in projects that haven't
  // explicitly wired one. Output type is enforced via FlattenedRPCMap.
  const rpc = async <Name extends keyof FlattenedRPCMap>(
    rpcName: Name,
    data: FlattenedRPCMap[Name]['input']
  ): Promise<FlattenedRPCMap[Name]['output']> => {
    return _pikku!.actionRequest(
      '${globalHTTPPrefix}/rpc/:rpcName',
      'POST',
      { rpcName, data: data ?? null }
    ) as Promise<FlattenedRPCMap[Name]['output']>
  }

  const staticRPC = async <Name extends keyof FlattenedRPCMap>(
    rpcName: Name,
    data: FlattenedRPCMap[Name]['input']
  ): Promise<FlattenedRPCMap[Name]['output']> => {
    return _pikku!.staticActionRequest(
      '${globalHTTPPrefix}/rpc/:rpcName',
      'POST',
      { rpcName, data: data ?? null }
    ) as Promise<FlattenedRPCMap[Name]['output']>
  }

  return {
    rpc,
    get: dynamicGet,
    post: dynamicPost,
    patch: dynamicPatch,
    del: dynamicDel,
    staticGet,
    staticPost,
    staticRPC,
  }
}

export const pikkuAPIRequest = (
  req: NextRequest,
  context: RouteContext
): Promise<Response> => {
  if (!_pikku) {
    _pikku = new PikkuNextJSWorkerRPC({ fetcher })
  }
  if (_removeAPIPrefix) {
    const url = new URL(req.url)
    url.pathname = url.pathname.replace(/^\\/api/, '') || '/'
    req = new NextRequest(url.toString(), {
      method: req.method,
      headers: req.headers,
      body: req.body,
      duplex: 'half',
    } as any)
  }
  return _pikku.apiRequest(req)
}
`
}
