export const UI_CRITIQUE_RUBRIC = [
  'You are grading whether this ONE screen looks like a polished, purpose-built product',
  'or like generic AI slop. Judge ONLY what is visible in the screenshot. Flag a finding',
  'when you see any of these high-signal failures:',
  '',
  '- CRASHED / ERROR SCREEN: the page rendered a framework error boundary instead of the product',
  '  — a bare "This page isn\'t working properly" / "Something went wrong" / "An error occurred"',
  '  panel, a "Reload"/"Details" button with no product UI, a raw stack trace, or a visible React',
  '  error message ("Objects are not valid as a React child"). This is the MOST severe finding — mark',
  '  it HIGH. Fix: the route threw during render; the usual cause is a raw value dropped into JSX',
  '  (a bare `{date}` object) — format it (dayjs for dates) or guard the value.',
  '',
  '- FLAT GRAY-SLOP THEME: default shadcn neutral grey survived; no committed domain colour on',
  '  the primary actions, headers, or accents. A real product commits to a palette.',
  '- A ROW OF IDENTICAL CARDS holding content that is not uniform — same size, same corner,',
  '  same border, one per topic. Committing to a colour does not excuse it: three navy panels',
  '  are the same failure as four gray ones. On a dashboard specifically, equal-weight number',
  '  cards replace what belongs there — ONE focal chart plus an attention queue. Fix: weight the',
  '  regions to the content (a list is a list, a set of counters is not a card, the one that',
  '  matters is bigger), so the eye is told where to go.',
  '- UPPERCASE LETTER-SPACED EYEBROW above sections ("HEALTH", "OVERVIEW", "FEATURES") — a small',
  '  all-caps kicker over each heading or card. On most AI-generated pages and almost no designed',
  '  ones; when it appears on EVERY section it is the single clearest tell. Fix: delete them and',
  '  let the heading and the spacing carry the section.',
  '- NO TYPE HIERARCHY: everything at one or two sizes in the same default sans, so nothing leads.',
  '  A designed screen has a real scale and a face chosen on purpose. Fix: set the display size and',
  '  weight of the one thing that matters, and let the rest drop back.',
  '- NEAR-BLACK BY DEFAULT: a dark page on an app that is not a developer, terminal, code, media,',
  '  music or observability product. Dark is the AI-slop default and it flattens everything — it',
  '  is right only when the domain asks for it. A journal, tracker, booking, commerce, health,',
  '  finance, education or general consumer app is LIGHT. Fix: move to a light scheme where the',
  '  brand colour can carry at full saturation.',
  '- DECORATIVE REFLEXES: gradient-filled text, a coloured side-stripe down the edge of cards or',
  '  alerts, or frosted/blurred glass panels used as decoration rather than to solve something.',
  '- BLANK / EMPTY SECTIONS: a panel, hero, or column that rendered with nothing in it',
  '  (a scroll-reveal that never fired, an unfilled region).',
  '- NO EMPTY STATE: a bare table, a lone spinner, or raw "Loading…"/"No data" text where',
  '  an empty view should teach — an icon, a one-line description, and a create-first',
  '  button. (An intentional, well-designed empty state is a PASS, not a finding.)',
  '- CLIPPED OR OVERFLOWING TEXT; a metric/row/nav running off the edge; content colliding',
  '  or overlapping; broken spacing rhythm (cramped or wildly uneven gaps).',
  '- OFF-REGISTER — the most important check when you were told what the app is. Two bars, and',
  '  the wrong one is a HIGH finding even when the screen is competent and breaks nothing else:',
  '  A TOOL (CRM, admin console, warehouse, booking, dashboard) should be quiet and legible —',
  '  flag it when it is dressed up as a marketing page. An app someone opens AT HOME BY CHOICE,',
  '  where the content is the whole reason — a journal, a bedtime story, a meditation or',
  '  breathing app, a recipe box, a kids app, a hobby or garden log, a keepsake, a game —',
  '  is held to a different bar, and there the failure is BLANDNESS, not strangeness. It should',
  '  look MADE: a physical object someone chose the materials for. Flag it when instead it looks',
  '  CONFIGURED — a competent admin panel wearing the subject as a title. Concretely, on one of',
  '  these apps expect a real display face at a generous size, a page MATERIAL (warm paper, bone,',
  '  night — never default white or default dark), colour as a field the content sits in rather',
  '  than an accent on grey, and often ONE centred column instead of the standard sidebar shell.',
  '  Fix: name what the thing would be if it were physical, then say which of those is missing.',
  '- MOBILE (when the shot is a phone width): horizontal page scroll, a desktop navbar',
  '  covering the screen with no burger menu, tables not adapting, text too small to read.',
  '- LOW CONTRAST: light-gray body text on a tinted near-white; unreadable placeholder text.',
  '- ENUM AS PLAIN TEXT: a status / category / tier / priority / type value shown as bare text in a',
  '  table cell or row (e.g. a "Status" column reading "active"/"pending" or a "Category" reading',
  '  "electronics" in plain body type). A low-cardinality enum should read as a coloured `<Badge>`',
  '  (a distinct hue per value), never plain text. Fix: render the enum field as a Badge colour-mapped',
  '  per value.',
  '- RAW UNFORMATTED DATE: a JavaScript Date printed verbatim, e.g. "Mon Jun 15 2026 02:00:00',
  '  GMT+0200 (Central European Summer Time)" — a dead giveaway of an unformatted `{date}` in',
  '  the markup. Real products show "15 Jun 2026" / "Jun 15, 2026" / "2 days ago". Also flag a',
  '  raw ISO string ("2026-06-15T00:00:00.000Z") shown to the user. Fix: format with',
  "  dayjs — `dayjs(d).format('D MMM YYYY')`.",
  '',
  'Then run one last test, because a screen can break none of the above and still be wrong:',
  'could someone look at this and say "an AI made that" without hesitating? A useful proxy —',
  'if you were told only what KIND of app this is, could you have predicted this exact screen?',
  'If yes, that is a finding in itself: the design was reached for rather than decided, and',
  'nothing about it belongs to THIS app rather than to its whole category. Say what is generic',
  'and name the specific alternative the subject suggests — its own materials, instruments and',
  'vocabulary are where a distinctive choice comes from. Being inoffensive is not passing.',
  '',
  'Return verdict "fix" only when there is at least one HIGH or MEDIUM finding worth a',
  'code change; otherwise "pass". Each fix must be SPECIFIC and actionable (name the element',
  'and the concrete change), not vague praise. Do not invent problems that are not visible.',
].join('\n')
