/**
 * Generates the main pikku-types.gen.ts file as a re-export hub
 */
export const serializePikkuTypesHub = (
  functionTypesImportPath: string,
  httpTypesImportPath: string,
  channelTypesImportPath: string,
  schedulerTypesImportPath: string,
  queueTypesImportPath: string,
  mcpTypesImportPath: string,
  cliTypesImportPath: string
) => {
  return `/**
 * This file was generated by the @pikku/cli
 * Main type export hub - re-exports all wiring-specific types for backwards compatibility
 */

// Core function, middleware, and permission types
export * from '${functionTypesImportPath}'

// HTTP wiring types
export * from '${httpTypesImportPath}'

// Channel wiring types
export * from '${channelTypesImportPath}'

// Scheduler wiring types
export * from '${schedulerTypesImportPath}'

// Queue wiring types
export * from '${queueTypesImportPath}'

// MCP wiring types
export * from '${mcpTypesImportPath}'

// CLI wiring types
export * from '${cliTypesImportPath}'
`
}
