/**
 * This file was generated by @pikku/cli@0.10.1
 */
/**
 * Auto-generated workflow queue workers
 *
 * This file contains:
 * - RPC step workers (one per RPC form step)
 * - Orchestrator workers (one per workflow)
 *
 * Do not edit manually - regenerate with 'npx pikku'
 */
import {
  pikkuSessionlessFunc,
  wireQueueWorker,
} from '../../.pikku/pikku-types.gen.js'

export const pikkuWorkflowWorker = pikkuSessionlessFunc({
  func: async ({ workflowState, rpc }, payload: any) => {
    const { runId, stepName, rpcName, data } = payload

    if (!workflowState) {
      throw new Error(
        'WorkflowState service not available in step worker, unable to proceed'
      )
    }

    // Idempotency check - skip if already done
    const stepState = await workflowState.getStepState(runId, stepName)
    if (stepState.status === 'done') {
      return
    }

    try {
      // Execute RPC
      const result = await rpc.invoke(rpcName, data)

      // Store result
      await workflowState.setStepResult(runId, stepName, result)

      // Trigger orchestrator to continue workflow
      await workflowState.addToQueue('pikku-workflow-orchestrator', runId)
    } catch (error: any) {
      // Store error
      await workflowState.setStepError(runId, stepName, error)

      // Mark workflow as failed
      await workflowState.updateRunStatus(runId, 'failed', undefined, {
        message: error.message,
        stack: error.stack,
        code: error.code,
      })

      throw error
    }
  },
})

export const pikkuWorkflowOrchestrator = pikkuSessionlessFunc({
  func: async ({ workflowState, rpc }, payload: any) => {
    const { runId } = payload

    if (!workflowState) {
      // TODO: Throw a better error message / typed
      throw new Error(
        'WorkflowState service not available in orchestrator worker'
      )
    }

    try {
      // Run workflow job (replays with caching)
      await workflowState.runWorkflowJob(runId, rpc.invoke.bind(rpc))
    } catch (error: any) {
      // WorkflowAsyncException is not an error - it means we scheduled a step
      if (error.name === 'WorkflowAsyncException') {
        // Workflow paused waiting for step completion
        return
      }

      // Real error - mark workflow as failed
      await workflowState.updateRunStatus(runId, 'failed', undefined, {
        message: error.message,
        stack: error.stack,
        code: error.code,
      })

      throw error
    }
  },
})

wireQueueWorker({
  queueName: 'pikku-workflow-step-worker',
  func: pikkuWorkflowWorker,
})

wireQueueWorker({
  queueName: 'pikku-workflow-orchestrator',
  func: pikkuWorkflowOrchestrator,
})
