/**
 * This file was generated by the @pikku/cli
 */
import './functions/pikku-functions-meta.gen.js'
import './channels/pikku-channels-meta.gen.js'
import './functions/pikku-functions.gen.js'
import './schemas/register.gen.js'
import './channels/pikku-channels.gen.js'
