/**
 * Type-safe RPC client backed by the snapshot SDK in `../sdk/`. The map is
 * a copy of fabric's generated rpc-map at the time of the addon's last
 * release — versioning bumps are taken by republishing this package.
 *
 * The snapshot lags: its header says @pikku/cli@0.12.21 against a live API
 * generated by 0.12.110, so an RPC missing from the map is not evidence that
 * fabric lacks it. When you need one that isn't there, check fabric's own
 * `packages/fabric-sdk/src/pikku/rpc-map.gen.d.ts` and copy the entry across
 * verbatim rather than reaching for whichever stale name happens to compile.
 */
import { PikkuRPC } from '../sdk/pikku-rpc.gen.js'

export function getFabricRPC(opts: {
  apiUrl: string
  token: string | null
}): PikkuRPC {
  const rpc = new PikkuRPC()
  rpc.setServerUrl(opts.apiUrl)
  rpc.setAuthorizationJWT(opts.token)
  return rpc
}
