/**
 * Generates the client-side `realtime.gen.ts`.
 *
 * Two surfaces:
 *
 *   - `PikkuRealtime` — websocket-based, multi-topic. Connects once to
 *     `/events`, then `subscribe(topic, handler)` / returned `unsubscribe`.
 *   - `subscribeToTopicViaSSE(topic, handler)` — lighter alternative.
 *     One EventSource = one topic, auto-cleanup on `close()`.
 *
 * Both are typed against `EventHubTopics` if the user supplies an import
 * via `clientFiles.realtimeEventHubTopicsImport`. Otherwise topics fall
 * back to `Record<string, unknown>`.
 */
export const serializeRealtimeClient = (
  topicsImport: string | undefined
): string => {
  const topicsTypeImport = topicsImport
    ? buildImportLine(topicsImport)
    : `// No EventHubTopics import configured. Set clientFiles.realtimeEventHubTopicsImport
// in pikku.config.json (e.g. \"../types/eventhub-topics.js#EventHubTopics\")
// to get fully-typed subscribe/unsubscribe.
type EventHubTopics = Record<string, unknown>`

  return `/**
 * Generated by @pikku/cli — do not edit.
 * Regenerate with \`pikku all\` (or \`pikku realtime\`).
 */
${topicsTypeImport}

type Handler<T> = (data: T) => void

type RealtimeMessage =
  | { topic: string; data: unknown }
  | unknown

interface RealtimeOptions {
  /** Full WebSocket URL, e.g. ws://localhost:3000/events */
  url: string
  /** Optional protocols passed to WebSocket constructor */
  protocols?: string | string[]
  /** Auto-reconnect with backoff (default: true) */
  reconnect?: boolean
  /** Initial reconnect delay in ms (default: 500) */
  reconnectDelayMs?: number
  /** Cap on reconnect delay (default: 10_000) */
  reconnectMaxDelayMs?: number
}

/**
 * WebSocket-based realtime client. Multi-topic per connection.
 *
 * \`\`\`ts
 * const realtime = new PikkuRealtime({ url: 'ws://localhost:3000/events' })
 * const off = realtime.subscribe('todo-created', ({ todo }) => { ... })
 * // later: off()
 * realtime.close()
 * \`\`\`
 */
export class PikkuRealtime {
  private ws: WebSocket | null = null
  private readonly handlers = new Map<string, Set<Handler<any>>>()
  private readonly options: Required<Omit<RealtimeOptions, 'protocols'>> & {
    protocols?: string | string[]
  }
  private reconnectAttempt = 0
  private closed = false

  constructor(options: RealtimeOptions) {
    this.options = {
      reconnect: options.reconnect ?? true,
      reconnectDelayMs: options.reconnectDelayMs ?? 500,
      reconnectMaxDelayMs: options.reconnectMaxDelayMs ?? 10_000,
      url: options.url,
      protocols: options.protocols,
    }
    this.connect()
  }

  subscribe<K extends keyof EventHubTopics & string>(
    topic: K,
    handler: Handler<EventHubTopics[K]>
  ): () => void {
    const set = this.handlers.get(topic) ?? new Set<Handler<any>>()
    if (set.size === 0) {
      this.send({ action: 'subscribe', topic })
    }
    set.add(handler)
    this.handlers.set(topic, set)
    return () => this.unsubscribe(topic, handler)
  }

  unsubscribe<K extends keyof EventHubTopics & string>(
    topic: K,
    handler?: Handler<EventHubTopics[K]>
  ): void {
    const set = this.handlers.get(topic)
    if (!set) return
    if (handler) set.delete(handler)
    else set.clear()
    if (set.size === 0) {
      this.handlers.delete(topic)
      this.send({ action: 'unsubscribe', topic })
    }
  }

  close(): void {
    this.closed = true
    this.handlers.clear()
    this.ws?.close()
    this.ws = null
  }

  private connect() {
    if (this.closed) return
    this.ws = new WebSocket(this.options.url, this.options.protocols)
    this.ws.onopen = () => {
      this.reconnectAttempt = 0
      // Re-subscribe everything we still care about
      for (const topic of this.handlers.keys()) {
        this.send({ action: 'subscribe', topic })
      }
    }
    this.ws.onmessage = (e: MessageEvent) => {
      let payload: RealtimeMessage
      try {
        payload =
          typeof e.data === 'string' ? JSON.parse(e.data) : (e.data as unknown)
      } catch {
        return
      }
      if (
        payload &&
        typeof payload === 'object' &&
        'topic' in (payload as any) &&
        typeof (payload as any).topic === 'string'
      ) {
        const { topic, data } = payload as { topic: string; data: unknown }
        const set = this.handlers.get(topic)
        if (set) for (const h of set) h(data)
      }
    }
    this.ws.onclose = () => {
      this.ws = null
      if (this.closed || !this.options.reconnect) return
      const delay = Math.min(
        this.options.reconnectDelayMs * 2 ** this.reconnectAttempt,
        this.options.reconnectMaxDelayMs
      )
      this.reconnectAttempt += 1
      setTimeout(() => this.connect(), delay)
    }
    this.ws.onerror = () => {
      // Let onclose handle reconnect
      this.ws?.close()
    }
  }

  private send(message: { action: 'subscribe' | 'unsubscribe'; topic: string }) {
    if (this.ws && this.ws.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(message))
    }
    // If not open, onopen replays current handler keys.
  }
}

/**
 * SSE alternative: one EventSource per topic. Auto-unsubscribes when you
 * call the returned \`close()\`. Use this in environments where WebSocket
 * is blocked, or when you only need a single-topic stream.
 *
 * \`\`\`ts
 * const sub = subscribeToTopicViaSSE('http://localhost:3000', 'todo-created', ({ todo }) => {...})
 * // later: sub.close()
 * \`\`\`
 */
export function subscribeToTopicViaSSE<
  K extends keyof EventHubTopics & string,
>(
  baseUrl: string,
  topic: K,
  handler: Handler<EventHubTopics[K]>
): { close: () => void } {
  const es = new EventSource(\`\${baseUrl.replace(/\\/$/, '')}/events/\${encodeURIComponent(topic)}\`)
  es.onmessage = (e: MessageEvent) => {
    try {
      handler(JSON.parse(e.data) as EventHubTopics[K])
    } catch {
      // Ignore malformed events
    }
  }
  return { close: () => es.close() }
}
`
}

function buildImportLine(spec: string): string {
  // Spec format: "<path>#<TypeName>"
  const hashIdx = spec.lastIndexOf('#')
  if (hashIdx === -1) {
    return `import type { EventHubTopics } from '${spec}'`
  }
  const path = spec.slice(0, hashIdx)
  const typeName = spec.slice(hashIdx + 1)
  if (typeName === 'EventHubTopics') {
    return `import type { EventHubTopics } from '${path}'`
  }
  return `import type { ${typeName} as EventHubTopics } from '${path}'`
}
