/**
 * Generates the client-side `realtime.gen.ts`.
 *
 * `PikkuRealtime` mirrors the `PikkuRPC` pattern: it wraps the project's
 * generated `PikkuFetch` (so server URL + auth come from one place) and
 * exposes:
 *
 *   - `subscribe(topic, handler)` / `unsubscribe(topic)` — typed pub/sub
 *     over the websocket at `/events`. Multi-topic per connection.
 *   - `subscribeToTopic(topic, handler)` — same shape but via SSE
 *     (one EventSource per topic, auto-cleanup on close).
 *   - `subscribeToSSE(path, handler)` — generic SSE subscribe for any
 *     `sse: true` route (workflow streams, agent streams, etc.).
 *   - `connectToChannel(channelRoute, protocols?)` — open a raw WebSocket
 *     for any wireChannel route, ready to wrap in
 *     `PikkuWebSocket<'channel-name'>` for typed subscribe/send.
 *
 * Topic types come from `EventHubTopics` if the user supplies an import
 * via `clientFiles.realtimeEventHubTopicsImport`. Otherwise topics fall
 * back to `Record<string, unknown>`.
 */
export const serializeRealtimeClient = (
  topicsImport: string | undefined
): string => {
  const topicsTypeImport = topicsImport
    ? buildImportLine(topicsImport)
    : `// No EventHubTopics import configured. Set clientFiles.realtimeEventHubTopicsImport
// in pikku.config.json (e.g. \"../types/eventhub-topics.js#EventHubTopics\")
// to get fully-typed subscribe/unsubscribe.
type EventHubTopics = Record<string, unknown>`

  return `/**
 * Generated by @pikku/cli — do not edit.
 * Regenerate with \`pikku all\` (or \`pikku realtime\`).
 */
import { PikkuFetch } from './pikku-fetch.gen.js'
${topicsTypeImport}

type Handler<T> = (data: T) => void

/**
 * Auth/options for SSE subscriptions. Headers can't be set on
 * EventSource, so auth must travel via cookies or a query parameter.
 */
interface SSEOptions {
  /** Appended as \`?access_token=...\` if set — server must accept it. */
  accessToken?: string
  /** Send cookies for cross-origin requests (server must allow it). */
  withCredentials?: boolean
  /** Handler for the underlying EventSource error event. */
  onError?: (event: Event) => void
}

interface RealtimeOptions {
  /** Auto-reconnect with backoff (default: true) */
  reconnect?: boolean
  /** Initial reconnect delay in ms (default: 500) */
  reconnectDelayMs?: number
  /** Cap on reconnect delay (default: 10_000) */
  reconnectMaxDelayMs?: number
}

/**
 * Realtime client. Mirrors the PikkuRPC pattern: wraps a PikkuFetch so
 * the server URL + auth are configured once and shared across transports.
 *
 * \`\`\`ts
 * const pikku = createPikku(PikkuFetch, PikkuRPC, { serverUrl: 'http://localhost:3000' })
 * const realtime = new PikkuRealtime()
 * realtime.setPikkuFetch(pikku.fetch)
 *
 * const off = realtime.subscribe('todo-created', ({ todo }) => { ... })
 * // later: off(); realtime.close()
 * \`\`\`
 */
export class PikkuRealtime {
  /** The underlying HTTP client used to derive server URL + auth */
  pikkuFetch = new PikkuFetch()

  private ws: WebSocket | null = null
  private readonly handlers = new Map<string, Set<Handler<any>>>()
  private readonly options: Required<RealtimeOptions>
  private reconnectAttempt = 0
  private closed = false
  private connectScheduled = false

  constructor(options: RealtimeOptions = {}) {
    this.options = {
      reconnect: options.reconnect ?? true,
      reconnectDelayMs: options.reconnectDelayMs ?? 500,
      reconnectMaxDelayMs: options.reconnectMaxDelayMs ?? 10_000,
    }
  }

  /**
   * Use a shared PikkuFetch instance (typically from \`createPikku(...)\`).
   * The realtime client picks up its server URL + auth from this fetch,
   * so you only configure connection details in one place.
   */
  setPikkuFetch(pikkuFetch: PikkuFetch): void {
    this.pikkuFetch = pikkuFetch
  }

  /** Sets the base server URL on the underlying PikkuFetch. */
  setServerUrl(serverUrl: string): void {
    this.pikkuFetch.setServerUrl(serverUrl)
  }

  /**
   * Sets the JWT on the underlying PikkuFetch.
   *
   * IMPORTANT — the browser \`EventSource\` (and \`WebSocket\`) constructors
   * cannot set \`Authorization\` headers, so this JWT does NOT travel on
   * SSE or WebSocket connections automatically. For realtime auth pick
   * one of:
   *   - cookie-based session (works because SSE/WS send cookies for the
   *     fetch's origin),
   *   - call \`subscribeToSSE(path, handler, { accessToken: jwt })\` so the
   *     token is appended as a query string param the server can read.
   * The header still applies to plain HTTP calls made via the same
   * PikkuFetch.
   */
  setAuthorizationJWT(jwt: string | null): void {
    this.pikkuFetch.setAuthorizationJWT(jwt)
  }

  /**
   * Sets the API key on the underlying PikkuFetch. Same caveat as
   * \`setAuthorizationJWT\` — this header is not carried by SSE or
   * WebSocket connections.
   */
  setAPIKey(apiKey: string | null): void {
    this.pikkuFetch.setAPIKey(apiKey)
  }

  /**
   * Subscribe to a typed event topic over the websocket. Returns an
   * \`unsubscribe\` function. Auto-reconnects re-send subscriptions.
   */
  subscribe<K extends keyof EventHubTopics & string>(
    topic: K,
    handler: Handler<EventHubTopics[K]>
  ): () => void {
    const set = this.handlers.get(topic) ?? new Set<Handler<any>>()
    if (set.size === 0) {
      this.send({ action: 'subscribe', topic })
    }
    set.add(handler)
    this.handlers.set(topic, set)
    this.ensureConnected()
    return () => this.unsubscribe(topic, handler)
  }

  unsubscribe<K extends keyof EventHubTopics & string>(
    topic: K,
    handler?: Handler<EventHubTopics[K]>
  ): void {
    const set = this.handlers.get(topic)
    if (!set) return
    if (handler) set.delete(handler)
    else set.clear()
    if (set.size === 0) {
      this.handlers.delete(topic)
      this.send({ action: 'unsubscribe', topic })
    }
  }

  /**
   * SSE alternative for a single topic stream. One EventSource per topic;
   * close the returned object to unsubscribe (the server cleans up
   * automatically on disconnect).
   */
  subscribeToTopic<K extends keyof EventHubTopics & string>(
    topic: K,
    handler: Handler<EventHubTopics[K]>,
    options: SSEOptions = {}
  ): { close: () => void } {
    return this.subscribeToSSE<EventHubTopics[K]>(
      \`/events/\${encodeURIComponent(topic)}\`,
      handler,
      options
    )
  }

  /**
   * Generic SSE subscribe. Use for any \`sse: true\` HTTP route in your
   * project. Caller supplies the path (with any params/query) — the base
   * URL comes from the wrapped PikkuFetch.
   *
   * Auth: \`EventSource\` cannot set headers, so the JWT/API key from the
   * underlying PikkuFetch are NOT sent automatically. Provide one of:
   *   - \`accessToken\` — appended as \`?access_token=…\` (server must
   *     accept query-string auth on the route),
   *   - \`withCredentials: true\` — instructs the browser to send cookies
   *     for cross-origin SSE (server origin must allow credentials).
   *
   * \`\`\`ts
   * const sub = realtime.subscribeToSSE<{ progress: number }>(
   *   \`/workflow-run/\${runId}/stream\`,
   *   (e) => setProgress(e.progress),
   *   { withCredentials: true }
   * )
   * \`\`\`
   */
  subscribeToSSE<T = unknown>(
    path: string,
    handler: Handler<T>,
    options: SSEOptions = {}
  ): { close: () => void } {
    let url = this.resolveHttpUrl(path)
    if (options.accessToken) {
      const sep = url.includes('?') ? '&' : '?'
      url += \`\${sep}access_token=\${encodeURIComponent(options.accessToken)}\`
    }
    const es = new EventSource(url, {
      withCredentials: options.withCredentials ?? false,
    })
    es.onmessage = (e: MessageEvent) => {
      try {
        handler(JSON.parse(e.data) as T)
      } catch {
        // Ignore malformed events
      }
    }
    if (options.onError) es.onerror = options.onError
    return { close: () => es.close() }
  }

  /**
   * Open a raw WebSocket against one of the project's wireChannel routes.
   * Wrap the returned socket in \`PikkuWebSocket<'channel-name'>\` from the
   * generated websocket client for typed subscribe/send.
   */
  connectToChannel(
    channelPath: string,
    protocols?: string | string[]
  ): WebSocket {
    return new WebSocket(this.resolveWsUrl(channelPath), protocols)
  }

  /** Disconnect the events websocket and clear all subscriptions. */
  close(): void {
    this.closed = true
    this.handlers.clear()
    this.ws?.close()
    this.ws = null
  }

  private ensureConnected() {
    if (this.ws || this.connectScheduled || this.closed) return
    this.connect()
  }

  private connect() {
    if (this.closed) return
    this.connectScheduled = false
    const url = this.resolveWsUrl('/events')
    this.ws = new WebSocket(url)
    this.ws.onopen = () => {
      this.reconnectAttempt = 0
      for (const topic of this.handlers.keys()) {
        this.send({ action: 'subscribe', topic })
      }
    }
    this.ws.onmessage = (e: MessageEvent) => {
      let payload: unknown
      try {
        payload =
          typeof e.data === 'string' ? JSON.parse(e.data) : (e.data as unknown)
      } catch {
        return
      }
      if (
        payload &&
        typeof payload === 'object' &&
        'topic' in (payload as any) &&
        typeof (payload as any).topic === 'string'
      ) {
        const { topic, data } = payload as { topic: string; data: unknown }
        const set = this.handlers.get(topic)
        if (set) for (const h of set) h(data)
      }
    }
    this.ws.onclose = () => {
      this.ws = null
      if (this.closed || !this.options.reconnect) return
      const delay = Math.min(
        this.options.reconnectDelayMs * 2 ** this.reconnectAttempt,
        this.options.reconnectMaxDelayMs
      )
      this.reconnectAttempt += 1
      this.connectScheduled = true
      setTimeout(() => this.connect(), delay)
    }
    this.ws.onerror = () => {
      this.ws?.close()
    }
  }

  private send(message: { action: 'subscribe' | 'unsubscribe'; topic: string }) {
    if (this.ws && this.ws.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(message))
    }
    // If not open, onopen replays current handler keys.
  }

  private resolveHttpUrl(path: string): string {
    const base = this.pikkuFetch.getServerUrl()
    if (!base) {
      throw new Error(
        'PikkuRealtime: no server URL — call setServerUrl(...) or setPikkuFetch(...) first.'
      )
    }
    return \`\${base}\${path.startsWith('/') ? path : \`/\${path}\`}\`
  }

  private resolveWsUrl(path: string): string {
    const httpUrl = this.resolveHttpUrl(path)
    return httpUrl.replace(/^http/i, 'ws')
  }
}
`
}

// Allow only the characters that legitimately appear in a module
// specifier: paths, scoped package names, the optional `#TypeName`
// suffix, and dots. Refusing the rest closes a generated-source
// injection vector if pikku.config.json comes from an untrusted source.
const SAFE_SPEC = /^[A-Za-z0-9./_\-#@]+$/
const SAFE_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function buildImportLine(spec: string): string {
  if (!SAFE_SPEC.test(spec)) {
    throw new Error(
      `clientFiles.realtimeEventHubTopicsImport contains unsupported characters: ${JSON.stringify(spec)}. Allowed: letters, digits, ./_-#@`
    )
  }
  const hashIdx = spec.lastIndexOf('#')
  const path = hashIdx === -1 ? spec : spec.slice(0, hashIdx)
  const typeName = hashIdx === -1 ? 'EventHubTopics' : spec.slice(hashIdx + 1)

  if (!SAFE_IDENT.test(typeName)) {
    throw new Error(
      `clientFiles.realtimeEventHubTopicsImport type name is not a valid identifier: ${JSON.stringify(typeName)}`
    )
  }
  // JSON.stringify is safe here because path passed SAFE_SPEC — no
  // quotes, backticks, or control chars to escape.
  if (typeName === 'EventHubTopics') {
    return `import type { EventHubTopics } from ${JSON.stringify(path)}`
  }
  return `import type { ${typeName} as EventHubTopics } from ${JSON.stringify(path)}`
}
