import type { SystemRoleDefinitions } from '@pikku/core/ecosystem/role'

export interface SerializeRolesOptions {
  definitions: SystemRoleDefinitions
}

const quote = (value: string) => `'${value.replace(/'/g, "\\'")}'`

/**
 * Generates the `SystemRoleName` union and role metadata from
 * `defineSystemRole` declarations.
 *
 * The union is what makes a persona's `roles: ['buyer']` checkable. Custom
 * roles are deliberately absent: an admin can delete one from the console, so
 * a persona pinned to it would silently stop testing what it claims to — the
 * failure would be a scatter of 403s rather than a build error.
 */
export const serializeRolesTypes = ({ definitions }: SerializeRolesOptions) => {
  const names = [...new Set(definitions.map((d) => d.name))].sort()

  const union =
    names.length > 0
      ? `\n${names.map((name) => `  | ${quote(name)}`).join('\n')}`
      : ' never'

  return `/**
 * This file was generated by the @pikku/cli
 */
import type { SystemRole, SystemRoleDefinitionsMeta } from '@pikku/core/ecosystem/role'
import { flattenSystemRoleDefinitions } from '@pikku/core/ecosystem/role'
import definitions from './pikku-roles-meta.gen.json' with { type: 'json' }

/**
 * Every role that ships with this application.
 *
 * Roles an admin composes in the console are not here and cannot be: they do
 * not exist at build time, and can be deleted after it.
 */
export type SystemRoleName =${union}

/**
 * The declared role set, for a ScopeService to sync into its store.
 *
 * Derived from the metadata sidecar rather than inlined, so the import above
 * forces tsc to emit the .json alongside this file — an addon publishes only
 * its compiled output, and a host reads that .json to merge the addon's roles
 * into its own union.
 *
 * Additive on removal: a deleted declaration leaves an inert row rather than
 * revoking everyone's grant on deploy. Use \`pikku roles prune\` to remove them.
 */
export const SYSTEM_ROLES: SystemRole[] = flattenSystemRoleDefinitions(
  Object.values(definitions as SystemRoleDefinitionsMeta)
)

/** Declared roles, keyed by name. Rendered by the console when granting. */
export const SYSTEM_ROLES_META: Record<string, SystemRole> = Object.fromEntries(
  SYSTEM_ROLES.map((role) => [role.name, role])
)

/** Whether a role name is declared in code, and therefore not editable. */
export const isSystemRole = (name: string): boolean =>
  Object.prototype.hasOwnProperty.call(SYSTEM_ROLES_META, name)
`
}
