import type { FeatureFlagDefinitions } from '@pikku/core/flag'
import { tsLiteral } from '../../../utils/ts-literal.js'

export interface SerializeFlagsOptions {
  definitions: FeatureFlagDefinitions
}

/**
 * Generates the `FeatureFlagName` union and flag metadata from
 * `defineFeatureFlags` declarations.
 *
 * The union is what makes `featureFlag: 'sandboxes'` on a function checkable. A
 * typo in a flag name would otherwise fail open — an unknown key is absent from
 * every snapshot, and an absent key is available — so the misspelled gate would
 * silently never close.
 */
export const serializeFlagsTypes = ({ definitions }: SerializeFlagsOptions) => {
  const names = [...new Set(definitions.map((d) => d.name))].sort()

  const union =
    names.length > 0
      ? `\n${names.map((name) => `  | ${tsLiteral(name)}`).join('\n')}`
      : ' never'

  return `/**
 * This file was generated by the @pikku/cli
 */
/** Every feature flag declared in this application. */
export type FeatureFlagName =${union}
`
}

/**
 * The generated manifest of what the application declared, beside the union and
 * not in it. The leaf barrel re-exports the union file because a function
 * annotates with `FeatureFlagName`; these values are read by generated code and
 * by whoever wires a flag store, and they are imported by path, as
 * `requiredSingletonServices` is.
 */
export const serializeFlagsManifest = () => {
  return `/**
 * This file was generated by the @pikku/cli
 */
import type { DeclaredFlag, FeatureFlagDefinitionsMeta } from '@pikku/core/flag'
import {
  compiledFallbackSnapshot,
  flattenFeatureFlagDefinitions,
} from '@pikku/core/flag'
import type { FeatureFlagName } from './pikku-flags.gen.js'
import definitions from './pikku-flags-meta.gen.json' with { type: 'json' }

/**
 * The declared flag set, for a FeatureFlagStore to sync into its store.
 *
 * Derived from the metadata sidecar rather than inlined, so the import above
 * forces tsc to emit the .json alongside this file — an addon publishes only
 * its compiled output, and a host reads that .json to merge the addon's flags
 * into its own union.
 *
 * Additive on removal: a deleted declaration leaves the row marked
 * \`declared: false\` rather than switching a feature off on deploy. Use
 * \`pikku flags prune\` to remove them.
 */
export const declaredFeatureFlags: DeclaredFlag[] = flattenFeatureFlagDefinitions(
  Object.values(definitions as FeatureFlagDefinitionsMeta)
)

/**
 * Declared flags, keyed by name. Rendered by the console beside each switch.
 *
 * Keyed by \`FeatureFlagName\` so a misspelled lookup is a type error, which is
 * the whole point of generating the union. The assertion is what
 * \`Object.fromEntries\` costs — it returns an index signature — and it is
 * sound here because both this object and the union are built from
 * \`declaredFeatureFlags\`, so every key of the union is present.
 */
export const featureFlagsMeta = Object.fromEntries(
  declaredFeatureFlags.map((flag) => [flag.name, flag])
) as Record<FeatureFlagName, DeclaredFlag>

/**
 * What a flag source falls back to when its backing store cannot be read: every
 * declared flag on, no rollout, no overrides.
 *
 * Failing open is deliberate. A flag store is not an authorization boundary —
 * \`scopes:\` is — so an unreadable config must not take the product down with
 * it.
 */
export const featureFlagsFallback = compiledFallbackSnapshot(declaredFeatureFlags)
`
}
