-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "pikku_trigger_source" ("name" text primary key, "kind" text not null, "base_url" text, "label_prefix" text, "declared" boolean default true not null, "enabled" boolean default false not null, "status" text, "state" text, "detail" text, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create table "pikku_lease" ("key" text primary key, "holder" text not null, "token" integer not null, "expires_at" bigint not null);

ALTER TABLE workflow_step ADD COLUMN lease_expires_at bigint;
