/**
 * This file was generated by the @pikku/cli
 */
import './pikku-functions-meta.gen.js'
import './pikku-schedules-meta.gen.js'
import './pikku-functions.gen.js'
import './pikku-schemas/register.gen.js'
import './pikku-schedules.gen.js'
