import { basename } from 'node:path'

import { pikkuVoidFunc } from '#pikku'
import { analyzeDeployment } from '../../deploy/analyzer/index.js'
import { bundleUnits } from '../../deploy/bundler/index.js'
import { generatePlan } from '../../deploy/plan/index.js'
import { applyPlan } from '../../deploy/plan/executor.js'
import { formatPlan } from '../../deploy/plan/formatter.js'
import type { DeployProvider } from '../../deploy/plan/provider.js'
import type { PlanChange } from '../../deploy/plan/types.js'

const ANSI = {
  green: '\x1b[32m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  dim: '\x1b[2m',
  bold: '\x1b[1m',
  reset: '\x1b[0m',
}

function createEmptyProvider(): DeployProvider {
  return {
    async getCurrentState() {
      // TODO: Load provider from config and get real state
      return {
        units: [],
        queues: [],
        scheduledTasks: [],
        secrets: [],
        variables: {},
      }
    },
    async applyChange(_change, _manifest) {
      // TODO: Delegate to provider package (e.g. @pikku/deploy-cloudflare)
      // For now, this is a stub
      await new Promise((r) => setTimeout(r, 100))
    },
    async hasActiveWork() {
      return { active: false, pendingCount: 0 }
    },
  }
}

function logProgress(
  change: PlanChange,
  status: 'start' | 'done' | 'error',
  error?: string
) {
  const action = change.action
  const color =
    action === 'create'
      ? ANSI.green
      : action === 'update'
        ? ANSI.blue
        : action === 'delete'
          ? ANSI.red
          : ANSI.yellow

  if (status === 'start') {
    process.stdout.write(
      `  ${color}${action}${ANSI.reset} ${change.resourceType} ${ANSI.bold}${change.name}${ANSI.reset}...`
    )
  } else if (status === 'done') {
    process.stdout.write(` ${ANSI.green}done${ANSI.reset}\n`)
  } else {
    process.stdout.write(` ${ANSI.red}error: ${error}${ANSI.reset}\n`)
  }
}

export const deployApply = pikkuVoidFunc({
  func: async ({ logger, config, getInspectorState }) => {
    const projectDir = config.rootDir

    // Step 1: Analyze
    logger.info('Analyzing project...')
    const inspectorState = await getInspectorState(true)
    const projectId = basename(projectDir)
    const manifest = analyzeDeployment(inspectorState, { projectId })
    logger.info(
      `Found ${manifest.units.length} units, ${manifest.queues.length} queues, ${manifest.scheduledTasks.length} scheduled tasks`
    )

    // Step 2: Bundle
    // TODO: Load provider-specific entry generator based on --provider flag
    // For now, stub entry files (real implementation comes from deploy provider package)
    logger.info('Bundling units...')
    const entryFiles = new Map<string, string>()
    // Entry files would be generated by the deploy provider
    const { results: bundled, errors: bundleErrors } = await bundleUnits(
      projectDir,
      manifest,
      entryFiles
    )
    logger.info(
      `Bundled ${bundled.length} units${bundleErrors.length > 0 ? ` (${bundleErrors.length} failed)` : ''}`
    )

    if (bundleErrors.length > 0) {
      for (const f of bundleErrors) {
        logger.error(`  Failed: ${f.unitName} — ${f.error}`)
      }
    }

    // Step 3: Plan
    logger.info('Planning deployment...')
    const provider = createEmptyProvider()
    const currentState = await provider.getCurrentState(manifest.projectId)
    const plan = await generatePlan(manifest, currentState, provider)

    console.log('')
    console.log(formatPlan(plan))
    console.log('')

    if (plan.changes.length === 0) {
      logger.info('Nothing to deploy.')
      return
    }

    // Step 4: Apply
    logger.info('Applying...')
    const result = await applyPlan(plan, manifest, provider, {
      onProgress: logProgress,
    })

    console.log('')
    if (result.success) {
      logger.info(`${ANSI.green}${ANSI.bold}Deployment complete.${ANSI.reset}`)
    } else {
      const errors = result.applied.filter((r) => r.status === 'error')
      logger.error(`Deployment finished with ${errors.length} error(s).`)
    }
  },
})
