name: Branch
run-name: Branch
on:
  push:
    branches-ignore:
      - master
      - develop
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn build
      # - run: yarn test
      - run: yarn prettier
      - run: yarn lint
      - run: yarn typedoc
      - name: Save build output (for later jobs)
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: packages/**/dist
          retention-days: 1

  templates:
    name: Templates
    runs-on: ubuntu-latest
    needs: main
    strategy:
      matrix:
        version: [22]
        template: [
            # express,
            express-middleware,
            # fastify,
            fastify-plugin,
            uws,
            aws-lambda,
            # aws-lambda-websockets,
            cloudflare-workers,
            # cloudflare-websockets,
            # nextjs,
          ]
        package-manager: [yarn]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: yarn
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages
      - name: Install dependencies
        run: yarn install
      - run: cd packages/create && node ./dist/index.js --template ${{ matrix.template }} --version ${{ github.ref_name }} --name ../../../test-app --install --package-manager ${{ matrix.package-manager}} --yarn-link ../pikku
      - run: cd ../test-app && yarn link -A ../pikku && yarn run test
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      USES_WEBSOCKET: ${{ matrix.template }}
