name: Branch
run-name: Branch
on:
  push:
    branches-ignore:
      - master
      - develop
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn prettier
      - run: yarn lint
      - run: yarn typedoc
