name: CI

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  e2e:
    needs: build
    uses: ./.github/workflows/e2e.yml

  # e2e-ai:
  #   needs: [e2e, verifiers, templates]
  #   uses: ./.github/workflows/e2e-ai.yml
  #   secrets:
  #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  verifiers:
    needs: build
    uses: ./.github/workflows/verifiers.yml

  templates:
    needs: build
    uses: ./.github/workflows/templates.yml
    secrets:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  release-dry-run:
    needs: [verifiers, templates, e2e]
    uses: ./.github/workflows/release.yml
    with:
      dry-run: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
