name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  e2e:
    needs: build
    uses: ./.github/workflows/e2e.yml

  # e2e-ai:
  #   needs: [e2e, verifiers, templates]
  #   uses: ./.github/workflows/e2e-ai.yml
  #   secrets:
  #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  verifiers:
    needs: build
    uses: ./.github/workflows/verifiers.yml

  templates:
    needs: build
    uses: ./.github/workflows/templates.yml
    secrets:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  release:
    needs: [verifiers, templates, e2e]
    uses: ./.github/workflows/release.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  sync-templates-stackblitz:
    name: Sync Templates
    runs-on: ubuntu-latest
    needs: release
    environment: sync-templates-approval
    strategy:
      fail-fast: false
      matrix:
        version: [24]
        template:
          [
            express,
            express-middleware,
            fastify,
            fastify-plugin,
            uws,
            ws,
            aws-lambda,
            aws-lambda-websocket,
            cloudflare-workers,
            cloudflare-websocket,
            nextjs,
            mcp-server,
            cli,
            pg-boss,
            bullmq,
            workflows-bullmq,
            workflows-pg-boss,
            remote-rpc-pg,
            remote-rpc-redis,
          ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create Template
        run: npm create pikku@latest -- --template ${{ matrix.template }} --version ${{ github.ref_name }} --name ../test-app --install --package-manager npm --stackblitz

      - name: Sync template repository
        run: ./scripts/sync-template-repos.sh ${{ matrix.template }} --apply --token ${{ secrets.SYNC_TOKEN_GITHUB }}
