name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test:coverage
      - run: yarn prettier
      - run: yarn lint
      - run: yarn typedoc

      - name: Save build output (for later jobs)
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: packages/**/dist
          retention-days: 1

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.cjs
          publish: yarn release
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4

  templates:
    name: Templates
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        version: [22]
        template: [express]
        package-manager: [npm]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: packages
      - name: Install dependencies for create
        run: yarn install # TODO: This should only need to install create
      - run: cd packages/create && node ./dist/index.js --template ${{ matrix.template }} --version ${{ github.ref_name }} --name my-app --install --package-manager ${{ matrix.package-manager}}
      - run:  cd packages/create/my-app && yarn test
