name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  templates:
    name: Templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22]
        template: [express]
        package-manager: [npm]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: yarn install
      - run: yarn build
      - run: cd packages/create && ./dist/index.js --template ${{ matrix.template }} --version ${{ github.ref_name }} --name my-app --install --package-manager ${{ matrix.package-manager}}
      - run: cd my-app && yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test:coverage
      - run: yarn prettier
      - run: yarn lint
      - run: yarn typedoc

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.cjs
          publish: yarn release
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
