name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: corepack enable
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn prettier
      - run: yarn lint
      - run: yarn typedoc

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.cjs
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
